begin;
create function pg_temp.fail_offseason_late_event() returns trigger language plpgsql as $$begin if new.idempotency_key='disposable:offseason:late-event-failure' then raise exception 'forced late event failure';end if;return new;end$$;
create trigger offseason_late_event_failure before insert on public.contract_events for each row execute function pg_temp.fail_offseason_late_event();
do $$
declare lid uuid;other_lid uuid;tid uuid;other_tid uuid;actor uuid;member_actor uuid;yr int;
 pids text[];pid text;pid2 text;pid3 text;pid4 text;pid5 text;result jsonb;agreement_id uuid;draft_request jsonb;
begin
 select ls.league_id,ls.season into lid,yr from public.league_seasons ls where ls.is_active order by ls.created_at desc limit 1;
 select id into tid from public.league_teams where league_id=lid order by id limit 1;
 select id into other_tid from public.league_teams where league_id=lid and id<>tid order by id limit 1;
 select user_id into actor from public.league_memberships where league_id=lid and lower(role)='commissioner' order by id limit 1;
 select user_id into member_actor from public.league_memberships where league_id=lid and lower(role)='member' order by id limit 1;
 select l.id into other_lid from public.leagues l where l.id<>lid and exists(select 1 from public.league_seasons s where s.league_id=l.id and s.is_active) limit 1;
 select array_agg(sleeper_id order by sleeper_id) into pids from (select sleeper_id from public.player_universe p where not exists(select 1 from public.contract_agreements a where a.league_id=lid and a.player_id=p.sleeper_id and a.status in('active','scheduled')) order by sleeper_id limit 5) q;
 pid:=pids[1];pid2:=pids[2];pid3:=pids[3];pid4:=pids[4];pid5:=pids[5];
 perform set_config('request.jwt.claim.sub',actor::text,true);

 result:=public.acquire_offseason_player_authenticated(jsonb_build_object('league_id',lid,'league_team_id',tid,'player_id',pid,'season',yr,'salary',8,'years',1,'acquisition_type','fa_auction','idempotency_key','disposable:offseason:auction'));
 agreement_id:=(result->>'contract_agreement_id')::uuid;
 if (select count(*) from public.contract_agreements where id=agreement_id and league_team_id=tid and status='active')<>1 or (select count(*) from public.contract_seasons where contract_id=agreement_id)<>1 or (select count(*) from public.contract_events where contract_id=agreement_id and event_type='signed')<>1 then raise exception 'canonical acquisition failed';end if;
 result:=public.acquire_offseason_player_authenticated(jsonb_build_object('league_id',lid,'league_team_id',tid,'player_id',pid,'season',yr,'salary',8,'years',1,'acquisition_type','fa_auction','idempotency_key','disposable:offseason:auction'));
 if coalesce((result->>'idempotent')::boolean,false) is not true or (select count(*) from public.contract_agreements where league_id=lid and player_id=pid and status='active')<>1 then raise exception 'exact acquisition replay failed';end if;
 begin perform public.acquire_offseason_player_authenticated(jsonb_build_object('league_id',lid,'league_team_id',tid,'player_id',pid,'season',yr,'salary',9,'years',1,'acquisition_type','fa_auction','idempotency_key','disposable:offseason:auction'));raise exception 'changed acquisition replay accepted';exception when others then if sqlerrm='changed acquisition replay accepted' then raise;end if;end;
 begin perform public.release_offseason_player_authenticated(jsonb_build_object('league_id',lid,'league_team_id',tid,'player_id',pid,'season',yr,'dead_cap',0,'idempotency_key','disposable:offseason:auction'));raise exception 'cross-operation key accepted';exception when others then if sqlerrm='cross-operation key accepted' then raise;end if;end;
 begin perform public.acquire_offseason_player_authenticated(jsonb_build_object('league_id',lid,'league_team_id',tid,'player_id',pid,'season',yr,'salary',8,'years',1,'acquisition_type','fa_auction','idempotency_key','disposable:offseason:auction:second'));raise exception 'duplicate live ownership accepted';exception when others then if sqlerrm='duplicate live ownership accepted' then raise;end if;end;
 begin perform public.acquire_offseason_player_authenticated(jsonb_build_object('league_id',lid,'league_team_id',tid,'player_id',pid2,'season',yr,'salary',5,'years',20,'acquisition_type','commissioner_manual_add','idempotency_key','disposable:offseason:missing-schedule'));raise exception 'incomplete schedule accepted';exception when others then if sqlerrm='incomplete schedule accepted' then raise;end if;end;
 if exists(select 1 from public.contract_agreements where league_id=lid and player_id=pid2) or exists(select 1 from public.contract_events where idempotency_key='disposable:offseason:missing-schedule') then raise exception 'late schedule failure left partial rows';end if;

 result:=public.release_offseason_player_authenticated(jsonb_build_object('league_id',lid,'league_team_id',tid,'player_id',pid,'season',yr,'dead_cap',4,'idempotency_key','disposable:offseason:drop'));
 if (select count(*) from public.contract_agreements where id=agreement_id and status='released')<>1 or exists(select 1 from public.contract_seasons where contract_id=agreement_id and obligation_status in('active','scheduled')) or (select count(*) from public.contract_events where contract_id=agreement_id and event_type='dead_cap_created' and (metadata->>'dead_cap_amount')::numeric=4 and metadata->>'penalty_rule'='commissioner_manual_drop')<>1 or (select count(*) from public.dead_cap_obligations where contract_agreement_id=agreement_id and amount=4 and status='active')<>1 then raise exception 'canonical release/dead cap failed';end if;
 result:=public.release_offseason_player_authenticated(jsonb_build_object('league_id',lid,'league_team_id',tid,'player_id',pid,'season',yr,'dead_cap',4,'idempotency_key','disposable:offseason:drop'));
 if coalesce((result->>'idempotent')::boolean,false) is not true or (select count(*) from public.dead_cap_obligations where contract_agreement_id=agreement_id)<>1 then raise exception 'release replay duplicated evidence';end if;
 begin perform public.release_offseason_player_authenticated(jsonb_build_object('league_id',lid,'league_team_id',tid,'player_id',pid,'season',yr,'dead_cap',5,'idempotency_key','disposable:offseason:drop'));raise exception 'changed release replay accepted';exception when others then if sqlerrm='changed release replay accepted' then raise;end if;end;
 begin perform public.release_offseason_player_authenticated(jsonb_build_object('league_id',lid,'league_team_id',tid,'player_id',pid,'season',yr+1,'dead_cap',0,'idempotency_key','disposable:offseason:wrong-season'));raise exception 'invalid release season accepted';exception when others then if sqlerrm='invalid release season accepted' then raise;end if;end;

 perform public.acquire_offseason_player_authenticated(jsonb_build_object('league_id',lid,'league_team_id',tid,'player_id',pid3,'season',yr,'salary',3,'years',1,'acquisition_type','commissioner_manual_add','idempotency_key','disposable:offseason:zero-cap-add'));
 begin perform public.release_offseason_player_authenticated(jsonb_build_object('league_id',lid,'league_team_id',other_tid,'player_id',pid3,'season',yr,'dead_cap',0,'idempotency_key','disposable:offseason:wrong-team'));raise exception 'wrong-team release accepted';exception when others then if sqlerrm='wrong-team release accepted' then raise;end if;end;
 perform public.release_offseason_player_authenticated(jsonb_build_object('league_id',lid,'league_team_id',tid,'player_id',pid3,'season',yr,'dead_cap',0,'idempotency_key','disposable:offseason:zero-cap-drop'));
 if exists(select 1 from public.dead_cap_obligations where idempotency_key like 'disposable:offseason:zero-cap-drop%') or exists(select 1 from public.contract_events where idempotency_key='disposable:offseason:zero-cap-drop:dead-cap-event') then raise exception 'zero dead cap created bogus evidence';end if;

 update public.player_universe set rookie_class_year=yr+1,draft_year=yr+1,pos='RB',nfl_status='PROSPECT',market_pool='ROOKIE_PROSPECT',active=true where sleeper_id in(pid4,pid5);
 update public.player_universe set rookie_class_year=yr,draft_year=yr,pos='RB',nfl_status='PROSPECT',market_pool='ROOKIE_PROSPECT',active=true where sleeper_id=pid2;
 draft_request:=jsonb_build_object('league_id',lid,'draft_year',yr+1,'idempotency_key','disposable:rookie-board:upcoming','picks',jsonb_build_array(jsonb_build_object('league_team_id',tid,'player_id',pid4,'draft_round',1,'round_pick',1,'original_salary',2,'original_contract_term',1,'one_time_option_salary',7)));
 perform public.persist_rookie_draft_board_authenticated(draft_request);perform public.persist_rookie_draft_board_authenticated(draft_request);
 if (select count(*) from public.rookie_draft_board_assignments where league_id=lid and draft_year=yr+1 and player_id=pid4)<>1 or (select count(*) from public.contract_agreements where league_id=lid and player_id=pid4 and start_season=yr+1 and status='scheduled')<>1 or exists(select 1 from public.league_seasons where league_id=lid and season=yr+1 and is_active) then raise exception 'upcoming draft acquisition/replay failed';end if;
 begin perform public.persist_rookie_draft_board_authenticated(jsonb_set(draft_request,'{picks,0,player_id}',to_jsonb(pid5)));raise exception 'same pick different player accepted';exception when others then if sqlerrm='same pick different player accepted' then raise;end if;end;
 begin perform public.persist_rookie_draft_board_authenticated(jsonb_set(draft_request,'{picks,0,league_team_id}',to_jsonb(other_tid::text)));raise exception 'same pick different team accepted';exception when others then if sqlerrm='same pick different team accepted' then raise;end if;end;
 begin perform public.persist_rookie_draft_board_authenticated(jsonb_set(draft_request,'{picks,0,round_pick}','2'::jsonb));raise exception 'same player different pick accepted';exception when others then if sqlerrm='same player different pick accepted' then raise;end if;end;
 draft_request:=jsonb_build_object('league_id',lid,'draft_year',yr,'idempotency_key','disposable:rookie-board:active','picks',jsonb_build_array(jsonb_build_object('league_team_id',tid,'player_id',pid2,'draft_round',1,'round_pick',2,'original_salary',2,'original_contract_term',1,'one_time_option_salary',7)));
 perform public.persist_rookie_draft_board_authenticated(draft_request);
 if not exists(select 1 from public.contract_agreements where league_id=lid and player_id=pid2 and start_season=yr and status='active') then raise exception 'active-year rookie acquisition failed';end if;

 begin perform public.acquire_offseason_player_private(jsonb_build_object('league_id',lid,'league_team_id',tid,'player_id',pid5,'season',yr,'salary',1,'years',1,'acquisition_type','fa_auction','idempotency_key','disposable:offseason:late-event-failure'),actor);raise exception 'late event failure unexpectedly committed';exception when others then if sqlerrm='late event failure unexpectedly committed' then raise;end if;end;
 if exists(select 1 from public.contract_agreements where league_id=lid and player_id=pid5) or exists(select 1 from public.contract_seasons where league_id=lid and player_id=pid5) or exists(select 1 from public.contract_events where idempotency_key='disposable:offseason:late-event-failure') then raise exception 'late failure did not roll back all acquisition rows';end if;

 perform set_config('request.jwt.claim.sub',member_actor::text,true);
 begin perform public.acquire_offseason_player_authenticated(jsonb_build_object('league_id',lid,'league_team_id',tid,'player_id',pid5,'season',yr,'salary',1,'years',1,'acquisition_type','fa_auction','idempotency_key','member-acquire'));raise exception 'member acquisition accepted';exception when others then if sqlerrm='member acquisition accepted' then raise;end if;end;
 begin perform public.release_offseason_player_authenticated(jsonb_build_object('league_id',lid,'league_team_id',tid,'player_id',pid5,'season',yr,'dead_cap',0,'idempotency_key','member-release'));raise exception 'member release accepted';exception when others then if sqlerrm='member release accepted' then raise;end if;end;
 begin perform public.persist_rookie_draft_board_authenticated(draft_request);raise exception 'member draft accepted';exception when others then if sqlerrm='member draft accepted' then raise;end if;end;
 if other_lid is not null then begin perform public.acquire_offseason_player_authenticated(jsonb_build_object('league_id',other_lid,'league_team_id',(select id from public.league_teams where league_id=other_lid limit 1),'player_id',pid5,'season',(select season from public.league_seasons where league_id=other_lid and is_active),'salary',1,'years',1,'acquisition_type','fa_auction','idempotency_key','cross-league'));raise exception 'cross-league commissioner mutation accepted';exception when others then if sqlerrm='cross-league commissioner mutation accepted' then raise;end if;end;end if;
 if has_function_privilege('authenticated','public.acquire_offseason_player_private(jsonb,uuid)','execute') or has_function_privilege('anon','public.acquire_offseason_player_authenticated(jsonb)','execute') or has_function_privilege('anon','public.release_offseason_player_authenticated(jsonb)','execute') or has_function_privilege('anon','public.persist_rookie_draft_board_authenticated(jsonb)','execute') then raise exception 'RPC privilege boundary invalid';end if;
 if not exists(select 1 from pg_indexes where schemaname='public' and indexname='contract_agreements_one_live_player_uidx' and indexdef ilike 'create unique index%') then raise exception 'database duplicate-live-ownership boundary missing';end if;
end$$;
rollback;
