QUESTIONS = [
    "how does my team look?",
    "what are my biggest weaknesses?",
    "what are my biggest strengths?",
    "am I a contender?",
    "should I rebuild or contend?",
    "who are my core players?",
    "who should I move on from?",
    "who should I cut?",
    "who should I trade first?",
    "who should I not trade?",

    "what contracts are best value?",
    "what contracts are hurting me the most?",
    "who is overpaid?",
    "who is underpaid?",
    "who has the worst contract?",
    "who has the best contract?",
    "how bad is Garrett Wilson's contract?",
    "should I trade Isiah Pacheco?",
    "should I move Cortland Sutton?",
    "is Josh Allen worth his salary?",

    "how can I use my QB depth to upgrade RB?",
    "which QB should I trade?",
    "should I trade Jared Goff?",
    "should I trade Bryce Young?",
    "should I keep Josh Allen?",
    "do I have too many QBs?",
    "what RB should I target?",
    "what TE should I target?",
    "what WR should I target?",
    "who are good buy-low targets?",

    "what positions should I upgrade?",
    "what is my biggest roster hole?",
    "how do I fix RB?",
    "how do I fix TE?",
    "do I need another WR?",
    "is my QB room strong enough?",
    "is my bench useful?",
    "who are my roster cloggers?",
    "who are my depth pieces?",
    "who are my best starters?",

    "should I consolidate?",
    "should I trade picks?",
    "should I trade for veterans?",
    "should I sell veterans?",
    "should I make an all-in move?",
    "what kind of trade should I make?",
    "build me a trade package for RB help",
    "build me a trade package using a QB",
    "what should I ask for Garrett Wilson?",
    "what should I ask for Bryce Young?",

    "who is my most valuable player?",
    "who is my least valuable player?",
    "who has the best production?",
    "who has the worst production?",
    "who is producing above contract?",
    "who is producing below contract?",
    "who is risky because of low production confidence?",
    "who has fallback production data?",
    "which players have unreliable data?",
    "which players need more source work?",

    "how does my RB room look?",
    "how does my WR room look?",
    "how does my TE room look?",
    "how does my QB room look?",
    "rank my RBs",
    "rank my WRs",
    "rank my QBs",
    "rank my TEs",
    "who should start at flex?",
    "who should be on my taxi squad?",

    "what free agents should I target?",
    "which FAs fit my team?",
    "who should I churn at the bottom of roster?",
    "what waiver profile should I look for?",
    "should I add another RB?",
    "should I add another TE?",
    "which bench player is most droppable?",
    "which cheap contract should I protect?",
    "who is a sneaky hold?",
    "who is a sell high?",

    "what rookie should I draft?",
    "which rookie QB is best value?",
    "should I draft Fernando Mendoza?",
    "should I draft Chandler Morris?",
    "rank the rookie board",
    "who are the best rookie values?",
    "should I trade my rookie pick?",
    "what positions should I draft?",
    "should I draft for need or value?",
    "who is my best rookie fit?",

    "give me a 3 step plan",
    "what should I do this week?",
    "what is the next move I should make?",
    "what is my offseason plan?",
    "what is my trade deadline plan?",
    "what is my contention window?",
    "what is my biggest blind spot?",
    "what question should I be asking?",
    "give me a GM summary",
    "be honest, what would you do with this roster?",
]
