begin;
alter table public.rollover_execution_handler_registry drop constraint rollover_execution_handler_registry_mutation_class_check;
alter table public.rollover_execution_handler_registry add constraint rollover_execution_handler_registry_mutation_class_check check(mutation_class in('read_only','contract_domain','roster_domain','taxi_domain','taxi_eligibility_domain'));
insert into public.rollover_execution_handler_registry(operation_code,operation_order,handler_version,input_schema_version,result_schema_version,execution_owner,mutation_class,metadata)
values('ENFORCE_TAXI_ELIGIBILITY_NONRETURN',17,1,'phase3b8c-taxi-eligibility-input-v1','phase3b8c-taxi-eligibility-result-v1','execution','taxi_eligibility_domain',jsonb_build_object('phase','3B.8C','activation','publication','roster_mutation',false));

create table public.rollover_taxi_eligibility_authorities(
 id uuid primary key default gen_random_uuid(),rollover_execution_id uuid not null references public.rollover_executions(id),league_id uuid not null references public.leagues(id),
 player_id text not null references public.player_universe(sleeper_id),target_league_season_id uuid not null references public.league_seasons(id),
 target_assignment_set_id uuid not null references public.rollover_target_roster_assignment_sets(id),taxi_unlock_set_id uuid not null references public.rollover_taxi_unlock_sets(id),
 source_snapshot_id uuid not null references public.rollover_execution_input_snapshots(id),source_snapshot_hash text not null check(source_snapshot_hash~'^[0-9a-f]{64}$'),
 assignment_set_hash text not null check(assignment_set_hash~'^[0-9a-f]{64}$'),rookie_class_year integer,draft_year integer,draft_round integer,
 eligibility_state text not null check(eligibility_state in('permanently_consumed','future_rookie_eligible','never_eligible','excluded_release','excluded_commissioner_hold')),
 eligibility_consumed boolean not null,permanent_nonreturn boolean not null,authority_version integer not null check(authority_version=1),
 prior_consumed_authority_id uuid references public.rollover_taxi_eligibility_authorities(id),canonical_league_team_id uuid references public.league_teams(id),
 deterministic_hash text not null check(deterministic_hash~'^[0-9a-f]{64}$'),provenance jsonb not null check(jsonb_typeof(provenance)='object'),
 created_by uuid not null,created_at timestamptz not null default clock_timestamp(),unique(rollover_execution_id,player_id),
 check(eligibility_consumed=permanent_nonreturn),check((eligibility_state='permanently_consumed')=permanent_nonreturn));
create index rollover_taxi_eligibility_permanent_idx on public.rollover_taxi_eligibility_authorities(league_id,player_id,created_at) where permanent_nonreturn;
create or replace function public.reject_phase3b8c_taxi_authority_mutation() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$begin raise exception 'Phase 3B.8C taxi eligibility authority is immutable';end$$;
create trigger rollover_taxi_eligibility_authorities_immutable before update or delete on public.rollover_taxi_eligibility_authorities for each row execute function public.reject_phase3b8c_taxi_authority_mutation();
alter table public.rollover_taxi_eligibility_authorities enable row level security;revoke all on public.rollover_taxi_eligibility_authorities from public,anon,authenticated;grant select,insert on public.rollover_taxi_eligibility_authorities to service_role;
create policy phase3b8c_taxi_authority_read on public.rollover_taxi_eligibility_authorities for select to authenticated using(exists(select 1 from public.league_memberships m where m.league_id=rollover_taxi_eligibility_authorities.league_id and m.user_id=auth.uid() and m.role='commissioner'));

create or replace function public.guard_contract_write_during_rollover() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$declare lid uuid:=coalesce(new.league_id,old.league_id);begin if coalesce(current_setting('app.rollover_typed_execution',true),'') not in('phase3b7c-v1','phase3b8a-v1','phase3b8b-v1','phase3b8c-v1') then perform public.assert_no_active_rollover_cutover_lock(lid);end if;return case when tg_op='DELETE' then old else new end;end$$;
create or replace function public.guard_season_roster_assignment_insert_phase3b8a() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$declare season_row public.league_seasons%rowtype;team_row public.league_teams%rowtype;begin select * into season_row from public.league_seasons where id=new.league_season_id;select * into team_row from public.league_teams where id=new.league_team_id;if season_row.id is null or team_row.id is null or season_row.league_id<>team_row.league_id then raise exception 'target_roster_team_cross_league';end if;if public.has_active_rollover_cutover_lock(season_row.league_id) and coalesce(current_setting('app.rollover_typed_execution',true),'') not in('phase3b8a-v1','phase3b8b-v1','phase3b8c-v1') then raise exception 'rollover_cutover_roster_writes_blocked';end if;return new;end$$;

create or replace function public.write_taxi_eligibility_authority_phase3b8c_private(p_rollover_execution_id uuid,p_execution_plan_id uuid,p_approval_id uuid,p_actor uuid)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare x public.rollover_executions%rowtype;s public.rollover_execution_input_snapshots%rowtype;aset public.rollover_target_roster_assignment_sets%rowtype;uset public.rollover_taxi_unlock_sets%rowtype;
 r record;player public.player_universe%rowtype;assignment public.season_roster_assignments%rowtype;release public.rollover_contract_releases%rowtype;hold public.rollover_commissioner_holds%rowtype;unlock public.rollover_taxi_unlock_dispositions%rowtype;prior public.rollover_taxi_eligibility_authorities%rowtype;
 state text;consumed boolean;team_id uuid;fp text;material jsonb:='[]';aggregate_fp text;candidate int:=0;consumed_count int:=0;future_count int:=0;never_count int:=0;released_count int:=0;hold_count int:=0;written int:=0;replay_count int:=0;
begin
 if p_actor is null then perform public.raise_phase3b6c1_failure('taxi_eligibility_actor_missing','{}');end if;select * into x from public.rollover_executions where id=p_rollover_execution_id;
 if x.id is null then perform public.raise_phase3b6c1_failure('taxi_eligibility_execution_missing','{}');end if;
 if not exists(select 1 from public.rollover_execution_locks where rollover_execution_id=x.id and execution_plan_id=p_execution_plan_id and approval_id=p_approval_id and status='active' and lock_type='cutover' and lock_scope='rollover_global' for update) then perform public.raise_phase3b6c1_failure('taxi_eligibility_cutover_lock_missing','{}');end if;
 select * into s from public.rollover_execution_input_snapshots where rollover_execution_id=x.id and execution_plan_id=p_execution_plan_id and approval_id=p_approval_id for share;
 select * into aset from public.rollover_target_roster_assignment_sets where rollover_execution_id=x.id for share;select * into uset from public.rollover_taxi_unlock_sets where rollover_execution_id=x.id for share;
 if s.id is null or aset.id is null or uset.id is null or aset.source_snapshot_id<>s.id or uset.source_snapshot_id<>s.id or uset.target_assignment_set_id<>aset.id or uset.source_snapshot_hash<>s.aggregate_snapshot_fingerprint then perform public.raise_phase3b6c1_failure('taxi_eligibility_authority_input_missing','{}');end if;
 for r in select player_id from(select sleeper_player_id player_id from public.season_roster_assignments where assignment_set_id=aset.id union select player_id from public.rollover_contract_releases where rollover_execution_id=x.id union select player_id from public.rollover_commissioner_holds where rollover_execution_id=x.id union select player_id from public.rollover_taxi_eligibility_authorities where league_id=x.league_id and permanent_nonreturn) q order by player_id loop
  candidate:=candidate+1;select * into player from public.player_universe where sleeper_id=r.player_id;if player.sleeper_id is null then perform public.raise_phase3b6c1_failure('taxi_eligibility_player_missing','{}');end if;
  select * into assignment from public.season_roster_assignments where assignment_set_id=aset.id and sleeper_player_id=r.player_id;select * into release from public.rollover_contract_releases where rollover_execution_id=x.id and player_id=r.player_id;select * into hold from public.rollover_commissioner_holds where rollover_execution_id=x.id and player_id=r.player_id and hold_status='active';select * into unlock from public.rollover_taxi_unlock_dispositions where rollover_execution_id=x.id and player_id=r.player_id;
  select * into prior from public.rollover_taxi_eligibility_authorities where league_id=x.league_id and player_id=r.player_id and permanent_nonreturn and rollover_execution_id<>x.id order by created_at desc,id desc limit 1;
  if exists(select 1 from public.season_roster_assignments src where src.league_season_id=uset.source_league_season_id and src.sleeper_player_id=r.player_id and src.roster_designation='taxi') and unlock.id is null then perform public.raise_phase3b6c1_failure('taxi_eligibility_unlock_evidence_missing','{}');end if;
  if assignment.id is not null then
   if not exists(select 1 from public.contract_agreements a where a.id=assignment.contract_agreement_id and a.league_id=x.league_id and a.league_team_id=assignment.league_team_id and a.player_id=r.player_id and a.status='active') then perform public.raise_phase3b6c1_failure('taxi_eligibility_owner_mismatch','{}');end if;
   if not exists(select 1 from public.league_teams t where t.id=assignment.league_team_id and t.league_id=x.league_id) then perform public.raise_phase3b6c1_failure('taxi_eligibility_cross_league','{}');end if;team_id:=assignment.league_team_id;
  else team_id:=null;end if;
  if prior.id is not null or (unlock.id is not null and unlock.disposition='unlocked_to_active_pool') then
   if player.rookie_class_year is null or player.draft_year is null or player.draft_round is null then perform public.raise_phase3b6c1_failure('taxi_eligibility_rookie_evidence_missing','{}');end if;state:='permanently_consumed';consumed:=true;consumed_count:=consumed_count+1;
  elsif hold.id is not null then state:='excluded_commissioner_hold';consumed:=false;hold_count:=hold_count+1;
  elsif release.id is not null then state:='excluded_release';consumed:=false;released_count:=released_count+1;
  elsif assignment.id is not null and player.rookie_class_year=x.target_season and player.draft_year=x.target_season and player.draft_round between 1 and 20 then state:='future_rookie_eligible';consumed:=false;future_count:=future_count+1;
  elsif assignment.id is not null then
   if (player.rookie_class_year is null)<>(player.draft_year is null) or (player.draft_year is null)<>(player.draft_round is null) then perform public.raise_phase3b6c1_failure('taxi_eligibility_rookie_evidence_conflict','{}');end if;state:='never_eligible';consumed:=false;never_count:=never_count+1;
  else perform public.raise_phase3b6c1_failure('taxi_eligibility_target_assignment_missing','{}');end if;
  fp:=public.rollover_material_fingerprint(jsonb_build_object('schema','phase3b8c-taxi-authority-v1','execution',x.id,'player',r.player_id,'rookie_class',player.rookie_class_year,'draft_year',player.draft_year,'draft_round',player.draft_round,'state',state,'consumed',consumed,'team',team_id,'snapshot_hash',s.aggregate_snapshot_fingerprint,'assignment_set_hash',aset.aggregate_assignment_set_hash,'unlock_set_hash',uset.aggregate_unlock_hash,'prior_consumed_authority',prior.id));
  material:=material||jsonb_build_array(jsonb_build_object('player_id',r.player_id,'hash',fp));
  if exists(select 1 from public.rollover_taxi_eligibility_authorities where rollover_execution_id=x.id and player_id=r.player_id and deterministic_hash<>fp) then perform public.raise_phase3b6c1_failure('taxi_eligibility_replay_conflict','{}');end if;
  insert into public.rollover_taxi_eligibility_authorities(rollover_execution_id,league_id,player_id,target_league_season_id,target_assignment_set_id,taxi_unlock_set_id,source_snapshot_id,source_snapshot_hash,assignment_set_hash,rookie_class_year,draft_year,draft_round,eligibility_state,eligibility_consumed,permanent_nonreturn,authority_version,prior_consumed_authority_id,canonical_league_team_id,deterministic_hash,provenance,created_by)
  values(x.id,x.league_id,r.player_id,aset.target_league_season_id,aset.id,uset.id,s.id,s.aggregate_snapshot_fingerprint,aset.aggregate_assignment_set_hash,player.rookie_class_year,player.draft_year,player.draft_round,state,consumed,consumed,1,prior.id,team_id,fp,jsonb_build_object('activation_status','pending_publication','sleeper_authoritative',false,'roster_mutated',false,'contract_mutated',false),p_actor)
  on conflict(rollover_execution_id,player_id) do nothing;if found then written:=written+1;else replay_count:=replay_count+1;end if;
 end loop;
 aggregate_fp:=public.rollover_material_fingerprint(jsonb_build_object('schema','phase3b8c-taxi-authority-set-v1','execution',x.id,'rows',material));
 return jsonb_build_object('candidate_count',candidate,'consumed_eligibility_count',consumed_count,'future_eligible_count',future_count,'never_eligible_count',never_count,'released_exclusion_count',released_count,'hold_exclusion_count',hold_count,'conflict_count',0,'authority_rows_written',written,'compatible_replay_count',replay_count,'deterministic_hash',aggregate_fp,'mutation_count',written,'validation_codes',jsonb_build_array('snapshot_hash','assignment_set_hash','unlock_evidence','rookie_evidence','canonical_ownership','permanent_nonreturn','cutover_lock'));
end$$;

create or replace function public.execute_rollover_typed_handler_phase3b8c_private(p_operation jsonb,p_rollover_execution_id uuid,p_execution_plan_id uuid,p_approval_id uuid,p_actor uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$declare code text:=p_operation->>'operation_type';result jsonb;begin if code<>'ENFORCE_TAXI_ELIGIBILITY_NONRETURN' then return public.execute_rollover_typed_handler_phase3b8b_private(p_operation,p_rollover_execution_id,p_execution_plan_id,p_approval_id,p_actor);end if;if (p_operation->>'operation_index')::int<>17 or not exists(select 1 from public.rollover_execution_handler_registry where operation_code=code and operation_order=17 and handler_version=1) then perform public.raise_phase3b6c1_failure('unsupported_handler_version','{}');end if;result:=public.write_taxi_eligibility_authority_phase3b8c_private(p_rollover_execution_id,p_execution_plan_id,p_approval_id,p_actor);return jsonb_build_object('operation_code',code,'handler_version',1,'result',result||jsonb_build_object('operation_mutation_count',coalesce((result->>'mutation_count')::int,0),'deterministic_result_hash',result->>'deterministic_hash'));end$$;

-- Dispatcher extension follows the certified outer-run/inner-savepoint model.
do $$declare d text;begin
 select pg_get_functiondef('public.execute_rollover_plan_phase3b8b_private(jsonb,uuid)'::regprocedure) into d;
 d:=replace(d,'execute_rollover_plan_phase3b8b_private','execute_rollover_plan_phase3b8c_private');
 d:=replace(d,'execute_rollover_typed_handler_phase3b8b_private','execute_rollover_typed_handler_phase3b8c_private');
 d:=replace(d,'''UNLOCK_TAXI_ASSIGNMENTS'')','''UNLOCK_TAXI_ASSIGNMENTS'',''ENFORCE_TAXI_ELIGIBILITY_NONRETURN'')');
 d:=replace(d,'Phase 3B.8B','Phase 3B.8C');d:=replace(d,'phase3b8b-v1','phase3b8c-v1');
 if d not like '%ENFORCE_TAXI_ELIGIBILITY_NONRETURN%' or d not like '%execute_rollover_typed_handler_phase3b8c_private%' then raise exception 'Phase 3B.8C dispatcher derivation failed';end if;
 execute d;
end$$;
create or replace function public.execute_rollover_plan_authenticated(p_request jsonb) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$declare actor uuid:=public.require_authenticated_user();x public.rollover_executions%rowtype;begin if p_request?'actor_user_id' or p_request?'executed_by' then raise exception 'actor spoofing forbidden';end if;select * into x from public.rollover_executions where id=(p_request->>'rollover_execution_id')::uuid;if x.id is null then raise exception 'execution not found';end if;perform public.require_commissioner_authority(x.league_id);return public.execute_rollover_plan_phase3b8c_private(p_request,actor);end$$;
revoke all on function public.write_taxi_eligibility_authority_phase3b8c_private(uuid,uuid,uuid,uuid),public.execute_rollover_typed_handler_phase3b8c_private(jsonb,uuid,uuid,uuid,uuid),public.execute_rollover_plan_phase3b8c_private(jsonb,uuid),public.reject_phase3b8c_taxi_authority_mutation() from public,anon,authenticated,service_role;
revoke all on function public.guard_contract_write_during_rollover(),public.guard_season_roster_assignment_insert_phase3b8a() from public,anon,authenticated,service_role;
revoke all on function public.execute_rollover_plan_authenticated(jsonb) from public,anon,authenticated,service_role;grant execute on function public.execute_rollover_plan_authenticated(jsonb) to authenticated;
commit;
