begin;
alter table public.rollover_execution_handler_registry drop constraint rollover_execution_handler_registry_mutation_class_check;
alter table public.rollover_execution_handler_registry add constraint rollover_execution_handler_registry_mutation_class_check check(mutation_class in('read_only','contract_domain','roster_domain','taxi_domain','taxi_eligibility_domain','ir_domain'));
insert into public.rollover_execution_handler_registry(operation_code,operation_order,handler_version,input_schema_version,result_schema_version,execution_owner,mutation_class,metadata) values('RECONCILE_IR_ASSIGNMENTS',18,1,'phase3b8d-ir-input-v1','phase3b8d-ir-result-v1','execution','ir_domain',jsonb_build_object('phase','3B.8D','medical_eligibility_validated',false,'publication',false));
create table public.rollover_ir_reconciliations(
 id uuid primary key default gen_random_uuid(),rollover_execution_id uuid not null references public.rollover_executions(id),operation_code text not null check(operation_code='RECONCILE_IR_ASSIGNMENTS'),league_id uuid not null references public.leagues(id),
 closing_season_id uuid not null references public.league_seasons(id),target_season_id uuid not null references public.league_seasons(id),player_id text not null references public.player_universe(sleeper_id),canonical_league_team_id uuid not null references public.league_teams(id),
 source_assignment_id uuid not null references public.season_roster_assignments(id),target_assignment_id uuid references public.season_roster_assignments(id),
 prior_ir_status text not null check(prior_ir_status='ir'),resulting_ir_status text not null check(resulting_ir_status in('administrative_carry_forward_unvalidated','cleared','excluded_release','excluded_commissioner_hold')),
 taxi_conflict boolean not null,release_exclusion boolean not null,commissioner_hold_exclusion boolean not null,
 source_evidence_hash text not null check(source_evidence_hash~'^[0-9a-f]{64}$'),target_assignment_set_hash text not null check(target_assignment_set_hash~'^[0-9a-f]{64}$'),
 reconciliation_schema_version text not null check(reconciliation_schema_version='phase3b8d-ir-v1'),provenance jsonb not null check(jsonb_typeof(provenance)='object'),effective_at timestamptz not null default clock_timestamp(),deterministic_fingerprint text not null check(deterministic_fingerprint~'^[0-9a-f]{64}$'),
 unique(rollover_execution_id,operation_code,player_id),unique(rollover_execution_id,source_assignment_id),
 check((resulting_ir_status='administrative_carry_forward_unvalidated' and target_assignment_id is not null and not release_exclusion and not commissioner_hold_exclusion and not taxi_conflict) or(resulting_ir_status='excluded_release' and target_assignment_id is null and release_exclusion and not commissioner_hold_exclusion) or(resulting_ir_status='excluded_commissioner_hold' and target_assignment_id is null and release_exclusion and commissioner_hold_exclusion) or resulting_ir_status='cleared'));
create or replace function public.reject_phase3b8d_ir_mutation() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$begin raise exception 'Phase 3B.8D IR reconciliation evidence is immutable';end$$;
create trigger rollover_ir_reconciliations_immutable before update or delete on public.rollover_ir_reconciliations for each row execute function public.reject_phase3b8d_ir_mutation();
alter table public.rollover_ir_reconciliations enable row level security;revoke all on public.rollover_ir_reconciliations from public,anon,authenticated;grant select,insert on public.rollover_ir_reconciliations to service_role;
create policy phase3b8d_ir_read on public.rollover_ir_reconciliations for select to authenticated using(exists(select 1 from public.league_memberships m where m.league_id=rollover_ir_reconciliations.league_id and m.user_id=auth.uid() and m.role='commissioner'));
create or replace function public.guard_contract_write_during_rollover() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$declare lid uuid:=coalesce(new.league_id,old.league_id);begin if coalesce(current_setting('app.rollover_typed_execution',true),'') not in('phase3b7c-v1','phase3b8a-v1','phase3b8b-v1','phase3b8c-v1','phase3b8d-v1') then perform public.assert_no_active_rollover_cutover_lock(lid);end if;return case when tg_op='DELETE' then old else new end;end$$;
create or replace function public.guard_season_roster_assignment_insert_phase3b8a() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$declare season_row public.league_seasons%rowtype;team_row public.league_teams%rowtype;begin select * into season_row from public.league_seasons where id=new.league_season_id;select * into team_row from public.league_teams where id=new.league_team_id;if season_row.id is null or team_row.id is null or season_row.league_id<>team_row.league_id then raise exception 'target_roster_team_cross_league';end if;if public.has_active_rollover_cutover_lock(season_row.league_id) and coalesce(current_setting('app.rollover_typed_execution',true),'') not in('phase3b8a-v1','phase3b8b-v1','phase3b8c-v1','phase3b8d-v1') then raise exception 'rollover_cutover_roster_writes_blocked';end if;return new;end$$;

create or replace function public.write_ir_reconciliation_phase3b8d_private(p_rollover_execution_id uuid,p_execution_plan_id uuid,p_approval_id uuid,p_actor uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare x public.rollover_executions%rowtype;s public.rollover_execution_input_snapshots%rowtype;aset public.rollover_target_roster_assignment_sets%rowtype;capture public.historical_capture_executions%rowtype;r public.season_roster_assignments%rowtype;target public.season_roster_assignments%rowtype;rel public.rollover_contract_releases%rowtype;hold public.rollover_commissioner_holds%rowtype;fp text;source_fp text;result_fp text;material jsonb:='[]';source_count int:=0;carry int:=0;cleared int:=0;released int:=0;held int:=0;written int:=0;replays int:=0;status text;
begin
 select * into x from public.rollover_executions where id=p_rollover_execution_id;if x.id is null then perform public.raise_phase3b6c1_failure('ir_source_assignment_missing','{}');end if;
 if not exists(select 1 from public.rollover_execution_locks l where l.rollover_execution_id=x.id and l.execution_plan_id=p_execution_plan_id and l.approval_id=p_approval_id and l.status='active' and l.lock_type='cutover' and l.lock_scope='rollover_global' for update) then perform public.raise_phase3b6c1_failure('ir_cutover_lock_missing','{}');end if;
 select * into s from public.rollover_execution_input_snapshots where rollover_execution_id=x.id and execution_plan_id=p_execution_plan_id and approval_id=p_approval_id for share;select * into aset from public.rollover_target_roster_assignment_sets where rollover_execution_id=x.id for share;select * into capture from public.historical_capture_executions where id=s.historical_capture_execution_id for share;
 if s.id is null or aset.id is null or aset.status<>'complete_unpublished' or aset.source_snapshot_id<>s.id or aset.source_snapshot_hash<>s.aggregate_snapshot_fingerprint then perform public.raise_phase3b6c1_failure('ir_target_set_hash_mismatch','{}');end if;
 if coalesce((capture.row_counts->>'roster_assignments')::int,-1)<>(select count(*) from public.season_roster_assignments where league_season_id=capture.league_season_id) then perform public.raise_phase3b6c1_failure('ir_source_changed_after_freeze','{}');end if;
 perform 1 from public.season_roster_assignments where league_season_id=capture.league_season_id and roster_designation='ir' order by sleeper_player_id,id for share;perform 1 from public.season_roster_assignments where assignment_set_id=aset.id order by sleeper_player_id,league_team_id,id for share;perform 1 from public.rollover_taxi_unlock_dispositions where rollover_execution_id=x.id order by player_id,id for share;perform 1 from public.rollover_taxi_eligibility_authorities where rollover_execution_id=x.id order by player_id,id for share;perform 1 from public.rollover_contract_releases where rollover_execution_id=x.id order by player_id,id for share;perform 1 from public.rollover_commissioner_holds where rollover_execution_id=x.id order by player_id,id for share;perform 1 from public.rollover_ir_reconciliations where rollover_execution_id=x.id order by player_id,id for update;
 if exists(select 1 from public.season_roster_assignments where league_season_id=capture.league_season_id and roster_designation='ir' group by sleeper_player_id having count(*)<>1) then perform public.raise_phase3b6c1_failure('ir_source_assignment_duplicate','{}');end if;
 if exists(select 1 from public.season_roster_assignments where assignment_set_id=aset.id group by sleeper_player_id having count(*)<>1) then perform public.raise_phase3b6c1_failure('ir_target_assignment_duplicate','{}');end if;
 for r in select * from public.season_roster_assignments where league_season_id=capture.league_season_id and roster_designation='ir' order by sleeper_player_id,id loop
  source_count:=source_count+1;if not exists(select 1 from public.league_teams t where t.id=r.league_team_id and t.league_id=x.league_id) then perform public.raise_phase3b6c1_failure('ir_source_cross_league','{}');end if;
  if exists(select 1 from public.rollover_taxi_unlock_dispositions d where d.rollover_execution_id=x.id and d.player_id=r.sleeper_player_id) then perform public.raise_phase3b6c1_failure('ir_taxi_state_conflict','{}');end if;
  select * into target from public.season_roster_assignments where assignment_set_id=aset.id and sleeper_player_id=r.sleeper_player_id;select * into rel from public.rollover_contract_releases where rollover_execution_id=x.id and player_id=r.sleeper_player_id;select * into hold from public.rollover_commissioner_holds where rollover_execution_id=x.id and player_id=r.sleeper_player_id and hold_status='active';
  if rel.id is not null and target.id is not null then perform public.raise_phase3b6c1_failure('ir_release_conflict','{}');end if;if hold.id is not null and target.id is not null then perform public.raise_phase3b6c1_failure('ir_commissioner_hold_conflict','{}');end if;
  if target.id is not null and (target.league_season_id<>aset.target_league_season_id or not exists(select 1 from public.league_teams t where t.id=target.league_team_id and t.league_id=x.league_id)) then perform public.raise_phase3b6c1_failure('ir_owner_mismatch','{}');end if;if target.id is not null and target.roster_status<>'pending_unpublished' then perform public.raise_phase3b6c1_failure('ir_owner_mismatch','{}');end if;
  if hold.id is not null then status:='excluded_commissioner_hold';held:=held+1;elsif rel.id is not null then status:='excluded_release';released:=released+1;elsif target.id is null then perform public.raise_phase3b6c1_failure('ir_target_assignment_missing','{}');elsif target.league_team_id<>r.league_team_id then perform public.raise_phase3b6c1_failure('ir_target_team_mismatch','{}');else status:='administrative_carry_forward_unvalidated';carry:=carry+1;end if;
  source_fp:=public.rollover_material_fingerprint(to_jsonb(r)-'created_at'-'captured_at'-'finalized_at');fp:=public.rollover_material_fingerprint(jsonb_build_object('schema','phase3b8d-ir-v1','execution',x.id,'player',r.sleeper_player_id,'team',r.league_team_id,'source',r.id,'source_hash',source_fp,'target',target.id,'target_set_hash',aset.aggregate_assignment_set_hash,'status',status,'taxi_conflict',false,'release',rel.id,'hold',hold.id));material:=material||jsonb_build_array(jsonb_build_object('player',r.sleeper_player_id,'hash',fp));
  if exists(select 1 from public.rollover_ir_reconciliations where rollover_execution_id=x.id and player_id=r.sleeper_player_id and deterministic_fingerprint<>fp) then perform public.raise_phase3b6c1_failure('ir_reconciliation_conflict','{}');end if;
  insert into public.rollover_ir_reconciliations(rollover_execution_id,operation_code,league_id,closing_season_id,target_season_id,player_id,canonical_league_team_id,source_assignment_id,target_assignment_id,prior_ir_status,resulting_ir_status,taxi_conflict,release_exclusion,commissioner_hold_exclusion,source_evidence_hash,target_assignment_set_hash,reconciliation_schema_version,provenance,deterministic_fingerprint)
  values(x.id,'RECONCILE_IR_ASSIGNMENTS',x.league_id,capture.league_season_id,aset.target_league_season_id,r.sleeper_player_id,r.league_team_id,r.id,target.id,'ir',status,false,rel.id is not null,hold.id is not null,source_fp,aset.aggregate_assignment_set_hash,'phase3b8d-ir-v1',jsonb_build_object('medical_eligibility_validated',false,'administrative_only',true,'published',false,'sleeper_authoritative',false),fp) on conflict(rollover_execution_id,operation_code,player_id) do nothing;if found then written:=written+1;else replays:=replays+1;end if;
 end loop;
 if source_count<>carry+cleared+released+held then perform public.raise_phase3b6c1_failure('ir_population_incomplete','{}');end if;result_fp:=public.rollover_material_fingerprint(jsonb_build_object('schema','phase3b8d-ir-result-v1','execution',x.id,'rows',material));
 return jsonb_build_object('source_ir_count',source_count,'valid_carry_forward_count',carry,'cleared_ir_count',cleared,'released_exclusion_count',released,'commissioner_hold_exclusion_count',held,'taxi_conflict_count',0,'missing_target_assignment_count',0,'ownership_conflict_count',0,'ir_evidence_rows_written',written,'compatible_replay_count',replays,'mutation_count',written,'postcondition_count',8,'validation_codes',jsonb_build_array('source_capture','target_assignment_set','canonical_owner','taxi_separation','release_hold_exclusions','cutover_lock','administrative_unvalidated'),'deterministic_result_hash',result_fp);
end$$;
create or replace function public.execute_rollover_typed_handler_phase3b8d_private(p_operation jsonb,p_rollover_execution_id uuid,p_execution_plan_id uuid,p_approval_id uuid,p_actor uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$declare code text:=p_operation->>'operation_type';result jsonb;begin if code<>'RECONCILE_IR_ASSIGNMENTS' then return public.execute_rollover_typed_handler_phase3b8c_private(p_operation,p_rollover_execution_id,p_execution_plan_id,p_approval_id,p_actor);end if;if (p_operation->>'operation_index')::int<>18 then perform public.raise_phase3b6c1_failure('unsupported_handler_version','{}');end if;result:=public.write_ir_reconciliation_phase3b8d_private(p_rollover_execution_id,p_execution_plan_id,p_approval_id,p_actor);return jsonb_build_object('operation_code',code,'handler_version',1,'result',result||jsonb_build_object('operation_mutation_count',coalesce((result->>'mutation_count')::int,0)));end$$;
do $$declare d text;begin select pg_get_functiondef('public.execute_rollover_plan_phase3b8c_private(jsonb,uuid)'::regprocedure) into d;d:=replace(d,'execute_rollover_plan_phase3b8c_private','execute_rollover_plan_phase3b8d_private');d:=replace(d,'execute_rollover_typed_handler_phase3b8c_private','execute_rollover_typed_handler_phase3b8d_private');d:=replace(d,'''ENFORCE_TAXI_ELIGIBILITY_NONRETURN'')','''ENFORCE_TAXI_ELIGIBILITY_NONRETURN'',''RECONCILE_IR_ASSIGNMENTS'')');d:=replace(d,'Phase 3B.8C','Phase 3B.8D');d:=replace(d,'phase3b8c-v1','phase3b8d-v1');if d not like '%RECONCILE_IR_ASSIGNMENTS%' then raise exception 'dispatcher derivation';end if;execute d;end$$;
create or replace function public.execute_rollover_plan_authenticated(p_request jsonb) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$declare actor uuid:=public.require_authenticated_user();x public.rollover_executions%rowtype;begin if p_request?'actor_user_id' or p_request?'executed_by' then raise exception 'actor spoofing forbidden';end if;select * into x from public.rollover_executions where id=(p_request->>'rollover_execution_id')::uuid;if x.id is null then raise exception 'execution not found';end if;perform public.require_commissioner_authority(x.league_id);return public.execute_rollover_plan_phase3b8d_private(p_request,actor);end$$;
revoke all on function public.write_ir_reconciliation_phase3b8d_private(uuid,uuid,uuid,uuid),public.execute_rollover_typed_handler_phase3b8d_private(jsonb,uuid,uuid,uuid,uuid),public.execute_rollover_plan_phase3b8d_private(jsonb,uuid),public.reject_phase3b8d_ir_mutation() from public,anon,authenticated,service_role;revoke all on function public.execute_rollover_plan_authenticated(jsonb) from public,anon,authenticated,service_role;grant execute on function public.execute_rollover_plan_authenticated(jsonb) to authenticated;
commit;
