begin;

insert into public.rollover_execution_handler_registry(operation_code,operation_order,handler_version,input_schema_version,result_schema_version,execution_owner,mutation_class,metadata)
values('ACTIVATE_TARGET_CAP_AUTHORITY',33,1,'phase3b13b-cap-publication-input-v1','phase3b13b-cap-publication-result-v1','publication','team_cap_domain',jsonb_build_object('phase','3B.13B','recalculation',false,'cap_repair',false,'free_agent_visibility',false,'cutover_lock_release',false,'cache_refresh',false,'external_sync',false));

alter table public.prepared_team_cap_sets drop constraint prepared_team_cap_sets_status_check;
alter table public.prepared_team_cap_sets add column published_at timestamptz;
alter table public.prepared_team_cap_sets add constraint prepared_team_cap_sets_status_check check(status in('prepared_unpublished','published'));
alter table public.prepared_team_cap_sets add constraint prepared_team_cap_sets_publication_state_check check((status='prepared_unpublished' and published_at is null) or(status='published' and published_at is not null));

create or replace function public.guard_phase3b10b_caps() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$declare lid uuid:=coalesce(new.league_id,old.league_id);begin
 if tg_op='UPDATE' and tg_table_name='prepared_team_cap_sets' then
  if coalesce(current_setting('app.rollover_publication',true),'')='phase3b13b-v1' and old.status='prepared_unpublished' and new.status='published' and old.published_at is null and new.published_at is not null and(to_jsonb(new)-'status'-'published_at')=(to_jsonb(old)-'status'-'published_at') then return new;end if;
 end if;
 if tg_op in('UPDATE','DELETE') then raise exception 'prepared_team_cap_immutable';end if;
 if public.has_active_rollover_cutover_lock(lid) and coalesce(current_setting('app.rollover_typed_execution',true),'') not in('phase3b7c-v1','phase3b8a-v1','phase3b8b-v1','phase3b8c-v1','phase3b8d-v1','phase3b9a-v1','phase3b9b-v1','phase3b9c-v1','phase3b10a-v1','phase3b10b-v1') then raise exception 'rollover_cutover_cap_writes_blocked';end if;return new;
end$$;

create table public.rollover_target_cap_authority_publications(
 id uuid primary key default gen_random_uuid(),rollover_execution_id uuid not null unique references public.rollover_executions(id),league_id uuid not null references public.leagues(id),target_season_id uuid not null references public.league_seasons(id),season_publication_id uuid not null unique references public.rollover_target_season_authority_publications(id),finalization_id uuid not null references public.rollover_executed_unpublished_finalizations(id),validation_report_id uuid not null references public.rollover_post_execution_validation_reports(id),approval_id uuid not null references public.rollover_execution_plan_approvals(id),execution_plan_id uuid not null references public.rollover_execution_plans(id),cutover_lock_id uuid not null references public.rollover_execution_locks(id),prepared_cap_set_id uuid not null unique references public.prepared_team_cap_sets(id),operation_index integer not null check(operation_index=33),operation_code text not null check(operation_code='ACTIVATE_TARGET_CAP_AUTHORITY'),idempotency_key text not null unique check(length(btrim(idempotency_key))>0),request_fingerprint text not null check(request_fingerprint~'^[0-9a-f]{64}$'),season_publication_fingerprint text not null check(season_publication_fingerprint~'^[0-9a-f]{64}$'),operation23_cap_hash text not null check(operation23_cap_hash~'^[0-9a-f]{64}$'),published_cap_value_hash text not null check(published_cap_value_hash~'^[0-9a-f]{64}$'),team_count integer not null check(team_count>0),cap_limit numeric(12,2) not null check(cap_limit>0),publication_fingerprint text not null check(publication_fingerprint~'^[0-9a-f]{64}$'),published_by uuid not null references auth.users(id),published_at timestamptz not null default clock_timestamp(),schema_version text not null check(schema_version='phase3b13b-cap-authority-publication-v1')
);
alter table public.rollover_target_cap_authority_publications enable row level security;
revoke all on public.rollover_target_cap_authority_publications from public,anon,authenticated;
grant select,insert on public.rollover_target_cap_authority_publications to service_role;
create policy target_cap_authority_publication_commissioner_read on public.rollover_target_cap_authority_publications for select to authenticated using(exists(select 1 from public.league_memberships m where m.league_id=rollover_target_cap_authority_publications.league_id and m.user_id=auth.uid() and m.role='commissioner'));
create or replace function public.guard_phase3b13b_cap_publication_evidence() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$begin if tg_op in('UPDATE','DELETE') then raise exception 'target_cap_authority_publication_immutable';end if;return new;end$$;
create trigger target_cap_authority_publication_immutable before update or delete on public.rollover_target_cap_authority_publications for each row execute function public.guard_phase3b13b_cap_publication_evidence();

create or replace function public.activate_target_cap_authority_phase3b13b_private(p_request jsonb,p_actor uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare x public.rollover_executions%rowtype;sp public.rollover_target_season_authority_publications%rowtype;f public.rollover_executed_unpublished_finalizations%rowtype;r public.rollover_post_execution_validation_reports%rowtype;a public.rollover_execution_plan_approvals%rowtype;p public.rollover_execution_plans%rowtype;l public.rollover_execution_locks%rowtype;t public.league_seasons%rowtype;cs public.prepared_team_cap_sets%rowtype;prior public.rollover_target_cap_authority_publications%rowtype;publishedrow public.rollover_target_cap_authority_publications%rowtype;k text:=nullif(btrim(p_request->>'idempotency_key'),'');reqfp text;recomputed text;valuehash text;pubfp text;published_at_value timestamptz:=clock_timestamp();material jsonb;prepared_count int;row_count int;
begin
 if p_actor is null or k is null then raise exception 'authenticated actor and idempotency key required';end if;
 if nullif(p_request->>'rollover_execution_id','') is null or nullif(p_request->>'season_publication_id','') is null or nullif(p_request->>'expected_season_publication_fingerprint','') is null or nullif(p_request->>'expected_cap_set_id','') is null or nullif(p_request->>'expected_cap_set_hash','') is null or nullif(p_request->>'approval_id','') is null or nullif(p_request->>'execution_plan_id','') is null or nullif(p_request->>'expected_plan_fingerprint','') is null then raise exception 'complete cap publication assertions required';end if;
 perform pg_advisory_xact_lock(hashtextextended('phase3b13b:'||(p_request->>'rollover_execution_id'),0));
 select * into x from public.rollover_executions where id=(p_request->>'rollover_execution_id')::uuid for update;if x.id is null or x.status<>'executed_unpublished' then raise exception 'stale cap publication execution';end if;perform public.require_commissioner_authority(x.league_id);
 material:=jsonb_build_object('operation','ACTIVATE_TARGET_CAP_AUTHORITY','execution',x.id,'league',x.league_id,'request',p_request-'idempotency_key','actor',p_actor);reqfp:=public.rollover_material_fingerprint(material);
 select * into prior from public.rollover_target_cap_authority_publications where rollover_execution_id=x.id for share;if found then if prior.idempotency_key<>k or prior.request_fingerprint<>reqfp or prior.operation23_cap_hash<>p_request->>'expected_cap_set_hash' or prior.season_publication_fingerprint<>p_request->>'expected_season_publication_fingerprint' then raise exception 'publication replay mismatch';end if;return jsonb_build_object('success',true,'idempotent',true,'publication_id',prior.id,'operation_index',33,'operation_code','ACTIVATE_TARGET_CAP_AUTHORITY','cap_status','published','cap_recalculated',false,'cutover_lock_active',true,'free_agent_visibility_enabled',false,'cache_refreshed',false,'external_sync_performed',false);end if;
 select * into sp from public.rollover_target_season_authority_publications where id=(p_request->>'season_publication_id')::uuid and rollover_execution_id=x.id for share;if sp.id is null or sp.publication_fingerprint<>p_request->>'expected_season_publication_fingerprint' then raise exception 'operation 32 publication evidence mismatch';end if;
 select * into f from public.rollover_executed_unpublished_finalizations where id=sp.finalization_id and rollover_execution_id=x.id for share;select * into r from public.rollover_post_execution_validation_reports where id=f.validation_report_id and rollover_execution_id=x.id for share;if f.id is null or r.id is null or not f.publication_eligible or f.publication_blocker_count<>0 or not r.publication_eligible or r.publication_blocker_count<>0 or r.execution_failure_count<>0 or f.validation_report_hash<>r.aggregate_validation_hash then raise exception 'publication eligibility or finalization invalid';end if;
 select * into p from public.rollover_execution_plans where id=(p_request->>'execution_plan_id')::uuid and id=sp.execution_plan_id and rollover_execution_id=x.id for share;select * into a from public.rollover_execution_plan_approvals where id=(p_request->>'approval_id')::uuid and id=sp.approval_id and execution_plan_id=p.id and rollover_execution_id=x.id for share;if p.id is null or a.id is null or p.plan_status<>'approved_for_execution' or not p.approved_for_execution or a.approval_status<>'approved' or p.plan_fingerprint<>p_request->>'expected_plan_fingerprint' or p.plan_fingerprint<>a.plan_fingerprint or p.plan_fingerprint<>x.execution_plan_fingerprint then raise exception 'stale cap publication plan or approval';end if;
 select * into l from public.rollover_execution_locks where id=sp.cutover_lock_id and rollover_execution_id=x.id and status='active' and lock_type='cutover' and lock_scope='rollover_global' for update;if l.id is null then raise exception 'active matching cutover lock required';end if;
 select * into t from public.league_seasons where id=sp.target_season_id and league_id=x.league_id and season=x.target_season for share;if t.id is null or not t.is_active or t.status<>'active' then raise exception 'inactive published season';end if;
 select count(*) into prepared_count from public.prepared_team_cap_sets where league_id=x.league_id and target_season_id=t.id and status='prepared_unpublished';if prepared_count=0 then raise exception 'prepared cap authority missing';elsif prepared_count>1 then raise exception 'multiple prepared cap authorities';end if;
 select * into cs from public.prepared_team_cap_sets where id=(p_request->>'expected_cap_set_id')::uuid and rollover_execution_id=x.id and league_id=x.league_id and target_season_id=t.id and status='prepared_unpublished' for update;if cs.id is null then raise exception 'prepared cap authority mismatch';end if;
 select count(*) into row_count from public.prepared_team_caps where cap_set_id=cs.id;recomputed:=public.rollover_material_fingerprint(coalesce((select jsonb_agg(jsonb_build_object('team',league_team_id,'hash',deterministic_row_fingerprint) order by league_team_id) from public.prepared_team_caps where cap_set_id=cs.id),'[]'));if row_count<>cs.canonical_team_count or recomputed<>cs.aggregate_cap_set_hash or cs.aggregate_cap_set_hash<>p_request->>'expected_cap_set_hash' or cs.aggregate_cap_set_hash<>(select prepared_cap_hash from public.season_cache_invalidation_manifests where rollover_execution_id=x.id) then raise exception 'authority hash mismatch';end if;
 if exists(select 1 from public.prepared_team_caps where cap_set_id=cs.id and publication_blocked) then raise exception 'prepared cap authority publication blocked';end if;
 if exists(select 1 from public.rollover_execution_operation_results where rollover_execution_id=x.id and operation_index>=33) or exists(select 1 from public.rollover_target_cap_authority_publications where league_id=x.league_id and target_season_id=t.id) then raise exception 'incompatible operation 33-36 publication exists';end if;
 valuehash:=public.rollover_material_fingerprint((select jsonb_agg(to_jsonb(c)-'created_at'-'published_at' order by c.league_team_id) from public.prepared_team_caps c where c.cap_set_id=cs.id));pubfp:=public.rollover_material_fingerprint(jsonb_build_object('schema','phase3b13b-cap-authority-publication-v1','execution',x.id,'season_publication',sp.publication_fingerprint,'finalization',f.deterministic_finalization_fingerprint,'validation',r.aggregate_validation_hash,'cap_set',cs.id,'operation23_hash',cs.aggregate_cap_set_hash,'values',valuehash,'teams',row_count,'cap_limit',cs.cap_limit,'lock',l.id));
 perform set_config('app.rollover_publication','phase3b13b-v1',true);update public.prepared_team_cap_sets set status='published',published_at=published_at_value where id=cs.id;
 insert into public.rollover_target_cap_authority_publications(rollover_execution_id,league_id,target_season_id,season_publication_id,finalization_id,validation_report_id,approval_id,execution_plan_id,cutover_lock_id,prepared_cap_set_id,operation_index,operation_code,idempotency_key,request_fingerprint,season_publication_fingerprint,operation23_cap_hash,published_cap_value_hash,team_count,cap_limit,publication_fingerprint,published_by,published_at,schema_version) values(x.id,x.league_id,t.id,sp.id,f.id,r.id,a.id,p.id,l.id,cs.id,33,'ACTIVATE_TARGET_CAP_AUTHORITY',k,reqfp,sp.publication_fingerprint,cs.aggregate_cap_set_hash,valuehash,row_count,cs.cap_limit,pubfp,p_actor,published_at_value,'phase3b13b-cap-authority-publication-v1') returning * into publishedrow;
 return jsonb_build_object('success',true,'idempotent',false,'publication_id',publishedrow.id,'operation_index',33,'operation_code','ACTIVATE_TARGET_CAP_AUTHORITY','cap_status','published','operation23_cap_hash',cs.aggregate_cap_set_hash,'published_cap_value_hash',valuehash,'team_count',row_count,'cap_recalculated',false,'cutover_lock_active',true,'free_agent_visibility_enabled',false,'cache_refreshed',false,'external_sync_performed',false);
end$$;

create or replace function public.activate_target_cap_authority_authenticated(p_request jsonb) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$declare actor uuid:=public.require_authenticated_user();begin if p_request?'actor_user_id' or p_request?'published_by' or p_request?'cap_values' or p_request?'cap_limit' or p_request?'team_caps' or p_request?'recalculate' or p_request?'repair' or p_request?'free_agent_visibility' or p_request?'release_cutover' or p_request?'cache_refresh' or p_request?'external_sync' then raise exception 'actor or cap publication material spoofing forbidden';end if;return public.activate_target_cap_authority_phase3b13b_private(p_request,actor);end$$;

revoke all on function public.guard_phase3b13b_cap_publication_evidence(),public.activate_target_cap_authority_phase3b13b_private(jsonb,uuid),public.activate_target_cap_authority_authenticated(jsonb) from public,anon,authenticated,service_role;
grant execute on function public.activate_target_cap_authority_authenticated(jsonb) to authenticated;

commit;
