begin;
alter table public.rollover_execution_handler_registry drop constraint rollover_execution_handler_registry_mutation_class_check;
alter table public.rollover_execution_handler_registry add constraint rollover_execution_handler_registry_mutation_class_check check(mutation_class in('read_only','contract_domain','roster_domain','taxi_domain','taxi_eligibility_domain','ir_domain','draft_inventory_domain','rookie_authority_domain','rookie_eligibility_domain','dead_cap_domain','team_cap_domain','free_agent_domain','expiring_contract_domain','standings_domain','matchup_domain','playoff_domain','cache_domain'));
insert into public.rollover_execution_handler_registry(operation_code,operation_order,handler_version,input_schema_version,result_schema_version,execution_owner,mutation_class,metadata) values('INVALIDATE_SEASON_DERIVED_CACHES',29,1,'phase3b12a-cache-input-v1','phase3b12a-cache-result-v1','execution','cache_domain',jsonb_build_object('phase','3B.12A','registry_version','phase3b12a-cache-registry-v1','publication',false,'external_calls',false));
do $$declare d text;sig regprocedure;begin foreach sig in array array['public.guard_contract_write_during_rollover()'::regprocedure,'public.guard_season_roster_assignment_insert_phase3b8a()'::regprocedure,'public.guard_phase3b9a_draft_inventory()'::regprocedure,'public.guard_phase3b9b_rookie_authority()'::regprocedure,'public.guard_phase3b9c_rookie_eligibility()'::regprocedure] loop select pg_get_functiondef(sig) into d;d:=replace(d,'''phase3b11c-v1'')','''phase3b11c-v1'',''phase3b12a-v1'')');execute d;end loop;end$$;

create table public.season_derived_cache_registry(cache_code text primary key,repository_owner text not null,cache_type text not null,season_scope text not null,source_authority text not null,invalidation_owner text not null,rebuild_owner text not null,lifecycle_owner text not null check(lifecycle_owner in('execution','publication','external','ephemeral')),required_action text not null check(required_action in('invalidate_now','rebuild_before_publication','rebuild_during_publication','external_sync_required','ephemeral_no_action','unaffected','blocking_unresolved')),blocking boolean not null,deterministic_key_version text not null,validation_method text not null,implementation_status text not null,registry_version text not null check(registry_version='phase3b12a-cache-registry-v1'),entry_fingerprint text not null check(entry_fingerprint~'^[0-9a-f]{64}$'));
with r(code,owner,typ,scope,authority,inv,rebuild,life,action,blocking,keyv,validation,status) as(values
('ai_context','gm_assistant/data.py; pages/05_GM_Assistant.py','AI context cache','league_target_season','published authority and GM loaders','publication','publication','publication','rebuild_during_publication',false,'league:season:publication_epoch:v1','loader/session audit','pending_publication'),
('app_context_process','services/app_context.py','Streamlit process cache','league_active_season','versioned app-context loaders','publication','publication','publication','rebuild_during_publication',false,'league:season:publication_epoch:v1','decorator/clear audit','pending_publication'),
('app_session_context','services/app_context.py; home.py','session-state cache','league_active_season','active league and published authority','publication','publication','publication','rebuild_during_publication',false,'session:league:publication_epoch:v1','session-key audit','pending_publication'),
('competition_session','pages/01_Season_Standings.py; pages/02_Weekly_Matchups.py','session-state cache','league_active_season','published competition authority','publication','publication','publication','rebuild_during_publication',false,'session:league:season:competition:v1','session-key audit','pending_publication'),
('generated_snapshot','snapshot/build_snapshot.py; snapshot/builders/**','generated snapshot','league_season','versioned builders and published authority','publication','publication','publication','rebuild_during_publication',false,'league:season:snapshot_schema:v1','builder inventory','pending_publication'),
('gm_loader_process','gm_assistant/data.py','Streamlit process cache','league_active_season','versioned GM loaders','publication','publication','publication','rebuild_during_publication',false,'league:season:publication_epoch:v1','decorator inventory','pending_publication'),
('gm_session_context','pages/05_GM_Assistant.py; gm_assistant/data.py','session-state cache','league_active_season','published authority and conversation context','publication','publication','publication','rebuild_during_publication',false,'session:league:season:conversation:v1','conversation audit','pending_publication'),
('materialized_views_absent','supabase/migrations/**','materialized view','repository','version-controlled migration inventory','execution','publication','execution','unaffected',false,'migration-inventory:v1','repository and pg absence','verified_absent'),
('page_loader_process','pages/*.py; Admin Commissioner/*.py','Streamlit process cache','league_active_season','versioned page loaders','publication','publication','publication','rebuild_during_publication',false,'league:season:publication_epoch:v1','decorator inventory','pending_publication'),
('persisted_contract_analytics','snapshot/builders/contract/**; snapshot/builders/player/**','persisted database derivative','league_season','prepared cap/contract evidence and builders','publication','publication','publication','rebuild_before_publication',false,'league:season:contract-analytics:v1','table/builder inventory','pending_publication'),
('persisted_matchup_ratings','matchup_ratings; snapshot/builders/**','persisted database derivative','league_season_week','synchronized matchups and builders','publication','publication','publication','rebuild_before_publication',false,'league:season:week:ratings:v1','table/consumer audit','pending_publication'),
('request_local_resolvers','services/**; season_engine/**','request-local','request','versioned resolver code','request_boundary','request_boundary','ephemeral','ephemeral_no_action',false,'request:v1','undecorated resolver audit','naturally_ephemeral'),
('sleeper_external_sync','services/sleeper_sync.py; services/sync_sleeper_teams.py; scripts/sync_roster_state.py','external synchronization cache','sleeper_league_season','Sleeper API and controlled sync jobs','external_sync','external_sync','external','external_sync_required',false,'sleeper_league:season:sync:v1','adapter/job inventory','pending_external_sync'))
insert into public.season_derived_cache_registry select code,owner,typ,scope,authority,inv,rebuild,life,action,blocking,keyv,validation,status,'phase3b12a-cache-registry-v1',public.rollover_material_fingerprint(jsonb_build_object('code',code,'owner',owner,'type',typ,'scope',scope,'authority',authority,'invalidation_owner',inv,'rebuild_owner',rebuild,'lifecycle_owner',life,'action',action,'blocking',blocking,'key_version',keyv,'validation',validation,'status',status)) from r;
alter table public.season_derived_cache_registry enable row level security;revoke all on public.season_derived_cache_registry from public,anon,authenticated;grant select on public.season_derived_cache_registry to service_role;

create table public.season_cache_invalidation_manifests(id uuid primary key default gen_random_uuid(),rollover_execution_id uuid not null unique references public.rollover_executions(id),league_id uuid not null references public.leagues(id),target_season_id uuid not null references public.league_seasons(id),snapshot_hash text not null,prepared_cap_hash text not null,prepared_free_agent_hash text not null,prepared_expiring_hash text not null,prepared_standings_hash text not null,prepared_matchup_hash text not null,prepared_playoff_hash text not null,registry_version text not null,registry_hash text not null,expected_entry_count int not null check(expected_entry_count>0),aggregate_manifest_hash text not null,status text not null check(status='prepared'),published_at timestamptz,completed_at timestamptz,schema_version text not null check(schema_version='phase3b12a-cache-manifest-v1'),created_at timestamptz not null default clock_timestamp(),unique(league_id,target_season_id),check(published_at is null and completed_at is null));
create table public.season_cache_invalidation_entries(id uuid primary key default gen_random_uuid(),manifest_id uuid not null references public.season_cache_invalidation_manifests(id),cache_code text not null,cache_type text not null,season_scope text not null,source_authority text not null,current_state text not null,required_action text not null check(required_action in('invalidate_now','rebuild_before_publication','rebuild_during_publication','external_sync_required','ephemeral_no_action','unaffected','blocking_unresolved')),action_owner text not null,lifecycle_owner text not null check(lifecycle_owner in('execution','publication','external','ephemeral')),blocking boolean not null,completion_status text not null check(completion_status in('completed','pending','not_required')),invalidated_at timestamptz,rebuilt_at timestamptz,source_evidence_hash text not null,entry_fingerprint text not null,created_at timestamptz not null default clock_timestamp(),unique(manifest_id,cache_code),check((required_action='invalidate_now' and completion_status='completed' and invalidated_at is not null) or(required_action<>'invalidate_now' and invalidated_at is null)),check(rebuilt_at is null));
do $$declare t text;begin foreach t in array array['season_cache_invalidation_manifests','season_cache_invalidation_entries'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from public,anon,authenticated',t);execute format('grant select,insert on public.%I to service_role',t);end loop;end$$;
create policy cache_manifest_commissioner_read on public.season_cache_invalidation_manifests for select to authenticated using(exists(select 1 from public.league_memberships m where m.league_id=season_cache_invalidation_manifests.league_id and m.user_id=auth.uid() and m.role='commissioner'));
create policy cache_entry_commissioner_read on public.season_cache_invalidation_entries for select to authenticated using(exists(select 1 from public.season_cache_invalidation_manifests h join public.league_memberships m on m.league_id=h.league_id where h.id=season_cache_invalidation_entries.manifest_id and m.user_id=auth.uid() and m.role='commissioner'));
create or replace function public.guard_phase3b12a_cache_evidence() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$begin if tg_op in('UPDATE','DELETE') then raise exception 'cache_manifest_evidence_immutable';end if;return new;end$$;
create trigger cache_manifest_immutable before update or delete on public.season_cache_invalidation_manifests for each row execute function public.guard_phase3b12a_cache_evidence();create trigger cache_entry_immutable before update or delete on public.season_cache_invalidation_entries for each row execute function public.guard_phase3b12a_cache_evidence();

create or replace function public.write_cache_manifest_phase3b12a_private(p_rollover_execution_id uuid,p_execution_plan_id uuid,p_approval_id uuid,p_actor uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare x public.rollover_executions%rowtype;target public.league_seasons%rowtype;snap public.rollover_execution_input_snapshots%rowtype;cap public.prepared_team_cap_sets%rowtype;fa public.prepared_free_agent_eligibility_sets%rowtype;exp public.prepared_expiring_contract_sets%rowtype;st public.prepared_target_standings_sets%rowtype;ma public.prepared_target_matchup_sets%rowtype;pl public.prepared_target_playoff_structures%rowtype;h public.season_cache_invalidation_manifests%rowtype;r public.season_derived_cache_registry%rowtype;registryhash text;sourcehash text;aggregatehash text;entryhash text;n int;written int:=0;
begin
 if p_actor is null then perform public.raise_phase3b6c1_failure('cache_authenticated_actor_required','{}');end if;select * into x from public.rollover_executions where id=p_rollover_execution_id;select * into target from public.league_seasons where league_id=x.league_id and season=x.target_season for share;if target.id is null or target.is_active or target.status<>'scheduled' then perform public.raise_phase3b6c1_failure('cache_source_hash_mismatch','{}');end if;
 if not exists(select 1 from public.rollover_execution_locks l where l.rollover_execution_id=x.id and l.execution_plan_id=p_execution_plan_id and l.approval_id=p_approval_id and l.status='active' and l.lock_type='cutover' for update) then perform public.raise_phase3b6c1_failure('cache_cutover_lock_missing','{}');end if;
 select * into snap from public.rollover_execution_input_snapshots where rollover_execution_id=x.id for share;select * into cap from public.prepared_team_cap_sets where rollover_execution_id=x.id for share;select * into fa from public.prepared_free_agent_eligibility_sets where rollover_execution_id=x.id for share;select * into exp from public.prepared_expiring_contract_sets where rollover_execution_id=x.id for share;select * into st from public.prepared_target_standings_sets where rollover_execution_id=x.id for share;select * into ma from public.prepared_target_matchup_sets where rollover_execution_id=x.id for share;select * into pl from public.prepared_target_playoff_structures where rollover_execution_id=x.id for share;
 if snap.id is null or cap.id is null or fa.id is null or exp.id is null or st.id is null or ma.id is null or pl.id is null or cap.frozen_snapshot_hash<>snap.aggregate_snapshot_fingerprint or fa.source_snapshot_hash<>snap.aggregate_snapshot_fingerprint or exp.source_snapshot_hash<>snap.aggregate_snapshot_fingerprint or st.source_snapshot_hash<>snap.aggregate_snapshot_fingerprint or ma.source_snapshot_hash<>snap.aggregate_snapshot_fingerprint or pl.source_snapshot_hash<>snap.aggregate_snapshot_fingerprint then perform public.raise_phase3b6c1_failure('cache_source_hash_mismatch','{}');end if;
 select count(*),public.rollover_material_fingerprint(coalesce(jsonb_agg(jsonb_build_object('code',cache_code,'fingerprint',entry_fingerprint) order by cache_code),'[]'::jsonb)) into n,registryhash from public.season_derived_cache_registry where registry_version='phase3b12a-cache-registry-v1';if n<>13 then perform public.raise_phase3b6c1_failure('cache_registry_incomplete','{}');end if;if exists(select 1 from public.season_derived_cache_registry where blocking or required_action='blocking_unresolved') then perform public.raise_phase3b6c1_failure('cache_blocking_unresolved','{}');end if;
 sourcehash:=public.rollover_material_fingerprint(jsonb_build_object('snapshot',snap.aggregate_snapshot_fingerprint,'cap',cap.aggregate_cap_set_hash,'free_agent',fa.aggregate_set_hash,'expiring',exp.aggregate_set_hash,'standings',st.aggregate_standings_hash,'matchup',ma.aggregate_matchup_hash,'playoff',pl.aggregate_structure_hash));aggregatehash:=public.rollover_material_fingerprint(jsonb_build_object('schema','phase3b12a-cache-manifest-v1','execution',x.id,'league',x.league_id,'target',target.id,'registry_hash',registryhash,'source_hash',sourcehash,'codes',(select jsonb_agg(cache_code order by cache_code) from public.season_derived_cache_registry)));
 select * into h from public.season_cache_invalidation_manifests where league_id=x.league_id and target_season_id=target.id for update;if found then if h.rollover_execution_id<>x.id or h.registry_hash<>registryhash or h.aggregate_manifest_hash<>aggregatehash or(select count(*) from public.season_cache_invalidation_entries where manifest_id=h.id)<>n then perform public.raise_phase3b6c1_failure('cache_manifest_conflict','{}');end if;return jsonb_build_object('registry_entry_count',n,'manifest_entry_count',n,'invalidate_now_count',0,'invalidations_completed_count',0,'rebuild_before_publication_count',2,'rebuild_during_publication_count',8,'external_sync_required_count',1,'ephemeral_no_action_count',1,'unaffected_count',1,'blocking_unresolved_count',0,'compatible_replay_count',1,'mutation_count',0,'postcondition_count',13,'aggregate_manifest_hash',aggregatehash,'validation_codes',jsonb_build_array('registry_complete','owners_explicit','source_hashes','publication_pending','external_pending','no_blockers','unpublished','cutover_lock'));end if;
 insert into public.season_cache_invalidation_manifests(rollover_execution_id,league_id,target_season_id,snapshot_hash,prepared_cap_hash,prepared_free_agent_hash,prepared_expiring_hash,prepared_standings_hash,prepared_matchup_hash,prepared_playoff_hash,registry_version,registry_hash,expected_entry_count,aggregate_manifest_hash,status,schema_version) values(x.id,x.league_id,target.id,snap.aggregate_snapshot_fingerprint,cap.aggregate_cap_set_hash,fa.aggregate_set_hash,exp.aggregate_set_hash,st.aggregate_standings_hash,ma.aggregate_matchup_hash,pl.aggregate_structure_hash,'phase3b12a-cache-registry-v1',registryhash,n,aggregatehash,'prepared','phase3b12a-cache-manifest-v1') returning * into h;
 for r in select * from public.season_derived_cache_registry order by cache_code loop entryhash:=public.rollover_material_fingerprint(jsonb_build_object('manifest',aggregatehash,'cache',r.cache_code,'registry_entry',r.entry_fingerprint,'source',sourcehash,'action',r.required_action,'owner',r.lifecycle_owner));insert into public.season_cache_invalidation_entries(manifest_id,cache_code,cache_type,season_scope,source_authority,current_state,required_action,action_owner,lifecycle_owner,blocking,completion_status,invalidated_at,source_evidence_hash,entry_fingerprint) values(h.id,r.cache_code,r.cache_type,r.season_scope,r.source_authority,case when r.required_action in('ephemeral_no_action','unaffected') then 'verified' else 'prepared_stale' end,r.required_action,r.rebuild_owner,r.lifecycle_owner,r.blocking,case when r.required_action in('ephemeral_no_action','unaffected') then 'not_required' else 'pending' end,null,sourcehash,entryhash);written:=written+1;end loop;
 return jsonb_build_object('registry_entry_count',n,'manifest_entry_count',written,'invalidate_now_count',0,'invalidations_completed_count',0,'rebuild_before_publication_count',2,'rebuild_during_publication_count',8,'external_sync_required_count',1,'ephemeral_no_action_count',1,'unaffected_count',1,'blocking_unresolved_count',0,'compatible_replay_count',0,'mutation_count',written+1,'postcondition_count',13,'aggregate_manifest_hash',aggregatehash,'validation_codes',jsonb_build_array('registry_complete','owners_explicit','source_hashes','publication_pending','external_pending','no_blockers','unpublished','cutover_lock'));
end$$;
create or replace function public.execute_rollover_typed_handler_phase3b12a_private(p_operation jsonb,p_rollover_execution_id uuid,p_execution_plan_id uuid,p_approval_id uuid,p_actor uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$declare code text:=p_operation->>'operation_type';result jsonb;begin if code<>'INVALIDATE_SEASON_DERIVED_CACHES' then return public.execute_rollover_typed_handler_phase3b11c_private(p_operation,p_rollover_execution_id,p_execution_plan_id,p_approval_id,p_actor);end if;if(p_operation->>'operation_index')::int<>29 then perform public.raise_phase3b6c1_failure('unsupported_handler_version','{}');end if;result:=public.write_cache_manifest_phase3b12a_private(p_rollover_execution_id,p_execution_plan_id,p_approval_id,p_actor);return jsonb_build_object('operation_code',code,'handler_version',1,'result',result||jsonb_build_object('operation_mutation_count',(result->>'mutation_count')::int));end$$;
do $$declare d text;begin select pg_get_functiondef('public.execute_rollover_plan_phase3b11c_private(jsonb,uuid)'::regprocedure) into d;d:=replace(d,'execute_rollover_plan_phase3b11c_private','execute_rollover_plan_phase3b12a_private');d:=replace(d,'execute_rollover_typed_handler_phase3b11c_private','execute_rollover_typed_handler_phase3b12a_private');d:=replace(d,'''INITIALIZE_TARGET_PLAYOFF_STRUCTURE'')','''INITIALIZE_TARGET_PLAYOFF_STRUCTURE'',''INVALIDATE_SEASON_DERIVED_CACHES'')');d:=replace(d,'Phase 3B.11C','Phase 3B.12A');d:=replace(d,'phase3b11c-v1','phase3b12a-v1');execute d;end$$;
create or replace function public.execute_rollover_plan_authenticated(p_request jsonb) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$declare actor uuid:=public.require_authenticated_user();x public.rollover_executions%rowtype;begin if p_request?'actor_user_id' or p_request?'executed_by' or p_request?'cache_codes' or p_request?'caches' or p_request?'actions' or p_request?'owners' or p_request?'registry' then raise exception 'actor or cache material spoofing forbidden';end if;select * into x from public.rollover_executions where id=(p_request->>'rollover_execution_id')::uuid;if x.id is null then raise exception 'execution not found';end if;perform public.require_commissioner_authority(x.league_id);return public.execute_rollover_plan_phase3b12a_private(p_request,actor);end$$;
revoke all on function public.write_cache_manifest_phase3b12a_private(uuid,uuid,uuid,uuid),public.execute_rollover_typed_handler_phase3b12a_private(jsonb,uuid,uuid,uuid,uuid),public.execute_rollover_plan_phase3b12a_private(jsonb,uuid),public.guard_phase3b12a_cache_evidence() from public,anon,authenticated,service_role;revoke all on function public.execute_rollover_plan_authenticated(jsonb) from public,anon,authenticated,service_role;grant execute on function public.execute_rollover_plan_authenticated(jsonb) to authenticated;
commit;
