begin;
alter table public.rollover_execution_handler_registry drop constraint rollover_execution_handler_registry_mutation_class_check;
alter table public.rollover_execution_handler_registry add constraint rollover_execution_handler_registry_mutation_class_check check(mutation_class in('read_only','contract_domain','roster_domain','taxi_domain','taxi_eligibility_domain','ir_domain','draft_inventory_domain'));
insert into public.rollover_execution_handler_registry(operation_code,operation_order,handler_version,input_schema_version,result_schema_version,execution_owner,mutation_class,metadata)
values('ADVANCE_DRAFT_PICK_INVENTORY',19,1,'phase3b9a-draft-input-v1','phase3b9a-draft-result-v1','execution','draft_inventory_domain',jsonb_build_object('phase','3B.9A','visible_classes',4,'rounds',3,'publication',false));
create or replace function public.guard_contract_write_during_rollover() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$declare lid uuid:=coalesce(new.league_id,old.league_id);begin if coalesce(current_setting('app.rollover_typed_execution',true),'') not in('phase3b7c-v1','phase3b8a-v1','phase3b8b-v1','phase3b8c-v1','phase3b8d-v1','phase3b9a-v1') then perform public.assert_no_active_rollover_cutover_lock(lid);end if;return case when tg_op='DELETE' then old else new end;end$$;
create or replace function public.guard_season_roster_assignment_insert_phase3b8a() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$declare season_row public.league_seasons%rowtype;team_row public.league_teams%rowtype;begin select * into season_row from public.league_seasons where id=new.league_season_id;select * into team_row from public.league_teams where id=new.league_team_id;if season_row.id is null or team_row.id is null or season_row.league_id<>team_row.league_id then raise exception 'target_roster_team_cross_league';end if;if public.has_active_rollover_cutover_lock(season_row.league_id) and coalesce(current_setting('app.rollover_typed_execution',true),'') not in('phase3b8a-v1','phase3b8b-v1','phase3b8c-v1','phase3b8d-v1','phase3b9a-v1') then raise exception 'rollover_cutover_roster_writes_blocked';end if;return new;end$$;

create table public.draft_inventory_classes(
 id uuid primary key default gen_random_uuid(),league_id uuid not null references public.leagues(id),draft_year integer not null check(draft_year between 1900 and 9999),
 horizon_status text not null check(horizon_status='visible_prepared'),publication_status text not null check(publication_status='unpublished'),
 provenance jsonb not null check(jsonb_typeof(provenance)='object'),deterministic_class_hash text not null check(deterministic_class_hash~'^[0-9a-f]{64}$'),created_at timestamptz not null default clock_timestamp(),
 unique(league_id,draft_year));
create table public.draft_pick_assets(
 stable_pick_id uuid primary key,class_id uuid not null references public.draft_inventory_classes(id),league_id uuid not null references public.leagues(id),draft_year integer not null,
 round_number integer not null check(round_number between 1 and 3),original_league_team_id uuid not null references public.league_teams(id),current_owner_league_team_id uuid not null references public.league_teams(id),
 asset_status text not null check(asset_status='tradable'),publication_status text not null check(publication_status='unpublished'),trade_provenance jsonb not null default '[]' check(jsonb_typeof(trade_provenance)='array'),
 generation_provenance jsonb not null check(jsonb_typeof(generation_provenance)='object'),deterministic_asset_hash text not null check(deterministic_asset_hash~'^[0-9a-f]{64}$'),created_at timestamptz not null default clock_timestamp(),
 unique(league_id,draft_year,round_number,original_league_team_id),unique(class_id,round_number,original_league_team_id));
create index draft_pick_assets_owner_idx on public.draft_pick_assets(league_id,current_owner_league_team_id,draft_year,round_number);
create table public.rollover_draft_inventory_generations(
 id uuid primary key default gen_random_uuid(),rollover_execution_id uuid not null unique references public.rollover_executions(id),operation_code text not null check(operation_code='ADVANCE_DRAFT_PICK_INVENTORY'),
 league_id uuid not null references public.leagues(id),target_season_id uuid not null references public.league_seasons(id),existing_visible_class_count integer not null,target_visible_class_count integer not null check(target_visible_class_count=4),
 appended_class_count integer not null check(appended_class_count in(0,1)),appended_draft_year integer,canonical_team_count integer not null,rounds_per_class integer not null check(rounds_per_class=3),
 expected_new_pick_count integer not null,created_pick_count integer not null,preserved_traded_pick_count integer not null,source_snapshot_hash text not null check(source_snapshot_hash~'^[0-9a-f]{64}$'),
 deterministic_class_set_hash text not null check(deterministic_class_set_hash~'^[0-9a-f]{64}$'),deterministic_fingerprint text not null check(deterministic_fingerprint~'^[0-9a-f]{64}$'),
 generation_schema_version text not null check(generation_schema_version='phase3b9a-draft-v1'),provenance jsonb not null check(jsonb_typeof(provenance)='object'),created_at timestamptz not null default clock_timestamp(),
 check((appended_class_count=0 and appended_draft_year is null and expected_new_pick_count=0 and created_pick_count=0) or(appended_class_count=1 and appended_draft_year is not null and expected_new_pick_count=created_pick_count)));

alter table public.draft_inventory_classes enable row level security;alter table public.draft_pick_assets enable row level security;alter table public.rollover_draft_inventory_generations enable row level security;
revoke all on public.draft_inventory_classes,public.draft_pick_assets,public.rollover_draft_inventory_generations from public,anon,authenticated;
grant select,insert,update,delete on public.draft_inventory_classes,public.draft_pick_assets to service_role;grant select,insert on public.rollover_draft_inventory_generations to service_role;
create policy draft_inventory_commissioner_read on public.draft_inventory_classes for select to authenticated using(exists(select 1 from public.league_memberships m where m.league_id=draft_inventory_classes.league_id and m.user_id=auth.uid() and m.role='commissioner'));
create policy draft_assets_commissioner_read on public.draft_pick_assets for select to authenticated using(exists(select 1 from public.league_memberships m where m.league_id=draft_pick_assets.league_id and m.user_id=auth.uid() and m.role='commissioner'));
create policy draft_generation_commissioner_read on public.rollover_draft_inventory_generations for select to authenticated using(exists(select 1 from public.league_memberships m where m.league_id=rollover_draft_inventory_generations.league_id and m.user_id=auth.uid() and m.role='commissioner'));

create or replace function public.guard_phase3b9a_draft_inventory() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
declare lid uuid:=coalesce(new.league_id,old.league_id);begin
 if tg_table_name='draft_pick_assets' then
  if tg_op='UPDATE' and new.stable_pick_id<>old.stable_pick_id then raise exception 'draft_pick_hash_mismatch';end if;
  if tg_op='UPDATE' and (new.original_league_team_id<>old.original_league_team_id or new.draft_year<>old.draft_year or new.round_number<>old.round_number or new.class_id<>old.class_id) then raise exception 'draft_pick_original_owner_immutable';end if;
 elsif tg_table_name='draft_inventory_classes' then
  if tg_op='UPDATE' and (new.league_id<>old.league_id or new.draft_year<>old.draft_year) then raise exception 'draft_class_identity_immutable';end if;
 end if;
 if public.has_active_rollover_cutover_lock(lid) and coalesce(current_setting('app.rollover_typed_execution',true),'') not in('phase3b7c-v1','phase3b8a-v1','phase3b8b-v1','phase3b8c-v1','phase3b8d-v1','phase3b9a-v1') then raise exception 'rollover_cutover_draft_writes_blocked';end if;return case when tg_op='DELETE' then old else new end;
end$$;
create trigger draft_inventory_classes_guard before insert or update or delete on public.draft_inventory_classes for each row execute function public.guard_phase3b9a_draft_inventory();
create trigger draft_pick_assets_guard before insert or update or delete on public.draft_pick_assets for each row execute function public.guard_phase3b9a_draft_inventory();
create or replace function public.reject_phase3b9a_generation_mutation() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$begin raise exception 'Phase 3B.9A generation evidence is immutable';end$$;
create trigger rollover_draft_inventory_generations_immutable before update or delete on public.rollover_draft_inventory_generations for each row execute function public.reject_phase3b9a_generation_mutation();

create or replace function public.phase3b9a_stable_pick_id(p_league uuid,p_year integer,p_round integer,p_original_team uuid) returns uuid language sql immutable strict set search_path=pg_catalog,public as $$select (substr(md5(p_league::text||':'||p_year||':'||p_round||':'||p_original_team::text),1,8)||'-'||substr(md5(p_league::text||':'||p_year||':'||p_round||':'||p_original_team::text),9,4)||'-4'||substr(md5(p_league::text||':'||p_year||':'||p_round||':'||p_original_team::text),14,3)||'-a'||substr(md5(p_league::text||':'||p_year||':'||p_round||':'||p_original_team::text),18,3)||'-'||substr(md5(p_league::text||':'||p_year||':'||p_round||':'||p_original_team::text),21,12))::uuid$$;

create or replace function public.write_draft_inventory_phase3b9a_private(p_rollover_execution_id uuid,p_execution_plan_id uuid,p_approval_id uuid,p_actor uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare x public.rollover_executions%rowtype;s public.rollover_execution_input_snapshots%rowtype;target public.league_seasons%rowtype;c public.draft_inventory_classes%rowtype;t public.league_teams%rowtype;existing_count int;team_count int;incomplete_count int:=0;append_year int;append_count int:=0;expected_count int:=0;created_count int:=0;traded_count int:=0;class_hash text;fp text;replays int:=0;
begin
 select * into x from public.rollover_executions where id=p_rollover_execution_id;if x.id is null then perform public.raise_phase3b6c1_failure('draft_inventory_missing','{}');end if;
 if not exists(select 1 from public.rollover_execution_locks l where l.rollover_execution_id=x.id and l.execution_plan_id=p_execution_plan_id and l.approval_id=p_approval_id and l.status='active' and l.lock_type='cutover' and l.lock_scope='rollover_global' for update) then perform public.raise_phase3b6c1_failure('draft_cutover_lock_missing','{}');end if;
 select * into s from public.rollover_execution_input_snapshots where rollover_execution_id=x.id and execution_plan_id=p_execution_plan_id and approval_id=p_approval_id for share;
 select ls.* into target from public.league_seasons ls join public.rollover_execution_plans p on p.id=p_execution_plan_id and p.rollover_execution_id=x.id where ls.season=p.target_season and ls.league_id=x.league_id;
 if s.id is null or target.id is null or s.aggregate_snapshot_fingerprint is null then perform public.raise_phase3b6c1_failure('draft_pick_hash_mismatch','{}');end if;
 perform 1 from public.league_teams where league_id=x.league_id order by id for share;select count(*) into team_count from public.league_teams where league_id=x.league_id;if team_count=0 then perform public.raise_phase3b6c1_failure('draft_inventory_missing','{}');end if;
 if exists(select 1 from public.draft_picks where league_id=x.league_id) then perform public.raise_phase3b6c1_failure('draft_pick_original_owner_missing','{}');end if;
 perform 1 from public.draft_inventory_classes where league_id=x.league_id order by draft_year,id for share;perform 1 from public.draft_pick_assets where league_id=x.league_id order by draft_year,round_number,original_league_team_id,stable_pick_id for share;perform 1 from public.rollover_draft_inventory_generations where rollover_execution_id=x.id order by id for update;
 if exists(select 1 from public.draft_inventory_classes where league_id=x.league_id group by draft_year having count(*)>1) then perform public.raise_phase3b6c1_failure('draft_class_duplicate','{}');end if;
 if exists(select 1 from public.draft_pick_assets a where a.league_id=x.league_id and(a.round_number not between 1 and 3)) then perform public.raise_phase3b6c1_failure('draft_round_invalid','{}');end if;
 if exists(select 1 from public.draft_pick_assets a left join public.league_teams o on o.id=a.original_league_team_id and o.league_id=x.league_id left join public.league_teams n on n.id=a.current_owner_league_team_id and n.league_id=x.league_id where a.league_id=x.league_id and(o.id is null or n.id is null)) then perform public.raise_phase3b6c1_failure('draft_pick_cross_league','{}');end if;
 if exists(select 1 from public.draft_pick_assets where league_id=x.league_id group by draft_year,round_number,original_league_team_id having count(*)>1) then perform public.raise_phase3b6c1_failure('draft_pick_duplicate','{}');end if;
 select count(*) into existing_count from public.draft_inventory_classes where league_id=x.league_id and horizon_status='visible_prepared';if existing_count>4 then perform public.raise_phase3b6c1_failure('draft_horizon_invalid','{}');end if;if existing_count<3 then perform public.raise_phase3b6c1_failure('draft_horizon_requires_multiple_repairs','{}');end if;
 for c in select * from public.draft_inventory_classes where league_id=x.league_id and horizon_status='visible_prepared' order by draft_year loop
  if c.draft_year<target.season or c.draft_year>target.season+3 then perform public.raise_phase3b6c1_failure('far_future_class_conflict','{}');end if;
  if (select count(*) from public.draft_pick_assets where class_id=c.id)<>team_count*3 or exists(select 1 from generate_series(1,3) r cross join public.league_teams lt where lt.league_id=x.league_id and not exists(select 1 from public.draft_pick_assets a where a.class_id=c.id and a.round_number=r and a.original_league_team_id=lt.id)) then incomplete_count:=incomplete_count+1;end if;
 end loop;
 if incomplete_count>0 then perform public.raise_phase3b6c1_failure('draft_class_incomplete',jsonb_build_object('count',incomplete_count));end if;
 if existing_count=4 and exists(select y from generate_series(target.season,target.season+3)y except select draft_year from public.draft_inventory_classes where league_id=x.league_id and horizon_status='visible_prepared') then perform public.raise_phase3b6c1_failure('draft_horizon_invalid','{}');end if;
 if existing_count=3 then append_year:=target.season+3;if exists(select 1 from public.draft_inventory_classes where league_id=x.league_id and draft_year=append_year) then perform public.raise_phase3b6c1_failure('far_future_class_conflict','{}');end if;append_count:=1;expected_count:=team_count*3;
  class_hash:=public.rollover_material_fingerprint(jsonb_build_object('schema','phase3b9a-class-v1','league',x.league_id,'year',append_year,'teams',team_count,'rounds',3));
  insert into public.draft_inventory_classes(league_id,draft_year,horizon_status,publication_status,provenance,deterministic_class_hash) values(x.league_id,append_year,'visible_prepared','unpublished',jsonb_build_object('rollover_execution_id',x.id,'operation_code','ADVANCE_DRAFT_PICK_INVENTORY'),class_hash) returning * into c;
  for t in select * from public.league_teams where league_id=x.league_id order by id loop for i in 1..3 loop
   insert into public.draft_pick_assets(stable_pick_id,class_id,league_id,draft_year,round_number,original_league_team_id,current_owner_league_team_id,asset_status,publication_status,generation_provenance,deterministic_asset_hash)
   values(public.phase3b9a_stable_pick_id(x.league_id,append_year,i,t.id),c.id,x.league_id,append_year,i,t.id,t.id,'tradable','unpublished',jsonb_build_object('rollover_execution_id',x.id,'operation_code','ADVANCE_DRAFT_PICK_INVENTORY'),public.rollover_material_fingerprint(jsonb_build_object('league',x.league_id,'year',append_year,'round',i,'original_team',t.id))) ;created_count:=created_count+1;
  end loop;end loop;
 end if;
 select count(*) into traded_count from public.draft_pick_assets where league_id=x.league_id and current_owner_league_team_id<>original_league_team_id;
 class_hash:=public.rollover_material_fingerprint((select jsonb_agg(jsonb_build_object('year',draft_year,'hash',deterministic_class_hash) order by draft_year) from public.draft_inventory_classes where league_id=x.league_id and horizon_status='visible_prepared'));
 fp:=public.rollover_material_fingerprint(jsonb_build_object('schema','phase3b9a-draft-v1','execution',x.id,'snapshot',s.aggregate_snapshot_fingerprint,'classes',class_hash,'append_year',append_year,'created',created_count,'traded',traded_count));
 if exists(select 1 from public.rollover_draft_inventory_generations where rollover_execution_id=x.id and deterministic_fingerprint<>fp) then perform public.raise_phase3b6c1_failure('draft_pick_hash_mismatch','{}');end if;
 insert into public.rollover_draft_inventory_generations(rollover_execution_id,operation_code,league_id,target_season_id,existing_visible_class_count,target_visible_class_count,appended_class_count,appended_draft_year,canonical_team_count,rounds_per_class,expected_new_pick_count,created_pick_count,preserved_traded_pick_count,source_snapshot_hash,deterministic_class_set_hash,deterministic_fingerprint,generation_schema_version,provenance)
 values(x.id,'ADVANCE_DRAFT_PICK_INVENTORY',x.league_id,target.id,existing_count,4,append_count,append_year,team_count,3,expected_count,created_count,traded_count,s.aggregate_snapshot_fingerprint,class_hash,fp,'phase3b9a-draft-v1',jsonb_build_object('publication',false,'external_calls',false)) on conflict(rollover_execution_id) do nothing;if not found then replays:=1;end if;
 if (select count(*) from public.draft_inventory_classes where league_id=x.league_id and horizon_status='visible_prepared')<>4 then perform public.raise_phase3b6c1_failure('draft_population_incomplete','{}');end if;
 return jsonb_build_object('existing_visible_class_count',existing_count,'target_visible_class_count',4,'appended_class_count',append_count,'appended_draft_year',append_year,'canonical_team_count',team_count,'rounds_per_class',3,'expected_new_pick_count',expected_count,'created_pick_count',created_count,'preserved_traded_pick_count',traded_count,'duplicate_conflict_count',0,'incomplete_class_count',0,'compatible_replay_count',replays,'mutation_count',created_count+append_count+1,'deterministic_class_set_hash',class_hash,'validation_codes',jsonb_build_array('canonical_teams','four_class_horizon','three_rounds','stable_identity','ownership_preserved','unpublished','cutover_lock'),'postcondition_count',8);
end$$;

create or replace function public.execute_rollover_typed_handler_phase3b9a_private(p_operation jsonb,p_rollover_execution_id uuid,p_execution_plan_id uuid,p_approval_id uuid,p_actor uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$declare code text:=p_operation->>'operation_type';result jsonb;begin if code<>'ADVANCE_DRAFT_PICK_INVENTORY' then return public.execute_rollover_typed_handler_phase3b8d_private(p_operation,p_rollover_execution_id,p_execution_plan_id,p_approval_id,p_actor);end if;if(p_operation->>'operation_index')::int<>19 then perform public.raise_phase3b6c1_failure('unsupported_handler_version','{}');end if;result:=public.write_draft_inventory_phase3b9a_private(p_rollover_execution_id,p_execution_plan_id,p_approval_id,p_actor);return jsonb_build_object('operation_code',code,'handler_version',1,'result',result||jsonb_build_object('operation_mutation_count',coalesce((result->>'mutation_count')::int,0)));end$$;
do $$declare d text;begin select pg_get_functiondef('public.execute_rollover_plan_phase3b8d_private(jsonb,uuid)'::regprocedure) into d;d:=replace(d,'execute_rollover_plan_phase3b8d_private','execute_rollover_plan_phase3b9a_private');d:=replace(d,'execute_rollover_typed_handler_phase3b8d_private','execute_rollover_typed_handler_phase3b9a_private');d:=replace(d,'''RECONCILE_IR_ASSIGNMENTS'')','''RECONCILE_IR_ASSIGNMENTS'',''ADVANCE_DRAFT_PICK_INVENTORY'')');d:=replace(d,'Phase 3B.8D','Phase 3B.9A');d:=replace(d,'phase3b8d-v1','phase3b9a-v1');if d not like '%ADVANCE_DRAFT_PICK_INVENTORY%' then raise exception 'dispatcher derivation';end if;execute d;end$$;
create or replace function public.execute_rollover_plan_authenticated(p_request jsonb) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$declare actor uuid:=public.require_authenticated_user();x public.rollover_executions%rowtype;begin if p_request?'actor_user_id' or p_request?'executed_by' then raise exception 'actor spoofing forbidden';end if;select * into x from public.rollover_executions where id=(p_request->>'rollover_execution_id')::uuid;if x.id is null then raise exception 'execution not found';end if;perform public.require_commissioner_authority(x.league_id);return public.execute_rollover_plan_phase3b9a_private(p_request,actor);end$$;
revoke all on function public.write_draft_inventory_phase3b9a_private(uuid,uuid,uuid,uuid),public.execute_rollover_typed_handler_phase3b9a_private(jsonb,uuid,uuid,uuid,uuid),public.execute_rollover_plan_phase3b9a_private(jsonb,uuid),public.guard_phase3b9a_draft_inventory(),public.reject_phase3b9a_generation_mutation() from public,anon,authenticated,service_role;
revoke all on function public.phase3b9a_stable_pick_id(uuid,integer,integer,uuid) from public,anon;grant execute on function public.phase3b9a_stable_pick_id(uuid,integer,integer,uuid) to authenticated,service_role;
revoke all on function public.execute_rollover_plan_authenticated(jsonb) from public,anon,authenticated,service_role;grant execute on function public.execute_rollover_plan_authenticated(jsonb) to authenticated;
commit;
