begin;
alter table public.rollover_execution_handler_registry drop constraint rollover_execution_handler_registry_mutation_class_check;
alter table public.rollover_execution_handler_registry add constraint rollover_execution_handler_registry_mutation_class_check check(mutation_class in('read_only','contract_domain','roster_domain','taxi_domain','taxi_eligibility_domain','ir_domain','draft_inventory_domain','rookie_authority_domain','rookie_eligibility_domain','dead_cap_domain','team_cap_domain','free_agent_domain','expiring_contract_domain','standings_domain','matchup_domain','playoff_domain','cache_domain','validation_domain'));
insert into public.rollover_execution_handler_registry(operation_code,operation_order,handler_version,input_schema_version,result_schema_version,execution_owner,mutation_class,metadata) values('VALIDATE_POST_EXECUTION_STATE',30,1,'phase3b12b-validation-input-v1','phase3b12b-validation-result-v1','execution','validation_domain',jsonb_build_object('phase','3B.12B','validation_only',true,'publication',false));
do $$declare d text;sig regprocedure;begin foreach sig in array array['public.guard_contract_write_during_rollover()'::regprocedure,'public.guard_season_roster_assignment_insert_phase3b8a()'::regprocedure,'public.guard_phase3b9a_draft_inventory()'::regprocedure,'public.guard_phase3b9b_rookie_authority()'::regprocedure,'public.guard_phase3b9c_rookie_eligibility()'::regprocedure] loop select pg_get_functiondef(sig) into d;d:=replace(d,'''phase3b12a-v1'')','''phase3b12a-v1'',''phase3b12b-v1'')');execute d;end loop;end$$;

create table public.rollover_post_execution_validation_registry(validation_code text primary key,domain_code text not null,description text not null,severity text not null check(severity in('passed','warning','publication_blocker','execution_failure')),execution_blocking boolean not null,publication_blocking boolean not null,source_operations int[] not null,source_objects text[] not null,validation_method text not null,expected_status text not null,implementation_status text not null check(implementation_status='implemented'),registry_version text not null check(registry_version='phase3b12b-validation-registry-v1'),entry_fingerprint text not null check(entry_fingerprint~'^[0-9a-f]{64}$'),check(execution_blocking=(severity='execution_failure')),check(publication_blocking=(severity='publication_blocker')));
with r(code,domain,descr,severity,eb,pb,ops,objs,method,expected) as(values
('A_EXECUTION_COMPLETE','execution','operations 1-29 exactly once','execution_failure',true,false,array[1,29],array['rollover_execution_operation_results'],'count and identity','passed'),
('B_HISTORY_PRESERVED','history','frozen closing history intact','execution_failure',true,false,array[6,7],array['rollover_execution_input_snapshots','historical_capture_executions'],'snapshot linkage','passed'),
('C_OPTIONS_CONTRACTS_RECONCILE','contracts','target contracts reconcile','execution_failure',true,false,array[10,12],array['contract_seasons','contract_events'],'contract conflicts','passed'),
('C1_OWNER_OPTIONS_COMPLETE','owner_options','final option outcomes complete','execution_failure',true,false,array[9],array['rollover_owner_option_final_outcomes'],'outcome population','passed'),
('D_RELEASE_HOLD_RECONCILE','releases_holds','release and hold custody exclusive','execution_failure',true,false,array[13,14],array['rollover_contract_releases','rollover_commissioner_holds'],'anti-join','passed'),
('E_TARGET_ROSTER_COMPLETE','roster','target assignment set complete','execution_failure',true,false,array[15],array['rollover_target_roster_assignment_sets','season_roster_assignments'],'header population','passed'),
('F_TAXI_IR_RECONCILE','taxi','taxi non-return complete','execution_failure',true,false,array[16,17],array['rollover_taxi_unlock_sets','rollover_taxi_eligibility_authorities'],'header evidence','passed'),
('F1_IR_RECONCILED','ir','IR evidence complete','execution_failure',true,false,array[18],array['rollover_ir_reconciliations'],'conflict anti-join','passed'),
('G_DRAFT_ROOKIE_COMPLETE','draft','four three-round draft classes complete','execution_failure',true,false,array[19],array['draft_pick_assets'],'class round population','passed'),
('G1_ROOKIE_AUTHORITY_COMPLETE','rookie','rookie authority eligibility complete','execution_failure',true,false,array[20,21],array['league_rookie_class_authorities','prepared_rookie_eligibility_sets'],'authority linkage','passed'),
('H_CAP_ARITHMETIC','caps','dead cap and team cap arithmetic','execution_failure',true,false,array[22,23],array['prepared_team_caps'],'arithmetic','passed'),
('H_OVER_CAP_PUBLICATION_BLOCKER','caps','over-cap blocks publication','publication_blocker',false,true,array[23],array['prepared_team_caps'],'blocker count','passed_or_publication_blocker'),
('I_MARKET_POPULATIONS_COMPLETE','free_agents','free-agent population complete','execution_failure',true,false,array[24],array['prepared_free_agent_eligibility_sets'],'header population','passed'),
('I1_EXPIRING_COMPLETE','expiring_contracts','expiring population complete','execution_failure',true,false,array[25],array['prepared_expiring_contract_sets'],'header population','passed'),
('J_COMPETITION_EMPTY','standings','standings zero complete','execution_failure',true,false,array[26],array['prepared_target_standings_sets'],'zero population','passed'),
('J1_MATCHUPS_EMPTY','matchups','matchup state empty','execution_failure',true,false,array[27],array['prepared_target_matchup_sets'],'empty header','passed'),
('J2_PLAYOFFS_EMPTY','playoffs','playoff state empty','execution_failure',true,false,array[28],array['prepared_target_playoff_structures'],'empty structure','passed'),
('K_CACHE_MANIFEST_COMPLETE','cache','cache manifest complete','execution_failure',true,false,array[29],array['season_cache_invalidation_manifests'],'registry population','passed'),
('L_PUBLICATION_BOUNDARY_INTACT','publication','target remains unpublished','execution_failure',true,false,array[23,29],array['league_seasons'],'boundary anti-join','passed'),
('M_CUTOVER_LOCK_CONTINUITY','cutover_lock','cutover lock remains identity bound','execution_failure',true,false,array[1,30],array['rollover_execution_locks'],'active lock identity','passed'))
insert into public.rollover_post_execution_validation_registry select code,domain,descr,severity,eb,pb,ops,objs,method,expected,'implemented','phase3b12b-validation-registry-v1',public.rollover_material_fingerprint(jsonb_build_object('code',code,'domain',domain,'severity',severity,'ops',ops,'objects',objs,'method',method)) from r;
alter table public.rollover_post_execution_validation_registry enable row level security;revoke all on public.rollover_post_execution_validation_registry from public,anon,authenticated;grant select on public.rollover_post_execution_validation_registry to service_role;

create table public.rollover_post_execution_validation_reports(id uuid primary key default gen_random_uuid(),rollover_execution_id uuid not null unique references public.rollover_executions(id),league_id uuid not null references public.leagues(id),closing_season_id uuid not null references public.league_seasons(id),target_season_id uuid not null references public.league_seasons(id),snapshot_id uuid not null references public.rollover_execution_input_snapshots(id),operation_catalog_version text not null,operation_catalog_hash text not null,validation_registry_version text not null,validation_registry_hash text not null,expected_check_count int not null,actual_check_count int not null,passed_count int not null,warning_count int not null,publication_blocker_count int not null,execution_failure_count int not null,validation_status text not null check(validation_status in('completed','completed_with_warnings','completed_with_publication_blockers')),publication_eligible boolean not null,aggregate_validation_hash text not null check(aggregate_validation_hash~'^[0-9a-f]{64}$'),schema_version text not null check(schema_version='phase3b12b-validation-v1'),created_at timestamptz not null default clock_timestamp(),check(actual_check_count=passed_count+warning_count+publication_blocker_count+execution_failure_count),check(execution_failure_count=0),check(publication_eligible=(execution_failure_count=0 and publication_blocker_count=0 and actual_check_count=expected_check_count)));
create table public.rollover_post_execution_validation_checks(id uuid primary key default gen_random_uuid(),report_id uuid not null references public.rollover_post_execution_validation_reports(id),validation_code text not null,domain_code text not null,severity text not null check(severity in('passed','warning','publication_blocker','execution_failure')),status text not null check(status in('passed','warning','publication_blocker','execution_failure')),expected_state jsonb not null,observed_state jsonb not null,affected_entity_count int not null default 0,source_evidence_hashes jsonb not null,publication_blocking boolean not null,execution_blocking boolean not null,bounded_sanitized_diagnostics jsonb not null check(length(bounded_sanitized_diagnostics::text)<=2048),deterministic_check_fingerprint text not null check(deterministic_check_fingerprint~'^[0-9a-f]{64}$'),created_at timestamptz not null default clock_timestamp(),unique(report_id,validation_code));
do $$declare t text;begin foreach t in array array['rollover_post_execution_validation_reports','rollover_post_execution_validation_checks'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from public,anon,authenticated',t);execute format('grant select,insert on public.%I to service_role',t);end loop;end$$;
create policy post_validation_report_commissioner_read on public.rollover_post_execution_validation_reports for select to authenticated using(exists(select 1 from public.league_memberships m where m.league_id=rollover_post_execution_validation_reports.league_id and m.user_id=auth.uid() and m.role='commissioner'));
create policy post_validation_check_commissioner_read on public.rollover_post_execution_validation_checks for select to authenticated using(exists(select 1 from public.rollover_post_execution_validation_reports h join public.league_memberships m on m.league_id=h.league_id where h.id=rollover_post_execution_validation_checks.report_id and m.user_id=auth.uid() and m.role='commissioner'));
create or replace function public.guard_phase3b12b_validation_evidence() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$begin if tg_op in('UPDATE','DELETE') then raise exception 'post_execution_validation_evidence_immutable';end if;return new;end$$;
create trigger post_validation_reports_immutable before update or delete on public.rollover_post_execution_validation_reports for each row execute function public.guard_phase3b12b_validation_evidence();create trigger post_validation_checks_immutable before update or delete on public.rollover_post_execution_validation_checks for each row execute function public.guard_phase3b12b_validation_evidence();

create or replace function public.write_post_validation_phase3b12b_private(p_rollover_execution_id uuid,p_execution_plan_id uuid,p_approval_id uuid,p_actor uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare x public.rollover_executions%rowtype;src public.league_seasons%rowtype;tgt public.league_seasons%rowtype;snap public.rollover_execution_input_snapshots%rowtype;rep public.rollover_post_execution_validation_reports%rowtype;r public.rollover_post_execution_validation_registry%rowtype;ok boolean;affected int;status text;obs jsonb;checkhash text;registryhash text;cataloghash text;aggregatehash text;expected int;passed int:=0;blockers int:=0;failures int:=0;checks jsonb:='[]'::jsonb;overcaps int;
begin
 if p_actor is null then perform public.raise_phase3b6c1_failure('post_validation_execution_failure','{}');end if;select * into x from public.rollover_executions where id=p_rollover_execution_id;select * into src from public.league_seasons where league_id=x.league_id and season=x.source_season for share;select * into tgt from public.league_seasons where league_id=x.league_id and season=x.target_season for share;select * into snap from public.rollover_execution_input_snapshots where rollover_execution_id=x.id for share;
 select count(*),public.rollover_material_fingerprint(jsonb_agg(jsonb_build_object('code',validation_code,'hash',entry_fingerprint) order by domain_code,validation_code)) into expected,registryhash from public.rollover_post_execution_validation_registry;if expected<>20 then perform public.raise_phase3b6c1_failure('post_validation_registry_invalid','{}');end if;select public.rollover_material_fingerprint(jsonb_agg(jsonb_build_object('code',operation_code,'order',operation_order,'version',handler_version) order by operation_order)) into cataloghash from public.rollover_execution_handler_registry;
 for r in select * from public.rollover_post_execution_validation_registry order by domain_code,validation_code loop affected:=0;ok:=false;
  case r.validation_code
  when 'A_EXECUTION_COMPLETE' then select count(*)=29 and count(distinct operation_index)=29 and min(operation_index)=1 and max(operation_index)=29,count(*) into ok,affected from public.rollover_execution_operation_results where execution_run_id=(select id from public.rollover_execution_runs where rollover_execution_id=x.id order by started_at desc limit 1) and operation_status='completed';
  when 'B_HISTORY_PRESERVED' then ok:=snap.id is not null and src.id is not null and tgt.id is not null and src.id<>tgt.id and exists(select 1 from public.historical_capture_executions h where h.league_season_id=src.id and h.status in('validated','finalized'));
  when 'C_OPTIONS_CONTRACTS_RECONCILE' then select count(*) into affected from public.contract_seasons where league_id=x.league_id and season=x.target_season;ok:=not exists(select 1 from public.contract_seasons where league_id=x.league_id and season=x.target_season group by contract_id having count(*)>1);
  when 'C1_OWNER_OPTIONS_COMPLETE' then select count(*) into affected from public.rollover_owner_option_final_outcomes where rollover_execution_id=x.id;ok:=not exists(select 1 from public.rollover_owner_option_snapshot_v2_cases c join public.rollover_owner_option_snapshot_v2 s on s.id=c.owner_option_snapshot_v2_id where s.rollover_execution_id=x.id and not exists(select 1 from public.rollover_owner_option_final_outcomes f where f.rollover_execution_id=x.id and f.player_id=c.player_id));
  when 'D_RELEASE_HOLD_RECONCILE' then select count(*) into affected from public.rollover_contract_releases where rollover_execution_id=x.id;ok:=not exists(select 1 from public.rollover_commissioner_holds h join public.season_roster_assignments a on a.sleeper_player_id=h.player_id and a.league_season_id=tgt.id where h.rollover_execution_id=x.id) and not exists(select 1 from public.free_agent_publications where league_id=x.league_id and season=x.target_season);
  when 'E_TARGET_ROSTER_COMPLETE' then select count(*) into affected from public.season_roster_assignments where assignment_set_id=(select id from public.rollover_target_roster_assignment_sets where rollover_execution_id=x.id);ok:=exists(select 1 from public.rollover_target_roster_assignment_sets s where s.rollover_execution_id=x.id and s.expected_row_count=affected and s.status='complete_unpublished');
  when 'F_TAXI_IR_RECONCILE' then select count(*) into affected from public.rollover_taxi_eligibility_authorities where rollover_execution_id=x.id;ok:=exists(select 1 from public.rollover_taxi_unlock_sets where rollover_execution_id=x.id);
  when 'F1_IR_RECONCILED' then select count(*) into affected from public.rollover_ir_reconciliations where rollover_execution_id=x.id;ok:=not exists(select 1 from public.rollover_ir_reconciliations where rollover_execution_id=x.id and taxi_conflict);
  when 'G_DRAFT_ROOKIE_COMPLETE' then select count(*) into affected from public.draft_pick_assets where league_id=x.league_id;ok:=exists(select 1 from public.rollover_draft_inventory_generations where rollover_execution_id=x.id and target_visible_class_count=4 and rounds_per_class=3) and affected=4*3*(select count(*) from public.league_teams where league_id=x.league_id) and not exists(select 1 from public.draft_pick_assets where league_id=x.league_id group by draft_year,round_number having count(*)<>(select count(*) from public.league_teams where league_id=x.league_id));
  when 'G1_ROOKIE_AUTHORITY_COMPLETE' then select count(*) into affected from public.prepared_rookie_eligibilities e join public.prepared_rookie_eligibility_sets s on s.id=e.eligibility_set_id where s.rollover_execution_id=x.id;ok:=exists(select 1 from public.prepared_rookie_eligibility_sets s where s.rollover_execution_id=x.id and s.expected_population=affected);
  when 'H_CAP_ARITHMETIC' then select count(*) into affected from public.prepared_team_caps c join public.prepared_team_cap_sets s on s.id=c.cap_set_id where s.rollover_execution_id=x.id;ok:=affected=(select count(*) from public.league_teams where league_id=x.league_id) and not exists(select 1 from public.prepared_team_caps c join public.prepared_team_cap_sets s on s.id=c.cap_set_id where s.rollover_execution_id=x.id and(c.total_cap_charge<>c.active_target_salary+c.prepared_dead_cap or c.cap_space<>c.salary_cap_limit-c.total_cap_charge));
  when 'H_OVER_CAP_PUBLICATION_BLOCKER' then select count(*) into overcaps from public.prepared_team_caps c join public.prepared_team_cap_sets s on s.id=c.cap_set_id where s.rollover_execution_id=x.id and c.is_over_cap;affected:=overcaps;ok:=overcaps=0;
  when 'I_MARKET_POPULATIONS_COMPLETE' then select count(*) into affected from public.prepared_free_agent_eligibilities e join public.prepared_free_agent_eligibility_sets s on s.id=e.eligibility_set_id where s.rollover_execution_id=x.id;ok:=exists(select 1 from public.prepared_free_agent_eligibility_sets s where s.rollover_execution_id=x.id and s.expected_player_count=affected);
  when 'I1_EXPIRING_COMPLETE' then select count(*) into affected from public.prepared_expiring_contract_eligibilities e join public.prepared_expiring_contract_sets s on s.id=e.expiring_set_id where s.rollover_execution_id=x.id;ok:=exists(select 1 from public.prepared_expiring_contract_sets s where s.rollover_execution_id=x.id and s.expected_row_count=affected and s.visible_horizon_length=4);
  when 'J_COMPETITION_EMPTY' then select count(*) into affected from public.prepared_target_standings a join public.prepared_target_standings_sets s on s.id=a.standings_set_id where s.rollover_execution_id=x.id;ok:=exists(select 1 from public.prepared_target_standings_sets s where s.rollover_execution_id=x.id and s.expected_team_count=affected) and not exists(select 1 from public.prepared_target_standings a join public.prepared_target_standings_sets s on s.id=a.standings_set_id where s.rollover_execution_id=x.id and(a.wins<>0 or a.losses<>0 or a.ties<>0));
  when 'J1_MATCHUPS_EMPTY' then ok:=exists(select 1 from public.prepared_target_matchup_sets where rollover_execution_id=x.id and expected_matchup_count=0 and actual_matchup_count=0 and published_at is null) and not exists(select 1 from public.season_matchups where league_season_id=tgt.id);
  when 'J2_PLAYOFFS_EMPTY' then ok:=exists(select 1 from public.prepared_target_playoff_structures where rollover_execution_id=x.id and participant_count=0 and seed_count=0 and bracket_row_count=0 and result_row_count=0 and qualification_status='pending' and published_at is null) and not exists(select 1 from public.season_playoff_brackets where league_season_id=tgt.id);
  when 'K_CACHE_MANIFEST_COMPLETE' then select count(*) into affected from public.season_cache_invalidation_entries e join public.season_cache_invalidation_manifests h on h.id=e.manifest_id where h.rollover_execution_id=x.id;ok:=exists(select 1 from public.season_cache_invalidation_manifests h where h.rollover_execution_id=x.id and h.expected_entry_count=affected and h.published_at is null) and not exists(select 1 from public.season_cache_invalidation_entries e join public.season_cache_invalidation_manifests h on h.id=e.manifest_id where h.rollover_execution_id=x.id and e.blocking);
  when 'L_PUBLICATION_BOUNDARY_INTACT' then ok:=tgt.id is not null and not tgt.is_active and tgt.status='scheduled' and not exists(select 1 from public.rollover_execution_operation_results where rollover_execution_id=x.id and operation_index>30);
  when 'M_CUTOVER_LOCK_CONTINUITY' then ok:=exists(select 1 from public.rollover_execution_locks l where l.rollover_execution_id=x.id and l.execution_plan_id=p_execution_plan_id and l.approval_id=p_approval_id and l.status='active' and l.lock_type='cutover' and l.lock_scope='rollover_global' for update);
  end case;
  if r.severity='publication_blocker' and not ok then status:='publication_blocker';blockers:=blockers+1;else status:=case when ok then 'passed' else 'execution_failure' end;if ok then passed:=passed+1;else failures:=failures+1;end if;end if;obs:=jsonb_build_object('satisfied',ok,'affected_count',affected);checkhash:=public.rollover_material_fingerprint(jsonb_build_object('execution',x.id,'code',r.validation_code,'status',status,'observed',obs,'snapshot',snap.aggregate_snapshot_fingerprint));checks:=checks||jsonb_build_array(jsonb_build_object('code',r.validation_code,'domain',r.domain_code,'status',status,'affected',affected,'hash',checkhash));
 end loop;
 if failures>0 then perform public.raise_phase3b6c1_failure('post_validation_execution_failure',jsonb_build_object('failure_count',failures));end if;aggregatehash:=public.rollover_material_fingerprint(jsonb_build_object('schema','phase3b12b-validation-v1','execution',x.id,'registry_hash',registryhash,'catalog_hash',cataloghash,'checks',checks));select * into rep from public.rollover_post_execution_validation_reports where rollover_execution_id=x.id for update;if found then if rep.aggregate_validation_hash<>aggregatehash then perform public.raise_phase3b6c1_failure('post_validation_report_conflict','{}');end if;return jsonb_build_object('registered_validation_count',expected,'produced_validation_count',expected,'passed_count',passed,'warning_count',0,'publication_blocker_count',blockers,'execution_failure_count',0,'publication_eligible',blockers=0,'validated_operation_count',29,'missing_operation_count',0,'compatible_replay_count',1,'mutation_count',0,'aggregate_validation_hash',aggregatehash,'validation_codes',(select jsonb_agg(validation_code order by domain_code,validation_code) from public.rollover_post_execution_validation_registry));end if;
 insert into public.rollover_post_execution_validation_reports(rollover_execution_id,league_id,closing_season_id,target_season_id,snapshot_id,operation_catalog_version,operation_catalog_hash,validation_registry_version,validation_registry_hash,expected_check_count,actual_check_count,passed_count,warning_count,publication_blocker_count,execution_failure_count,validation_status,publication_eligible,aggregate_validation_hash,schema_version) values(x.id,x.league_id,src.id,tgt.id,snap.id,'phase3b12b-operation-catalog-v1',cataloghash,'phase3b12b-validation-registry-v1',registryhash,expected,expected,passed,0,blockers,0,case when blockers>0 then 'completed_with_publication_blockers' else 'completed' end,blockers=0,aggregatehash,'phase3b12b-validation-v1') returning * into rep;
 for r in select * from public.rollover_post_execution_validation_registry order by domain_code,validation_code loop obs:=(select e->'observed' from jsonb_array_elements(checks) e where e->>'code'=r.validation_code);status:=(select e->>'status' from jsonb_array_elements(checks) e where e->>'code'=r.validation_code);affected:=coalesce((select(e->>'affected')::int from jsonb_array_elements(checks)e where e->>'code'=r.validation_code),0);checkhash:=(select e->>'hash' from jsonb_array_elements(checks)e where e->>'code'=r.validation_code);insert into public.rollover_post_execution_validation_checks(report_id,validation_code,domain_code,severity,status,expected_state,observed_state,affected_entity_count,source_evidence_hashes,publication_blocking,execution_blocking,bounded_sanitized_diagnostics,deterministic_check_fingerprint) values(rep.id,r.validation_code,r.domain_code,case when status='passed' then 'passed' else r.severity end,status,jsonb_build_object('status',r.expected_status),coalesce(obs,'{}'),affected,jsonb_build_object('snapshot',snap.aggregate_snapshot_fingerprint,'registry',r.entry_fingerprint),r.publication_blocking,r.execution_blocking,'{}',checkhash);end loop;
 return jsonb_build_object('registered_validation_count',expected,'produced_validation_count',expected,'passed_count',passed,'warning_count',0,'publication_blocker_count',blockers,'execution_failure_count',0,'publication_eligible',blockers=0,'validated_operation_count',29,'missing_operation_count',0,'compatible_replay_count',0,'mutation_count',expected+1,'aggregate_validation_hash',aggregatehash,'validation_codes',(select jsonb_agg(validation_code order by domain_code,validation_code) from public.rollover_post_execution_validation_registry));
end$$;
create or replace function public.execute_rollover_typed_handler_phase3b12b_private(p_operation jsonb,p_rollover_execution_id uuid,p_execution_plan_id uuid,p_approval_id uuid,p_actor uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$declare code text:=p_operation->>'operation_type';result jsonb;begin if code<>'VALIDATE_POST_EXECUTION_STATE' then return public.execute_rollover_typed_handler_phase3b12a_private(p_operation,p_rollover_execution_id,p_execution_plan_id,p_approval_id,p_actor);end if;if(p_operation->>'operation_index')::int<>30 then perform public.raise_phase3b6c1_failure('unsupported_handler_version','{}');end if;result:=public.write_post_validation_phase3b12b_private(p_rollover_execution_id,p_execution_plan_id,p_approval_id,p_actor);return jsonb_build_object('operation_code',code,'handler_version',1,'result',result||jsonb_build_object('operation_mutation_count',(result->>'mutation_count')::int));end$$;
do $$declare d text;begin select pg_get_functiondef('public.execute_rollover_plan_phase3b12a_private(jsonb,uuid)'::regprocedure) into d;d:=replace(d,'execute_rollover_plan_phase3b12a_private','execute_rollover_plan_phase3b12b_private');d:=replace(d,'execute_rollover_typed_handler_phase3b12a_private','execute_rollover_typed_handler_phase3b12b_private');d:=replace(d,'''INVALIDATE_SEASON_DERIVED_CACHES'')','''INVALIDATE_SEASON_DERIVED_CACHES'',''VALIDATE_POST_EXECUTION_STATE'')');d:=replace(d,'Phase 3B.12A','Phase 3B.12B');d:=replace(d,'phase3b12a-v1','phase3b12b-v1');execute d;end$$;
create or replace function public.execute_rollover_plan_authenticated(p_request jsonb) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$declare actor uuid:=public.require_authenticated_user();x public.rollover_executions%rowtype;begin if p_request?'actor_user_id' or p_request?'executed_by' or p_request?'expected_counts' or p_request?'validation_results' or p_request?'publication_eligible' or p_request?'checks' then raise exception 'actor or validation material spoofing forbidden';end if;select * into x from public.rollover_executions where id=(p_request->>'rollover_execution_id')::uuid;if x.id is null then raise exception 'execution not found';end if;perform public.require_commissioner_authority(x.league_id);return public.execute_rollover_plan_phase3b12b_private(p_request,actor);end$$;
revoke all on function public.write_post_validation_phase3b12b_private(uuid,uuid,uuid,uuid),public.execute_rollover_typed_handler_phase3b12b_private(jsonb,uuid,uuid,uuid,uuid),public.execute_rollover_plan_phase3b12b_private(jsonb,uuid),public.guard_phase3b12b_validation_evidence() from public,anon,authenticated,service_role;revoke all on function public.execute_rollover_plan_authenticated(jsonb) from public,anon,authenticated,service_role;grant execute on function public.execute_rollover_plan_authenticated(jsonb) to authenticated;
commit;
