begin;
alter table public.rollover_execution_handler_registry drop constraint rollover_execution_handler_registry_mutation_class_check;
alter table public.rollover_execution_handler_registry add constraint rollover_execution_handler_registry_mutation_class_check check(mutation_class in('read_only','contract_domain','roster_domain','taxi_domain','taxi_eligibility_domain','ir_domain','draft_inventory_domain','rookie_authority_domain','rookie_eligibility_domain'));
insert into public.rollover_execution_handler_registry(operation_code,operation_order,handler_version,input_schema_version,result_schema_version,execution_owner,mutation_class,metadata) values('REFRESH_ROOKIE_ELIGIBILITY',21,1,'phase3b9c-rookie-eligibility-input-v1','phase3b9c-rookie-eligibility-result-v1','execution','rookie_eligibility_domain',jsonb_build_object('phase','3B.9C','publication',false,'taxi_mutation',false));
create or replace function public.guard_contract_write_during_rollover() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$declare lid uuid:=coalesce(new.league_id,old.league_id);begin if coalesce(current_setting('app.rollover_typed_execution',true),'') not in('phase3b7c-v1','phase3b8a-v1','phase3b8b-v1','phase3b8c-v1','phase3b8d-v1','phase3b9a-v1','phase3b9b-v1','phase3b9c-v1') then perform public.assert_no_active_rollover_cutover_lock(lid);end if;return case when tg_op='DELETE' then old else new end;end$$;
create or replace function public.guard_season_roster_assignment_insert_phase3b8a() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$declare season_row public.league_seasons%rowtype;team_row public.league_teams%rowtype;begin select * into season_row from public.league_seasons where id=new.league_season_id;select * into team_row from public.league_teams where id=new.league_team_id;if season_row.id is null or team_row.id is null or season_row.league_id<>team_row.league_id then raise exception 'target_roster_team_cross_league';end if;if public.has_active_rollover_cutover_lock(season_row.league_id) and coalesce(current_setting('app.rollover_typed_execution',true),'') not in('phase3b8a-v1','phase3b8b-v1','phase3b8c-v1','phase3b8d-v1','phase3b9a-v1','phase3b9b-v1','phase3b9c-v1') then raise exception 'rollover_cutover_roster_writes_blocked';end if;return new;end$$;
create or replace function public.guard_phase3b9a_draft_inventory() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$declare lid uuid:=coalesce(new.league_id,old.league_id);begin if tg_table_name='draft_pick_assets' then if tg_op='UPDATE' and new.stable_pick_id<>old.stable_pick_id then raise exception 'draft_pick_hash_mismatch';end if;if tg_op='UPDATE' and(new.original_league_team_id<>old.original_league_team_id or new.draft_year<>old.draft_year or new.round_number<>old.round_number or new.class_id<>old.class_id) then raise exception 'draft_pick_original_owner_immutable';end if;elsif tg_table_name='draft_inventory_classes' then if tg_op='UPDATE' and(new.league_id<>old.league_id or new.draft_year<>old.draft_year) then raise exception 'draft_class_identity_immutable';end if;end if;if public.has_active_rollover_cutover_lock(lid) and coalesce(current_setting('app.rollover_typed_execution',true),'') not in('phase3b7c-v1','phase3b8a-v1','phase3b8b-v1','phase3b8c-v1','phase3b8d-v1','phase3b9a-v1','phase3b9b-v1','phase3b9c-v1') then raise exception 'rollover_cutover_draft_writes_blocked';end if;return case when tg_op='DELETE' then old else new end;end$$;
create or replace function public.guard_phase3b9b_rookie_authority() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$declare lid uuid:=coalesce(new.league_id,old.league_id);begin if tg_op in('UPDATE','DELETE') then raise exception 'rookie_authority_immutable';end if;if public.has_active_rollover_cutover_lock(lid) and coalesce(current_setting('app.rollover_typed_execution',true),'') not in('phase3b7c-v1','phase3b8a-v1','phase3b8b-v1','phase3b8c-v1','phase3b8d-v1','phase3b9a-v1','phase3b9b-v1','phase3b9c-v1') then raise exception 'rollover_cutover_rookie_authority_writes_blocked';end if;return new;end$$;

create table public.prepared_rookie_eligibility_sets(
 id uuid primary key default gen_random_uuid(),rollover_execution_id uuid not null unique references public.rollover_executions(id),authority_id uuid not null unique references public.league_rookie_class_authorities(id),league_id uuid not null references public.leagues(id),target_season_id uuid not null references public.league_seasons(id),rookie_class_year integer not null,status text not null check(status='prepared_unpublished'),expected_population integer not null,eligibility_set_hash text not null check(eligibility_set_hash~'^[0-9a-f]{64}$'),source_authority_fingerprint text not null check(source_authority_fingerprint~'^[0-9a-f]{64}$'),source_snapshot_hash text not null check(source_snapshot_hash~'^[0-9a-f]{64}$'),schema_version text not null check(schema_version='phase3b9c-rookie-v1'),created_at timestamptz not null default clock_timestamp());
create table public.prepared_rookie_eligibilities(
 id uuid primary key default gen_random_uuid(),eligibility_set_id uuid not null references public.prepared_rookie_eligibility_sets(id),authority_id uuid not null references public.league_rookie_class_authorities(id),league_id uuid not null references public.leagues(id),target_season_id uuid not null references public.league_seasons(id),rookie_class_year integer not null,player_id text not null references public.player_universe(sleeper_id),eligibility_status text not null check(eligibility_status in('prepared_eligible','prepared_ineligible','excluded_released','excluded_commissioner_hold','excluded_invalid_classification','conflicting_evidence')),eligibility_reason_code text not null,draft_year integer,draft_round integer,rookie_contract_indicator boolean not null,taxi_eligibility_compatible boolean not null,source_player_fingerprint text not null check(source_player_fingerprint~'^[0-9a-f]{64}$'),source_authority_fingerprint text not null check(source_authority_fingerprint~'^[0-9a-f]{64}$'),prepared_execution_id uuid not null references public.rollover_executions(id),published_at timestamptz,superseded_at timestamptz,schema_version text not null check(schema_version='phase3b9c-rookie-v1'),deterministic_eligibility_fingerprint text not null check(deterministic_eligibility_fingerprint~'^[0-9a-f]{64}$'),created_at timestamptz not null default clock_timestamp(),unique(authority_id,player_id),unique(eligibility_set_id,player_id),check(published_at is null and superseded_at is null));
alter table public.prepared_rookie_eligibility_sets enable row level security;alter table public.prepared_rookie_eligibilities enable row level security;revoke all on public.prepared_rookie_eligibility_sets,public.prepared_rookie_eligibilities from public,anon,authenticated;grant select,insert on public.prepared_rookie_eligibility_sets,public.prepared_rookie_eligibilities to service_role;
create policy prepared_rookie_set_commissioner_read on public.prepared_rookie_eligibility_sets for select to authenticated using(exists(select 1 from public.league_memberships m where m.league_id=prepared_rookie_eligibility_sets.league_id and m.user_id=auth.uid() and m.role='commissioner'));
create policy prepared_rookie_row_commissioner_read on public.prepared_rookie_eligibilities for select to authenticated using(exists(select 1 from public.league_memberships m where m.league_id=prepared_rookie_eligibilities.league_id and m.user_id=auth.uid() and m.role='commissioner'));
create or replace function public.guard_phase3b9c_rookie_eligibility() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$declare lid uuid:=coalesce(new.league_id,old.league_id);begin if tg_op in('UPDATE','DELETE') then raise exception 'rookie_eligibility_immutable';end if;if public.has_active_rollover_cutover_lock(lid) and coalesce(current_setting('app.rollover_typed_execution',true),'') not in('phase3b7c-v1','phase3b8a-v1','phase3b8b-v1','phase3b8c-v1','phase3b8d-v1','phase3b9a-v1','phase3b9b-v1','phase3b9c-v1') then raise exception 'rollover_cutover_rookie_eligibility_writes_blocked';end if;return new;end$$;
create trigger prepared_rookie_sets_guard before insert or update or delete on public.prepared_rookie_eligibility_sets for each row execute function public.guard_phase3b9c_rookie_eligibility();create trigger prepared_rookie_rows_guard before insert or update or delete on public.prepared_rookie_eligibilities for each row execute function public.guard_phase3b9c_rookie_eligibility();

create or replace function public.write_rookie_eligibility_phase3b9c_private(p_rollover_execution_id uuid,p_execution_plan_id uuid,p_approval_id uuid,p_actor uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare x public.rollover_executions%rowtype;s public.rollover_execution_input_snapshots%rowtype;a public.league_rookie_class_authorities%rowtype;dc public.draft_inventory_classes%rowtype;es public.prepared_rookie_eligibility_sets%rowtype;p public.player_universe%rowtype;rel public.rollover_contract_releases%rowtype;hold public.rollover_commissioner_holds%rowtype;taxi public.rollover_taxi_eligibility_authorities%rowtype;status text;reason text;pf text;rf text;material jsonb:='[]';total int:=0;eligible int:=0;ineligible int:=0;released int:=0;held int:=0;conflicts int:=0;written int:=0;reused int:=0;sethash text;
begin
 select * into x from public.rollover_executions where id=p_rollover_execution_id;if x.id is null then perform public.raise_phase3b6c1_failure('rookie_eligibility_authority_missing','{}');end if;
 if not exists(select 1 from public.rollover_execution_locks l where l.rollover_execution_id=x.id and l.execution_plan_id=p_execution_plan_id and l.approval_id=p_approval_id and l.status='active' and l.lock_type='cutover' and l.lock_scope='rollover_global' for update) then perform public.raise_phase3b6c1_failure('rookie_eligibility_cutover_lock_missing','{}');end if;
 select * into s from public.rollover_execution_input_snapshots where rollover_execution_id=x.id and execution_plan_id=p_execution_plan_id and approval_id=p_approval_id for share;select * into a from public.league_rookie_class_authorities where prepared_execution_id=x.id and authority_status='prepared' for share;
 if a.id is null then perform public.raise_phase3b6c1_failure('rookie_eligibility_authority_missing','{}');end if;if a.league_id<>x.league_id then perform public.raise_phase3b6c1_failure('rookie_eligibility_authority_cross_league','{}');end if;if a.published_at is not null or a.authority_status<>'prepared' then perform public.raise_phase3b6c1_failure('rookie_eligibility_authority_not_prepared','{}');end if;
 select * into dc from public.draft_inventory_classes where id=a.source_draft_inventory_class_id for share;if dc.id is null or dc.league_id<>x.league_id or dc.draft_year<>a.rookie_class_year or dc.deterministic_class_hash<>a.source_draft_inventory_hash then perform public.raise_phase3b6c1_failure('rookie_eligibility_hash_mismatch','{}');end if;
 perform 1 from public.player_universe where sleeper_id in(select sleeper_player_id from public.season_roster_assignments where assignment_set_id=(select id from public.rollover_target_roster_assignment_sets where rollover_execution_id=x.id) union select player_id from public.rollover_contract_releases where rollover_execution_id=x.id) order by sleeper_id for share;perform 1 from public.rollover_contract_releases where rollover_execution_id=x.id order by player_id,id for share;perform 1 from public.rollover_commissioner_holds where rollover_execution_id=x.id order by player_id,id for share;perform 1 from public.rollover_taxi_eligibility_authorities where rollover_execution_id=x.id order by player_id,id for share;perform 1 from public.prepared_rookie_eligibility_sets where rollover_execution_id=x.id for update;perform 1 from public.prepared_rookie_eligibilities where prepared_execution_id=x.id order by player_id,id for update;
 for p in select pu.* from public.player_universe pu where pu.sleeper_id in(select sleeper_player_id from public.season_roster_assignments where assignment_set_id=(select id from public.rollover_target_roster_assignment_sets where rollover_execution_id=x.id) union select player_id from public.rollover_contract_releases where rollover_execution_id=x.id) order by pu.sleeper_id loop
  total:=total+1;select * into rel from public.rollover_contract_releases where rollover_execution_id=x.id and player_id=p.sleeper_id;select * into hold from public.rollover_commissioner_holds where rollover_execution_id=x.id and player_id=p.sleeper_id and hold_status='active';select * into taxi from public.rollover_taxi_eligibility_authorities where rollover_execution_id=x.id and player_id=p.sleeper_id;
  if(p.rookie_class_year is null)<>(p.draft_year is null) or(p.rookie_class_year is not null and p.draft_year is not null and p.rookie_class_year<>p.draft_year) then perform public.raise_phase3b6c1_failure('rookie_eligibility_draft_year_conflict',jsonb_build_object('player',p.sleeper_id));end if;if p.draft_round is not null and p.draft_round not between 1 and 20 then perform public.raise_phase3b6c1_failure('rookie_eligibility_round_invalid',jsonb_build_object('player',p.sleeper_id));end if;if coalesce(p.is_rookie_contract,false) and p.rookie_class_year is null then perform public.raise_phase3b6c1_failure('rookie_eligibility_contract_classification_conflict',jsonb_build_object('player',p.sleeper_id));end if;
  if hold.id is not null then status:='excluded_commissioner_hold';reason:='commissioner_hold';held:=held+1;elsif rel.id is not null then status:='excluded_released';reason:='released';released:=released+1;elsif p.rookie_class_year=a.rookie_class_year and p.draft_year=a.rookie_class_year and p.draft_round between 1 and 20 then if coalesce(taxi.permanent_nonreturn,false) then perform public.raise_phase3b6c1_failure('rookie_eligibility_taxi_conflict',jsonb_build_object('player',p.sleeper_id));end if;status:='prepared_eligible';reason:='matching_prepared_class';eligible:=eligible+1;else status:='prepared_ineligible';reason:=case when p.rookie_class_year is null then 'veteran_or_unclassified' when p.rookie_class_year<a.rookie_class_year then 'older_class' else 'future_class' end;ineligible:=ineligible+1;end if;
  pf:=public.rollover_material_fingerprint(to_jsonb(p)-'created_at'-'updated_at');rf:=public.rollover_material_fingerprint(jsonb_build_object('authority',a.deterministic_authority_fingerprint,'player',p.sleeper_id,'player_hash',pf,'status',status,'reason',reason,'taxi',taxi.deterministic_hash));material:=material||jsonb_build_array(jsonb_build_object('player',p.sleeper_id,'hash',rf));
  if exists(select 1 from public.prepared_rookie_eligibilities where authority_id=a.id and player_id=p.sleeper_id and deterministic_eligibility_fingerprint<>rf) then perform public.raise_phase3b6c1_failure('rookie_eligibility_set_conflict','{}');end if;
 end loop;
 if total=0 then perform public.raise_phase3b6c1_failure('rookie_eligibility_player_missing','{}');end if;sethash:=public.rollover_material_fingerprint(jsonb_build_object('schema','phase3b9c-rookie-v1','authority',a.id,'rows',material));
 insert into public.prepared_rookie_eligibility_sets(rollover_execution_id,authority_id,league_id,target_season_id,rookie_class_year,status,expected_population,eligibility_set_hash,source_authority_fingerprint,source_snapshot_hash,schema_version) values(x.id,a.id,x.league_id,a.target_season_id,a.rookie_class_year,'prepared_unpublished',total,sethash,a.deterministic_authority_fingerprint,s.aggregate_snapshot_fingerprint,'phase3b9c-rookie-v1') on conflict(rollover_execution_id) do nothing;select * into es from public.prepared_rookie_eligibility_sets where rollover_execution_id=x.id;if es.eligibility_set_hash<>sethash then perform public.raise_phase3b6c1_failure('rookie_eligibility_set_conflict','{}');end if;
 for p in select pu.* from public.player_universe pu where pu.sleeper_id in(select sleeper_player_id from public.season_roster_assignments where assignment_set_id=(select id from public.rollover_target_roster_assignment_sets where rollover_execution_id=x.id) union select player_id from public.rollover_contract_releases where rollover_execution_id=x.id) order by pu.sleeper_id loop
  select * into rel from public.rollover_contract_releases where rollover_execution_id=x.id and player_id=p.sleeper_id;select * into hold from public.rollover_commissioner_holds where rollover_execution_id=x.id and player_id=p.sleeper_id and hold_status='active';select * into taxi from public.rollover_taxi_eligibility_authorities where rollover_execution_id=x.id and player_id=p.sleeper_id;if hold.id is not null then status:='excluded_commissioner_hold';reason:='commissioner_hold';elsif rel.id is not null then status:='excluded_released';reason:='released';elsif p.rookie_class_year=a.rookie_class_year and p.draft_year=a.rookie_class_year and p.draft_round between 1 and 20 then status:='prepared_eligible';reason:='matching_prepared_class';else status:='prepared_ineligible';reason:=case when p.rookie_class_year is null then 'veteran_or_unclassified' when p.rookie_class_year<a.rookie_class_year then 'older_class' else 'future_class' end;end if;pf:=public.rollover_material_fingerprint(to_jsonb(p)-'created_at'-'updated_at');rf:=public.rollover_material_fingerprint(jsonb_build_object('authority',a.deterministic_authority_fingerprint,'player',p.sleeper_id,'player_hash',pf,'status',status,'reason',reason,'taxi',taxi.deterministic_hash));insert into public.prepared_rookie_eligibilities(eligibility_set_id,authority_id,league_id,target_season_id,rookie_class_year,player_id,eligibility_status,eligibility_reason_code,draft_year,draft_round,rookie_contract_indicator,taxi_eligibility_compatible,source_player_fingerprint,source_authority_fingerprint,prepared_execution_id,schema_version,deterministic_eligibility_fingerprint) values(es.id,a.id,x.league_id,a.target_season_id,a.rookie_class_year,p.sleeper_id,status,reason,p.draft_year,p.draft_round,coalesce(p.is_rookie_contract,false),not coalesce(taxi.permanent_nonreturn,false),pf,a.deterministic_authority_fingerprint,x.id,'phase3b9c-rookie-v1',rf) on conflict(authority_id,player_id) do nothing;if found then written:=written+1;else reused:=reused+1;end if;end loop;
 if(select count(*) from public.prepared_rookie_eligibilities where eligibility_set_id=es.id)<>total then perform public.raise_phase3b6c1_failure('rookie_eligibility_population_incomplete','{}');end if;
 return jsonb_build_object('total_player_population_evaluated',total,'prepared_eligible_count',eligible,'prepared_ineligible_count',ineligible,'released_exclusion_count',released,'commissioner_hold_exclusion_count',held,'conflicting_evidence_count',conflicts,'rows_written',written,'compatible_replay_count',reused,'authority_id',a.id,'eligibility_set_hash',sethash,'mutation_count',written+1,'postcondition_count',8,'validation_codes',jsonb_build_array('prepared_authority','complete_population','class_draft_consistency','release_hold_exclusions','taxi_nonreturn','unpublished','cutover_lock'));
end$$;
create or replace function public.execute_rollover_typed_handler_phase3b9c_private(p_operation jsonb,p_rollover_execution_id uuid,p_execution_plan_id uuid,p_approval_id uuid,p_actor uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$declare code text:=p_operation->>'operation_type';result jsonb;begin if code<>'REFRESH_ROOKIE_ELIGIBILITY' then return public.execute_rollover_typed_handler_phase3b9b_private(p_operation,p_rollover_execution_id,p_execution_plan_id,p_approval_id,p_actor);end if;if(p_operation->>'operation_index')::int<>21 then perform public.raise_phase3b6c1_failure('unsupported_handler_version','{}');end if;result:=public.write_rookie_eligibility_phase3b9c_private(p_rollover_execution_id,p_execution_plan_id,p_approval_id,p_actor);return jsonb_build_object('operation_code',code,'handler_version',1,'result',result||jsonb_build_object('operation_mutation_count',coalesce((result->>'mutation_count')::int,0)));end$$;
do $$declare d text;begin select pg_get_functiondef('public.execute_rollover_plan_phase3b9b_private(jsonb,uuid)'::regprocedure) into d;d:=replace(d,'execute_rollover_plan_phase3b9b_private','execute_rollover_plan_phase3b9c_private');d:=replace(d,'execute_rollover_typed_handler_phase3b9b_private','execute_rollover_typed_handler_phase3b9c_private');d:=replace(d,'''ADVANCE_ROOKIE_CLASS_AUTHORITY'')','''ADVANCE_ROOKIE_CLASS_AUTHORITY'',''REFRESH_ROOKIE_ELIGIBILITY'')');d:=replace(d,'Phase 3B.9B','Phase 3B.9C');d:=replace(d,'phase3b9b-v1','phase3b9c-v1');if d not like '%REFRESH_ROOKIE_ELIGIBILITY%' then raise exception 'dispatcher derivation';end if;execute d;end$$;
create or replace function public.execute_rollover_plan_authenticated(p_request jsonb) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$declare actor uuid:=public.require_authenticated_user();x public.rollover_executions%rowtype;begin if p_request?'actor_user_id' or p_request?'executed_by' then raise exception 'actor spoofing forbidden';end if;select * into x from public.rollover_executions where id=(p_request->>'rollover_execution_id')::uuid;if x.id is null then raise exception 'execution not found';end if;perform public.require_commissioner_authority(x.league_id);return public.execute_rollover_plan_phase3b9c_private(p_request,actor);end$$;
revoke all on function public.write_rookie_eligibility_phase3b9c_private(uuid,uuid,uuid,uuid),public.execute_rollover_typed_handler_phase3b9c_private(jsonb,uuid,uuid,uuid,uuid),public.execute_rollover_plan_phase3b9c_private(jsonb,uuid),public.guard_phase3b9c_rookie_eligibility() from public,anon,authenticated,service_role;revoke all on function public.execute_rollover_plan_authenticated(jsonb) from public,anon,authenticated,service_role;grant execute on function public.execute_rollover_plan_authenticated(jsonb) to authenticated;
commit;
