begin;
alter table public.rollover_execution_handler_registry drop constraint rollover_execution_handler_registry_mutation_class_check;
alter table public.rollover_execution_handler_registry add constraint rollover_execution_handler_registry_mutation_class_check check(mutation_class in('read_only','contract_domain','roster_domain','taxi_domain','taxi_eligibility_domain','ir_domain','draft_inventory_domain','rookie_authority_domain'));
insert into public.rollover_execution_handler_registry(operation_code,operation_order,handler_version,input_schema_version,result_schema_version,execution_owner,mutation_class,metadata) values('ADVANCE_ROOKIE_CLASS_AUTHORITY',20,1,'phase3b9b-rookie-authority-input-v1','phase3b9b-rookie-authority-result-v1','execution','rookie_authority_domain',jsonb_build_object('phase','3B.9B','publication',false,'player_eligibility_refresh',false));
create or replace function public.guard_contract_write_during_rollover() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$declare lid uuid:=coalesce(new.league_id,old.league_id);begin if coalesce(current_setting('app.rollover_typed_execution',true),'') not in('phase3b7c-v1','phase3b8a-v1','phase3b8b-v1','phase3b8c-v1','phase3b8d-v1','phase3b9a-v1','phase3b9b-v1') then perform public.assert_no_active_rollover_cutover_lock(lid);end if;return case when tg_op='DELETE' then old else new end;end$$;
create or replace function public.guard_season_roster_assignment_insert_phase3b8a() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$declare season_row public.league_seasons%rowtype;team_row public.league_teams%rowtype;begin select * into season_row from public.league_seasons where id=new.league_season_id;select * into team_row from public.league_teams where id=new.league_team_id;if season_row.id is null or team_row.id is null or season_row.league_id<>team_row.league_id then raise exception 'target_roster_team_cross_league';end if;if public.has_active_rollover_cutover_lock(season_row.league_id) and coalesce(current_setting('app.rollover_typed_execution',true),'') not in('phase3b8a-v1','phase3b8b-v1','phase3b8c-v1','phase3b8d-v1','phase3b9a-v1','phase3b9b-v1') then raise exception 'rollover_cutover_roster_writes_blocked';end if;return new;end$$;
create or replace function public.guard_phase3b9a_draft_inventory() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$declare lid uuid:=coalesce(new.league_id,old.league_id);begin if tg_table_name='draft_pick_assets' then if tg_op='UPDATE' and new.stable_pick_id<>old.stable_pick_id then raise exception 'draft_pick_hash_mismatch';end if;if tg_op='UPDATE' and(new.original_league_team_id<>old.original_league_team_id or new.draft_year<>old.draft_year or new.round_number<>old.round_number or new.class_id<>old.class_id) then raise exception 'draft_pick_original_owner_immutable';end if;elsif tg_table_name='draft_inventory_classes' then if tg_op='UPDATE' and(new.league_id<>old.league_id or new.draft_year<>old.draft_year) then raise exception 'draft_class_identity_immutable';end if;end if;if public.has_active_rollover_cutover_lock(lid) and coalesce(current_setting('app.rollover_typed_execution',true),'') not in('phase3b7c-v1','phase3b8a-v1','phase3b8b-v1','phase3b8c-v1','phase3b8d-v1','phase3b9a-v1','phase3b9b-v1') then raise exception 'rollover_cutover_draft_writes_blocked';end if;return case when tg_op='DELETE' then old else new end;end$$;

create table public.league_rookie_class_authorities(
 id uuid primary key default gen_random_uuid(),league_id uuid not null references public.leagues(id),target_season_id uuid not null references public.league_seasons(id),rookie_class_year integer not null,
 authority_version integer not null check(authority_version>0),authority_status text not null check(authority_status in('prepared','published','superseded','invalidated')),
 prepared_execution_id uuid references public.rollover_executions(id),published_at timestamptz,superseded_at timestamptz,source_draft_inventory_class_id uuid references public.draft_inventory_classes(id),
 source_draft_inventory_hash text,source_snapshot_hash text not null check(source_snapshot_hash~'^[0-9a-f]{64}$'),created_at timestamptz not null default clock_timestamp(),deterministic_authority_fingerprint text not null check(deterministic_authority_fingerprint~'^[0-9a-f]{64}$'),
 unique(league_id,authority_version),check((authority_status='prepared' and prepared_execution_id is not null and published_at is null and superseded_at is null and source_draft_inventory_class_id is not null and source_draft_inventory_hash~'^[0-9a-f]{64}$') or authority_status<>'prepared'));
create unique index league_rookie_authority_published_uidx on public.league_rookie_class_authorities(league_id) where authority_status='published';
create unique index league_rookie_authority_prepared_uidx on public.league_rookie_class_authorities(league_id,target_season_id) where authority_status='prepared';
create table public.rollover_rookie_authority_advancements(
 id uuid primary key default gen_random_uuid(),rollover_execution_id uuid not null unique references public.rollover_executions(id),operation_code text not null check(operation_code='ADVANCE_ROOKIE_CLASS_AUTHORITY'),league_id uuid not null references public.leagues(id),target_season_id uuid not null references public.league_seasons(id),rookie_authority_id uuid not null references public.league_rookie_class_authorities(id),draft_inventory_generation_id uuid not null references public.rollover_draft_inventory_generations(id),current_published_rookie_class_year integer,target_prepared_rookie_class_year integer not null,source_draft_inventory_class_id uuid not null references public.draft_inventory_classes(id),source_draft_inventory_hash text not null check(source_draft_inventory_hash~'^[0-9a-f]{64}$'),source_class_set_hash text not null check(source_class_set_hash~'^[0-9a-f]{64}$'),source_snapshot_hash text not null check(source_snapshot_hash~'^[0-9a-f]{64}$'),deterministic_authority_set_hash text not null check(deterministic_authority_set_hash~'^[0-9a-f]{64}$'),deterministic_fingerprint text not null check(deterministic_fingerprint~'^[0-9a-f]{64}$'),advancement_schema_version text not null check(advancement_schema_version='phase3b9b-rookie-v1'),provenance jsonb not null check(jsonb_typeof(provenance)='object'),created_at timestamptz not null default clock_timestamp());
alter table public.league_rookie_class_authorities enable row level security;alter table public.rollover_rookie_authority_advancements enable row level security;
revoke all on public.league_rookie_class_authorities,public.rollover_rookie_authority_advancements from public,anon,authenticated;grant select,insert on public.league_rookie_class_authorities,public.rollover_rookie_authority_advancements to service_role;
create policy rookie_authority_commissioner_read on public.league_rookie_class_authorities for select to authenticated using(exists(select 1 from public.league_memberships m where m.league_id=league_rookie_class_authorities.league_id and m.user_id=auth.uid() and m.role='commissioner'));
create policy rookie_advancement_commissioner_read on public.rollover_rookie_authority_advancements for select to authenticated using(exists(select 1 from public.league_memberships m where m.league_id=rollover_rookie_authority_advancements.league_id and m.user_id=auth.uid() and m.role='commissioner'));
create or replace function public.guard_phase3b9b_rookie_authority() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$declare lid uuid:=coalesce(new.league_id,old.league_id);begin if tg_op in('UPDATE','DELETE') then raise exception 'rookie_authority_immutable';end if;if public.has_active_rollover_cutover_lock(lid) and coalesce(current_setting('app.rollover_typed_execution',true),'') not in('phase3b7c-v1','phase3b8a-v1','phase3b8b-v1','phase3b8c-v1','phase3b8d-v1','phase3b9a-v1','phase3b9b-v1') then raise exception 'rollover_cutover_rookie_authority_writes_blocked';end if;return new;end$$;
create trigger league_rookie_class_authorities_guard before insert or update or delete on public.league_rookie_class_authorities for each row execute function public.guard_phase3b9b_rookie_authority();
create or replace function public.reject_phase3b9b_advancement_mutation() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$begin raise exception 'Phase 3B.9B advancement evidence is immutable';end$$;
create trigger rollover_rookie_authority_advancements_immutable before update or delete on public.rollover_rookie_authority_advancements for each row execute function public.reject_phase3b9b_advancement_mutation();

create or replace function public.write_rookie_authority_phase3b9b_private(p_rollover_execution_id uuid,p_execution_plan_id uuid,p_approval_id uuid,p_actor uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare x public.rollover_executions%rowtype;s public.rollover_execution_input_snapshots%rowtype;target public.league_seasons%rowtype;gen public.rollover_draft_inventory_generations%rowtype;dc public.draft_inventory_classes%rowtype;pub public.league_rookie_class_authorities%rowtype;prep public.league_rookie_class_authorities%rowtype;version int;created int:=0;reused int:=0;aset_hash text;fp text;
begin
 select * into x from public.rollover_executions where id=p_rollover_execution_id;if x.id is null then perform public.raise_phase3b6c1_failure('rookie_authority_target_season_missing','{}');end if;
 if not exists(select 1 from public.rollover_execution_locks l where l.rollover_execution_id=x.id and l.execution_plan_id=p_execution_plan_id and l.approval_id=p_approval_id and l.status='active' and l.lock_type='cutover' and l.lock_scope='rollover_global' for update) then perform public.raise_phase3b6c1_failure('rookie_authority_cutover_lock_missing','{}');end if;
 select * into s from public.rollover_execution_input_snapshots where rollover_execution_id=x.id and execution_plan_id=p_execution_plan_id and approval_id=p_approval_id for share;
 select ls.* into target from public.league_seasons ls join public.rollover_execution_plans p on p.id=p_execution_plan_id and p.rollover_execution_id=x.id where ls.league_id=x.league_id and ls.season=p.target_season for share;
 if target.id is null then perform public.raise_phase3b6c1_failure('rookie_authority_target_season_missing','{}');end if;if target.league_id<>x.league_id then perform public.raise_phase3b6c1_failure('rookie_authority_target_season_cross_league','{}');end if;if target.season is null then perform public.raise_phase3b6c1_failure('rookie_authority_target_year_unresolved','{}');end if;
 select * into gen from public.rollover_draft_inventory_generations where rollover_execution_id=x.id for share;if gen.id is null then perform public.raise_phase3b6c1_failure('rookie_authority_draft_hash_mismatch','{}');end if;
 select * into dc from public.draft_inventory_classes where league_id=x.league_id and draft_year=target.season for share;if dc.id is null then perform public.raise_phase3b6c1_failure('rookie_authority_draft_class_missing','{}');end if;if(select count(*) from public.draft_inventory_classes where league_id=x.league_id and draft_year=target.season)<>1 then perform public.raise_phase3b6c1_failure('rookie_authority_draft_class_duplicate','{}');end if;
 if(select count(*) from public.draft_pick_assets where class_id=dc.id)<>(select count(*)*3 from public.league_teams where league_id=x.league_id) then perform public.raise_phase3b6c1_failure('rookie_authority_draft_class_incomplete','{}');end if;
 perform 1 from public.draft_pick_assets where class_id=dc.id order by round_number,original_league_team_id,stable_pick_id for share;
 select * into pub from public.league_rookie_class_authorities where league_id=x.league_id and authority_status='published' for share;if pub.rookie_class_year=target.season then perform public.raise_phase3b6c1_failure('rookie_authority_already_published_conflict','{}');end if;
 select * into prep from public.league_rookie_class_authorities where league_id=x.league_id and target_season_id=target.id and authority_status='prepared' for update;
 aset_hash:=public.rollover_material_fingerprint(jsonb_build_object('league',x.league_id,'target_season',target.id,'rookie_year',target.season,'draft_class',dc.id,'draft_hash',dc.deterministic_class_hash,'class_set_hash',gen.deterministic_class_set_hash,'snapshot',s.aggregate_snapshot_fingerprint));
 if prep.id is not null and(prep.prepared_execution_id<>x.id or prep.deterministic_authority_fingerprint<>aset_hash) then perform public.raise_phase3b6c1_failure('rookie_authority_prepared_conflict','{}');end if;
 if prep.id is null then select coalesce(max(authority_version),0)+1 into version from public.league_rookie_class_authorities where league_id=x.league_id;insert into public.league_rookie_class_authorities(league_id,target_season_id,rookie_class_year,authority_version,authority_status,prepared_execution_id,source_draft_inventory_class_id,source_draft_inventory_hash,source_snapshot_hash,deterministic_authority_fingerprint) values(x.league_id,target.id,target.season,version,'prepared',x.id,dc.id,dc.deterministic_class_hash,s.aggregate_snapshot_fingerprint,aset_hash) returning * into prep;created:=1;else reused:=1;end if;
 fp:=public.rollover_material_fingerprint(jsonb_build_object('schema','phase3b9b-rookie-v1','execution',x.id,'authority',prep.id,'authority_hash',aset_hash,'published',pub.id,'generation',gen.id));
 if exists(select 1 from public.rollover_rookie_authority_advancements where rollover_execution_id=x.id and deterministic_fingerprint<>fp) then perform public.raise_phase3b6c1_failure('rookie_authority_source_changed','{}');end if;
 insert into public.rollover_rookie_authority_advancements(rollover_execution_id,operation_code,league_id,target_season_id,rookie_authority_id,draft_inventory_generation_id,current_published_rookie_class_year,target_prepared_rookie_class_year,source_draft_inventory_class_id,source_draft_inventory_hash,source_class_set_hash,source_snapshot_hash,deterministic_authority_set_hash,deterministic_fingerprint,advancement_schema_version,provenance) values(x.id,'ADVANCE_ROOKIE_CLASS_AUTHORITY',x.league_id,target.id,prep.id,gen.id,pub.rookie_class_year,target.season,dc.id,dc.deterministic_class_hash,gen.deterministic_class_set_hash,s.aggregate_snapshot_fingerprint,aset_hash,fp,'phase3b9b-rookie-v1',jsonb_build_object('publication',false,'player_eligibility_mutated',false,'external_calls',false)) on conflict(rollover_execution_id) do nothing;
 if(select count(*) from public.league_rookie_class_authorities where league_id=x.league_id and target_season_id=target.id and authority_status='prepared')<>1 then perform public.raise_phase3b6c1_failure('rookie_authority_population_incomplete','{}');end if;
 return jsonb_build_object('current_published_rookie_class_year',pub.rookie_class_year,'target_prepared_rookie_class_year',target.season,'target_season_id',target.id,'matching_draft_class_id',dc.id,'matching_draft_class_hash',dc.deterministic_class_hash,'prepared_authority_rows_created',created,'compatible_authority_rows_reused',reused,'conflicting_authority_count',0,'published_authority_count',case when pub.id is null then 0 else 1 end,'mutation_count',created+1,'deterministic_authority_set_hash',aset_hash,'validation_codes',jsonb_build_array('target_season','draft_inventory_link','class_complete','published_preserved','prepared_unpublished','cutover_lock'),'postcondition_count',7);
end$$;
create or replace function public.execute_rollover_typed_handler_phase3b9b_private(p_operation jsonb,p_rollover_execution_id uuid,p_execution_plan_id uuid,p_approval_id uuid,p_actor uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$declare code text:=p_operation->>'operation_type';result jsonb;begin if code<>'ADVANCE_ROOKIE_CLASS_AUTHORITY' then return public.execute_rollover_typed_handler_phase3b9a_private(p_operation,p_rollover_execution_id,p_execution_plan_id,p_approval_id,p_actor);end if;if(p_operation->>'operation_index')::int<>20 then perform public.raise_phase3b6c1_failure('unsupported_handler_version','{}');end if;result:=public.write_rookie_authority_phase3b9b_private(p_rollover_execution_id,p_execution_plan_id,p_approval_id,p_actor);return jsonb_build_object('operation_code',code,'handler_version',1,'result',result||jsonb_build_object('operation_mutation_count',coalesce((result->>'mutation_count')::int,0)));end$$;
do $$declare d text;begin select pg_get_functiondef('public.execute_rollover_plan_phase3b9a_private(jsonb,uuid)'::regprocedure) into d;d:=replace(d,'execute_rollover_plan_phase3b9a_private','execute_rollover_plan_phase3b9b_private');d:=replace(d,'execute_rollover_typed_handler_phase3b9a_private','execute_rollover_typed_handler_phase3b9b_private');d:=replace(d,'''ADVANCE_DRAFT_PICK_INVENTORY'')','''ADVANCE_DRAFT_PICK_INVENTORY'',''ADVANCE_ROOKIE_CLASS_AUTHORITY'')');d:=replace(d,'Phase 3B.9A','Phase 3B.9B');d:=replace(d,'phase3b9a-v1','phase3b9b-v1');if d not like '%ADVANCE_ROOKIE_CLASS_AUTHORITY%' then raise exception 'dispatcher derivation';end if;execute d;end$$;
create or replace function public.execute_rollover_plan_authenticated(p_request jsonb) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$declare actor uuid:=public.require_authenticated_user();x public.rollover_executions%rowtype;begin if p_request?'actor_user_id' or p_request?'executed_by' then raise exception 'actor spoofing forbidden';end if;select * into x from public.rollover_executions where id=(p_request->>'rollover_execution_id')::uuid;if x.id is null then raise exception 'execution not found';end if;perform public.require_commissioner_authority(x.league_id);return public.execute_rollover_plan_phase3b9b_private(p_request,actor);end$$;
revoke all on function public.write_rookie_authority_phase3b9b_private(uuid,uuid,uuid,uuid),public.execute_rollover_typed_handler_phase3b9b_private(jsonb,uuid,uuid,uuid,uuid),public.execute_rollover_plan_phase3b9b_private(jsonb,uuid),public.guard_phase3b9b_rookie_authority(),public.reject_phase3b9b_advancement_mutation() from public,anon,authenticated,service_role;
revoke all on function public.execute_rollover_plan_authenticated(jsonb) from public,anon,authenticated,service_role;grant execute on function public.execute_rollover_plan_authenticated(jsonb) to authenticated;
commit;
