begin;
insert into public.rollover_execution_handler_registry(operation_code,operation_order,handler_version,input_schema_version,result_schema_version,execution_owner,mutation_class,metadata) values('REFRESH_PUBLISHED_UI_AND_AI_CONTEXT',36,1,'phase3b13e-context-refresh-input-v1','phase3b13e-context-refresh-result-v1','publication','cache_domain',jsonb_build_object('phase','3B.13E','football_mutation',false,'external_sync',false,'model_call',false));

alter table public.season_cache_invalidation_entries drop constraint season_cache_invalidation_entries_completion_status_check;
alter table public.season_cache_invalidation_entries add constraint season_cache_invalidation_entries_completion_status_check check(completion_status in('completed','pending','not_required','external_pending','failed'));
alter table public.season_cache_invalidation_entries drop constraint season_cache_invalidation_entries_rebuilt_at_check;
alter table public.season_cache_invalidation_entries add constraint season_cache_invalidation_entries_rebuilt_at_check check((completion_status='completed' and rebuilt_at is not null) or(completion_status<>'completed' and rebuilt_at is null));
alter table public.season_cache_invalidation_manifests drop constraint season_cache_invalidation_manifests_status_check;
alter table public.season_cache_invalidation_manifests add constraint season_cache_invalidation_manifests_status_check check(status in('prepared','completed'));
alter table public.season_cache_invalidation_manifests drop constraint season_cache_invalidation_manifests_check;
alter table public.season_cache_invalidation_manifests add constraint season_cache_invalidation_manifests_check check((status='prepared' and published_at is null and completed_at is null) or(status='completed' and published_at is not null and completed_at is not null));

create table public.publication_context_generations(
 id uuid primary key default gen_random_uuid(),rollover_execution_id uuid not null unique references public.rollover_executions(id),league_id uuid not null references public.leagues(id),published_season_id uuid not null references public.league_seasons(id),season_publication_id uuid not null unique references public.rollover_target_season_authority_publications(id),cap_publication_id uuid not null unique references public.rollover_target_cap_authority_publications(id),market_publication_id uuid not null unique references public.rollover_target_market_visibility_publications(id),cutover_release_id uuid not null unique references public.rollover_cutover_release_publications(id),cache_manifest_id uuid not null unique references public.season_cache_invalidation_manifests(id),cache_manifest_hash text not null check(cache_manifest_hash~'^[0-9a-f]{64}$'),context_generation bigint not null check(context_generation>0),ui_generation bigint not null check(ui_generation=context_generation),data_generation bigint not null check(data_generation=context_generation),session_generation bigint not null check(session_generation=context_generation),analytics_generation bigint not null check(analytics_generation=context_generation),ai_context_generation bigint not null check(ai_context_generation=context_generation),gm_assistant_generation bigint not null check(gm_assistant_generation=context_generation),publication_context_status text not null check(publication_context_status='published'),registered_manifest_entry_count int not null check(registered_manifest_entry_count>0),completed_entry_count int not null check(completed_entry_count>=0),not_required_entry_count int not null check(not_required_entry_count>=0),external_pending_count int not null check(external_pending_count>=0),failed_entry_count int not null check(failed_entry_count=0),remediated_read_path_count int not null check(remediated_read_path_count>=0),remaining_stale_path_count int not null check(remaining_stale_path_count=0),aggregate_context_hash text not null check(aggregate_context_hash~'^[0-9a-f]{64}$'),deterministic_fingerprint text not null check(deterministic_fingerprint~'^[0-9a-f]{64}$'),idempotency_key text not null unique,request_fingerprint text not null check(request_fingerprint~'^[0-9a-f]{64}$'),completed_by uuid not null references auth.users(id),completed_at timestamptz not null,schema_version text not null check(schema_version='phase3b13e-publication-context-v1'),unique(league_id,context_generation)
);
alter table public.publication_context_generations enable row level security;
revoke all on public.publication_context_generations from public,anon,authenticated;grant select,insert on public.publication_context_generations to service_role;grant select on public.publication_context_generations to authenticated;
create policy publication_context_member_read on public.publication_context_generations for select to authenticated using(exists(select 1 from public.league_memberships m where m.league_id=publication_context_generations.league_id and m.user_id=auth.uid()));

create function public.guard_phase3b13e_context_evidence() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$begin raise exception 'publication_context_evidence_immutable';end$$;
create trigger publication_context_immutable before update or delete on public.publication_context_generations for each row execute function public.guard_phase3b13e_context_evidence();

create or replace function public.guard_phase3b12a_cache_evidence() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$begin
 if tg_op='DELETE' then raise exception 'cache_manifest_evidence_immutable';end if;
 if current_setting('app.phase3b13e_context_refresh',true)<>'on' then raise exception 'cache_manifest_evidence_immutable';end if;
 if tg_table_name='season_cache_invalidation_manifests' then
  if to_jsonb(new)-array['status','published_at','completed_at'] is distinct from to_jsonb(old)-array['status','published_at','completed_at'] then raise exception 'cache_manifest_source_evidence_immutable';end if;
 elsif tg_table_name='season_cache_invalidation_entries' then
  if to_jsonb(new)-array['current_state','completion_status','rebuilt_at'] is distinct from to_jsonb(old)-array['current_state','completion_status','rebuilt_at'] then raise exception 'cache_entry_source_evidence_immutable';end if;
 end if;return new;
end$$;

create function public.refresh_published_context_phase3b13e_private(p_request jsonb,p_actor uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare x public.rollover_executions%rowtype;f public.rollover_executed_unpublished_finalizations%rowtype;sp public.rollover_target_season_authority_publications%rowtype;cp public.rollover_target_cap_authority_publications%rowtype;mp public.rollover_target_market_visibility_publications%rowtype;cr public.rollover_cutover_release_publications%rowtype;h public.season_cache_invalidation_manifests%rowtype;t public.league_seasons%rowtype;prior public.publication_context_generations%rowtype;g public.publication_context_generations%rowtype;k text:=nullif(btrim(p_request->>'idempotency_key'),'');reqfp text;finalhash text;context_hash text;fp text;at timestamptz:=clock_timestamp();gen bigint;registered int;completed int;notreq int;externalp int;failed int;remediated int:=9;stale int:=0;
begin
 if p_actor is null or k is null or nullif(p_request->>'rollover_execution_id','') is null then raise exception 'context_refresh_execution_missing';end if;
 perform pg_advisory_xact_lock(hashtextextended('phase3b13e:'||(p_request->>'rollover_execution_id'),0));select * into x from public.rollover_executions where id=(p_request->>'rollover_execution_id')::uuid for update;if x.id is null then raise exception 'context_refresh_execution_missing';end if;perform public.require_commissioner_authority(x.league_id);
 reqfp:=public.rollover_material_fingerprint(jsonb_build_object('operation','REFRESH_PUBLISHED_UI_AND_AI_CONTEXT','execution',x.id,'league',x.league_id,'assertions',p_request-'idempotency_key','actor',p_actor));select * into prior from public.publication_context_generations where rollover_execution_id=x.id for share;
 if found then if prior.idempotency_key<>k or prior.request_fingerprint<>reqfp then raise exception 'context_refresh_already_applied_conflict';end if;return jsonb_build_object('success',true,'context_generation_id',prior.id,'execution_id',x.id,'target_season_id',prior.published_season_id,'cache_manifest_id',prior.cache_manifest_id,'registered_manifest_entry_count',prior.registered_manifest_entry_count,'completed_entry_count',prior.completed_entry_count,'not_required_entry_count',prior.not_required_entry_count,'external_pending_entry_count',prior.external_pending_count,'failed_entry_count',prior.failed_entry_count,'ui_generation',prior.ui_generation,'data_generation',prior.data_generation,'session_generation',prior.session_generation,'analytics_generation',prior.analytics_generation,'ai_context_generation',prior.ai_context_generation,'gm_assistant_generation',prior.gm_assistant_generation,'remediated_read_path_count',prior.remediated_read_path_count,'remaining_stale_path_count',0,'compatible_replay_count',1,'operation_mutation_count',0,'postcondition_count',16,'aggregate_context_hash',prior.aggregate_context_hash,'validation_codes',jsonb_build_array('replay','published_context','external_pending'));end if;
 if x.status<>'completed' then raise exception 'context_refresh_execution_state_invalid';end if;
 if nullif(p_request->>'season_publication_id','') is null or nullif(p_request->>'cap_publication_id','') is null or nullif(p_request->>'market_publication_id','') is null or nullif(p_request->>'cutover_release_id','') is null or nullif(p_request->>'expected_season_publication_fingerprint','') is null or nullif(p_request->>'expected_cap_publication_fingerprint','') is null or nullif(p_request->>'expected_market_publication_fingerprint','') is null or nullif(p_request->>'expected_cutover_release_fingerprint','') is null or nullif(p_request->>'expected_manifest_hash','') is null then raise exception 'context_refresh_publication_entry_incomplete';end if;
 select * into f from public.rollover_executed_unpublished_finalizations where rollover_execution_id=x.id for share;if f.id is null then raise exception 'context_refresh_source_hash_mismatch';end if;
 select * into sp from public.rollover_target_season_authority_publications where id=(p_request->>'season_publication_id')::uuid and rollover_execution_id=x.id for share;if sp.id is null or sp.publication_fingerprint<>p_request->>'expected_season_publication_fingerprint' then raise exception 'context_refresh_season_publication_missing';end if;
 select * into cp from public.rollover_target_cap_authority_publications where id=(p_request->>'cap_publication_id')::uuid and rollover_execution_id=x.id and season_publication_id=sp.id for share;if cp.id is null or cp.publication_fingerprint<>p_request->>'expected_cap_publication_fingerprint' then raise exception 'context_refresh_cap_publication_missing';end if;
 select * into mp from public.rollover_target_market_visibility_publications where id=(p_request->>'market_publication_id')::uuid and rollover_execution_id=x.id and cap_publication_id=cp.id for share;if mp.id is null or mp.deterministic_fingerprint<>p_request->>'expected_market_publication_fingerprint' then raise exception 'context_refresh_market_publication_missing';end if;
 select * into cr from public.rollover_cutover_release_publications where id=(p_request->>'cutover_release_id')::uuid and rollover_execution_id=x.id and market_publication_id=mp.id for share;if cr.id is null or cr.release_fingerprint<>p_request->>'expected_cutover_release_fingerprint' then raise exception 'context_refresh_cutover_release_missing';end if;
 if exists(select 1 from public.rollover_execution_locks where id=cr.cutover_lock_id and status<>'released') then raise exception 'context_refresh_cutover_still_active';end if;
 select * into t from public.league_seasons where id=sp.target_season_id and league_id=x.league_id and is_active and status='active' for share;if t.id is null then raise exception 'context_refresh_season_publication_missing';end if;
 select * into h from public.season_cache_invalidation_manifests where rollover_execution_id=x.id for update;if h.id is null then raise exception 'context_refresh_manifest_missing';end if;
 if h.aggregate_manifest_hash<>p_request->>'expected_manifest_hash' or h.aggregate_manifest_hash<>(select aggregate_manifest_hash from public.season_cache_invalidation_manifests where rollover_execution_id=x.id) or public.phase3b13a_prepared_artifact_hash(x.id)<>f.prepared_artifact_aggregate_hash then raise exception 'context_refresh_manifest_hash_mismatch';end if;
 if exists(select 1 from public.season_cache_invalidation_entries e where e.manifest_id=h.id and(e.required_action='blocking_unresolved' or(e.blocking and e.required_action='external_sync_required'))) then raise exception 'context_refresh_manifest_blocker_present';end if;
 perform 1 from public.season_cache_invalidation_entries where manifest_id=h.id order by cache_code for update;perform 1 from public.publication_context_generations where league_id=x.league_id order by context_generation for share;
 registered:=(select count(*) from public.season_cache_invalidation_entries where manifest_id=h.id);if registered<>h.expected_entry_count or registered<>(select count(*) from public.season_derived_cache_registry) then raise exception 'context_refresh_population_incomplete';end if;
 if exists(select 1 from public.season_cache_invalidation_entries e join public.season_derived_cache_registry r using(cache_code) where e.manifest_id=h.id and(e.required_action<>r.required_action or e.source_authority<>r.source_authority or e.blocking<>r.blocking)) then raise exception 'context_refresh_source_hash_mismatch';end if;
 gen:=coalesce((select max(context_generation)+1 from public.publication_context_generations where league_id=x.league_id),1);
 perform set_config('app.phase3b13e_context_refresh','on',true);
 update public.season_cache_invalidation_entries set completion_status=case when required_action in('rebuild_before_publication','rebuild_during_publication') then 'completed' when required_action in('ephemeral_no_action','unaffected') then 'not_required' when required_action='external_sync_required' then 'external_pending' else 'failed' end,current_state=case when required_action in('rebuild_before_publication','rebuild_during_publication') then 'generation_advanced' when required_action in('ephemeral_no_action','unaffected') then 'not_required' when required_action='external_sync_required' then 'external_pending' else 'failed' end,rebuilt_at=case when required_action in('rebuild_before_publication','rebuild_during_publication') then at else null end where manifest_id=h.id;
 select count(*) filter(where completion_status='completed'),count(*) filter(where completion_status='not_required'),count(*) filter(where completion_status='external_pending'),count(*) filter(where completion_status='failed') into completed,notreq,externalp,failed from public.season_cache_invalidation_entries where manifest_id=h.id;
 if failed<>0 or completed+notreq+externalp<>registered or exists(select 1 from public.season_cache_invalidation_entries where manifest_id=h.id and completion_status='pending') then raise exception 'context_refresh_publication_entry_incomplete';end if;
 update public.season_cache_invalidation_manifests set status='completed',published_at=at,completed_at=at where id=h.id;
 finalhash:=public.rollover_material_fingerprint(jsonb_build_object('manifest',h.aggregate_manifest_hash,'entries',(select jsonb_agg(jsonb_build_object('code',cache_code,'state',completion_status,'source',source_evidence_hash) order by cache_code) from public.season_cache_invalidation_entries where manifest_id=h.id)));
 context_hash:=public.rollover_material_fingerprint(jsonb_build_object('schema','phase3b13e-publication-context-v1','execution',x.id,'season',sp.publication_fingerprint,'cap',cp.publication_fingerprint,'market',mp.deterministic_fingerprint,'release',cr.release_fingerprint,'manifest',h.aggregate_manifest_hash,'final_entries',finalhash,'generation',gen));fp:=public.rollover_material_fingerprint(jsonb_build_object('context',context_hash,'actor',p_actor,'completed_at',at));
 insert into public.publication_context_generations(rollover_execution_id,league_id,published_season_id,season_publication_id,cap_publication_id,market_publication_id,cutover_release_id,cache_manifest_id,cache_manifest_hash,context_generation,ui_generation,data_generation,session_generation,analytics_generation,ai_context_generation,gm_assistant_generation,publication_context_status,registered_manifest_entry_count,completed_entry_count,not_required_entry_count,external_pending_count,failed_entry_count,remediated_read_path_count,remaining_stale_path_count,aggregate_context_hash,deterministic_fingerprint,idempotency_key,request_fingerprint,completed_by,completed_at,schema_version) values(x.id,x.league_id,t.id,sp.id,cp.id,mp.id,cr.id,h.id,h.aggregate_manifest_hash,gen,gen,gen,gen,gen,gen,gen,'published',registered,completed,notreq,externalp,failed,remediated,stale,context_hash,fp,k,reqfp,p_actor,at,'phase3b13e-publication-context-v1') returning * into g;
 return jsonb_build_object('success',true,'context_generation_id',g.id,'execution_id',x.id,'target_season_id',t.id,'cache_manifest_id',h.id,'registered_manifest_entry_count',registered,'completed_entry_count',completed,'not_required_entry_count',notreq,'external_pending_entry_count',externalp,'failed_entry_count',failed,'ui_generation',gen,'data_generation',gen,'session_generation',gen,'analytics_generation',gen,'ai_context_generation',gen,'gm_assistant_generation',gen,'remediated_read_path_count',remediated,'remaining_stale_path_count',stale,'compatible_replay_count',0,'operation_mutation_count',registered+2,'postcondition_count',16,'aggregate_context_hash',context_hash,'validation_codes',jsonb_build_array('operations_32_35','canonical_season','published_cap','published_market','cutover_released','manifest_hash','publication_entries_completed','external_pending','ui_generation','ai_generation','no_football_mutation'));
end$$;

create function public.refresh_published_ui_and_ai_context_authenticated(p_request jsonb) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$declare actor uuid:=public.require_authenticated_user();begin if p_request?'actor_user_id' or p_request?'completed_by' or p_request?'cache_codes' or p_request?'generations' or p_request?'target_season_id' or p_request?'context_generation' then raise exception 'actor or context material spoofing forbidden';end if;return public.refresh_published_context_phase3b13e_private(p_request,actor);end$$;
revoke all on function public.guard_phase3b13e_context_evidence(),public.refresh_published_context_phase3b13e_private(jsonb,uuid),public.refresh_published_ui_and_ai_context_authenticated(jsonb) from public,anon,authenticated,service_role;grant execute on function public.refresh_published_ui_and_ai_context_authenticated(jsonb) to authenticated;
commit;
