begin;

alter table public.rollover_execution_handler_registry drop constraint rollover_execution_handler_registry_mutation_class_check;
alter table public.rollover_execution_handler_registry add constraint rollover_execution_handler_registry_mutation_class_check check(mutation_class in(
 'read_only','contract_domain','roster_domain','taxi_domain','taxi_eligibility_domain','ir_domain','draft_inventory_domain','rookie_authority_domain','rookie_eligibility_domain','dead_cap_domain','team_cap_domain','free_agent_domain','expiring_contract_domain','standings_domain','matchup_domain','playoff_domain'));
insert into public.rollover_execution_handler_registry(operation_code,operation_order,handler_version,input_schema_version,result_schema_version,execution_owner,mutation_class,metadata)
values('INITIALIZE_TARGET_PLAYOFF_STRUCTURE',28,1,'phase3b11c-playoff-input-v1','phase3b11c-playoff-result-v1','execution','playoff_domain',jsonb_build_object('phase','3B.11C','configuration_source_status','externally_resolved_pending','participant_count',0,'bracket_row_count',0,'qualification_status','pending','publication',false));

do $$declare d text;sig regprocedure;begin foreach sig in array array[
 'public.guard_contract_write_during_rollover()'::regprocedure,
 'public.guard_season_roster_assignment_insert_phase3b8a()'::regprocedure,
 'public.guard_phase3b9a_draft_inventory()'::regprocedure,
 'public.guard_phase3b9b_rookie_authority()'::regprocedure,
 'public.guard_phase3b9c_rookie_eligibility()'::regprocedure]
 loop select pg_get_functiondef(sig) into d;d:=replace(d,'''phase3b11b-v1'')','''phase3b11b-v1'',''phase3b11c-v1'')');execute d;end loop;end$$;

create table public.prepared_target_playoff_structures(
 id uuid primary key default gen_random_uuid(),rollover_execution_id uuid not null unique references public.rollover_executions(id),
 league_id uuid not null references public.leagues(id),target_season_id uuid not null references public.league_seasons(id),
 source_snapshot_hash text not null check(source_snapshot_hash~'^[0-9a-f]{64}$'),prepared_standings_set_id uuid not null references public.prepared_target_standings_sets(id),prepared_standings_hash text not null check(prepared_standings_hash~'^[0-9a-f]{64}$'),
 prepared_matchup_set_id uuid not null references public.prepared_target_matchup_sets(id),prepared_matchup_hash text not null check(prepared_matchup_hash~'^[0-9a-f]{64}$'),
 configuration_source text,configuration_version text,configuration_source_status text not null check(configuration_source_status='externally_resolved_pending'),
 configured_playoff_team_count integer check(configured_playoff_team_count>0),configured_round_count integer check(configured_round_count>0),bye_configuration jsonb,consolation_configuration jsonb,
 participant_count integer not null check(participant_count=0),seed_count integer not null check(seed_count=0),bracket_row_count integer not null check(bracket_row_count=0),result_row_count integer not null check(result_row_count=0),
 qualification_status text not null check(qualification_status='pending'),structure_status text not null check(structure_status='prepared'),published_at timestamptz,
 schema_version text not null check(schema_version='phase3b11c-playoff-v1'),aggregate_structure_hash text not null check(aggregate_structure_hash~'^[0-9a-f]{64}$'),deterministic_fingerprint text not null check(deterministic_fingerprint~'^[0-9a-f]{64}$'),created_at timestamptz not null default clock_timestamp(),
 unique(league_id,target_season_id),check(configuration_source is null and configuration_version is null and configured_playoff_team_count is null and configured_round_count is null and bye_configuration is null and consolation_configuration is null and published_at is null));
alter table public.prepared_target_playoff_structures enable row level security;
revoke all on public.prepared_target_playoff_structures from public,anon,authenticated;
grant select,insert on public.prepared_target_playoff_structures to service_role;
create policy prepared_target_playoff_structure_commissioner_read on public.prepared_target_playoff_structures for select to authenticated using(exists(select 1 from public.league_memberships m where m.league_id=prepared_target_playoff_structures.league_id and m.user_id=auth.uid() and m.role='commissioner'));

create or replace function public.guard_phase3b11c_prepared_playoffs() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
declare lid uuid:=coalesce(new.league_id,old.league_id);begin if tg_op in('UPDATE','DELETE') then raise exception 'prepared_target_playoff_structure_immutable';end if;if public.has_active_rollover_cutover_lock(lid) and coalesce(current_setting('app.rollover_typed_execution',true),'')<>'phase3b11c-v1' then raise exception 'rollover_cutover_playoff_writes_blocked';end if;return new;end$$;
create trigger prepared_target_playoff_structures_guard before insert or update or delete on public.prepared_target_playoff_structures for each row execute function public.guard_phase3b11c_prepared_playoffs();

create or replace function public.guard_phase3b11c_legacy_playoff_writes() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
declare sid uuid:=coalesce(new.league_season_id,old.league_season_id);begin if exists(select 1 from public.league_seasons s join public.rollover_executions x on x.league_id=s.league_id and x.target_season=s.season join public.rollover_execution_locks l on l.rollover_execution_id=x.id where s.id=sid and l.status='active' and l.lock_type='cutover' and l.lock_scope='rollover_global') then raise exception 'rollover_cutover_legacy_playoff_write_blocked';end if;return coalesce(new,old);end$$;
create trigger season_playoff_brackets_cutover_guard before insert on public.season_playoff_brackets for each row execute function public.guard_phase3b11c_legacy_playoff_writes();
create trigger season_playoff_matchups_cutover_guard before insert on public.season_matchups for each row when(new.phase in('playoff','consolation')) execute function public.guard_phase3b11c_legacy_playoff_writes();
create trigger season_standings_playoff_cutover_guard before insert on public.season_standings for each row when(new.playoff_seed is not null or new.final_finish is not null or new.is_champion) execute function public.guard_phase3b11c_legacy_playoff_writes();

create or replace function public.write_prepared_target_playoffs_phase3b11c_private(p_rollover_execution_id uuid,p_execution_plan_id uuid,p_approval_id uuid,p_actor uuid)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare x public.rollover_executions%rowtype;target public.league_seasons%rowtype;snap public.rollover_execution_input_snapshots%rowtype;standings public.prepared_target_standings_sets%rowtype;matchups public.prepared_target_matchup_sets%rowtype;existing public.prepared_target_playoff_structures%rowtype;aggregatehash text;fingerprint text;
begin
 if p_actor is null then perform public.raise_phase3b6c1_failure('playoff_authenticated_actor_required','{}');end if;
 select * into x from public.rollover_executions where id=p_rollover_execution_id;
 select * into target from public.league_seasons where league_id=x.league_id and season=x.target_season for share;
 if target.id is null then perform public.raise_phase3b6c1_failure('playoff_target_season_missing','{}');end if;
 if target.league_id<>x.league_id or target.is_active or target.status<>'scheduled' then perform public.raise_phase3b6c1_failure('playoff_target_season_cross_league','{}');end if;
 if not exists(select 1 from public.rollover_execution_locks l where l.rollover_execution_id=x.id and l.execution_plan_id=p_execution_plan_id and l.approval_id=p_approval_id and l.status='active' and l.lock_type='cutover' and l.lock_scope='rollover_global' for update) then perform public.raise_phase3b6c1_failure('playoff_cutover_lock_missing','{}');end if;
 select * into snap from public.rollover_execution_input_snapshots where rollover_execution_id=x.id and execution_plan_id=p_execution_plan_id and approval_id=p_approval_id for share;
 if snap.id is null or snap.league_id<>x.league_id then perform public.raise_phase3b6c1_failure('playoff_source_hash_mismatch','{}');end if;
 select * into standings from public.prepared_target_standings_sets where rollover_execution_id=x.id for share;
 if standings.id is null then perform public.raise_phase3b6c1_failure('playoff_standings_set_missing','{}');end if;
 if standings.league_id<>x.league_id or standings.target_season_id<>target.id or standings.source_snapshot_hash<>snap.aggregate_snapshot_fingerprint or standings.status<>'prepared' or standings.published_at is not null or(select count(*) from public.prepared_target_standings where standings_set_id=standings.id)<>standings.expected_team_count then perform public.raise_phase3b6c1_failure('playoff_standings_set_incomplete','{}');end if;
 select * into matchups from public.prepared_target_matchup_sets where rollover_execution_id=x.id for share;
 if matchups.id is null then perform public.raise_phase3b6c1_failure('playoff_matchup_header_missing','{}');end if;
 if matchups.league_id<>x.league_id or matchups.target_season_id<>target.id or matchups.source_snapshot_hash<>snap.aggregate_snapshot_fingerprint or matchups.prepared_standings_hash<>standings.aggregate_standings_hash then perform public.raise_phase3b6c1_failure('playoff_source_hash_mismatch','{}');end if;
 if matchups.expected_matchup_count<>0 or matchups.actual_matchup_count<>0 or matchups.status<>'prepared_empty' or matchups.published_at is not null or exists(select 1 from public.season_matchups where league_season_id=target.id) then perform public.raise_phase3b6c1_failure('playoff_matchup_state_not_empty','{}');end if;
 if exists(select 1 from public.season_playoff_brackets where league_season_id=target.id) then perform public.raise_phase3b6c1_failure('playoff_bracket_rows_present','{}');end if;
 if exists(select 1 from public.season_standings where league_season_id=target.id and(playoff_seed is not null or final_finish is not null or is_champion)) then perform public.raise_phase3b6c1_failure('playoff_population_not_empty','{}');end if;
 perform 1 from public.prepared_target_playoff_structures where rollover_execution_id=x.id for update;
 aggregatehash:=public.rollover_material_fingerprint(jsonb_build_object('schema','phase3b11c-playoff-empty-v1','execution',x.id,'league',x.league_id,'target_season',target.id,'snapshot',snap.aggregate_snapshot_fingerprint,'standings_hash',standings.aggregate_standings_hash,'matchup_hash',matchups.aggregate_matchup_hash,'configuration','externally_resolved_pending','participants','[]'::jsonb,'seeds','[]'::jsonb,'brackets','[]'::jsonb,'results','[]'::jsonb,'qualification','pending'));
 fingerprint:=public.rollover_material_fingerprint(jsonb_build_object('schema','phase3b11c-playoff-structure-v1','aggregate_hash',aggregatehash,'counts',jsonb_build_array(0,0,0,0),'status','prepared','published',false));
 select * into existing from public.prepared_target_playoff_structures where league_id=x.league_id and target_season_id=target.id for update;
 if found then if existing.rollover_execution_id<>x.id or existing.source_snapshot_hash<>snap.aggregate_snapshot_fingerprint or existing.prepared_standings_hash<>standings.aggregate_standings_hash or existing.prepared_matchup_hash<>matchups.aggregate_matchup_hash or existing.aggregate_structure_hash<>aggregatehash or existing.deterministic_fingerprint<>fingerprint or existing.participant_count<>0 or existing.seed_count<>0 or existing.bracket_row_count<>0 or existing.result_row_count<>0 then perform public.raise_phase3b6c1_failure('playoff_structure_conflict','{}');end if;return jsonb_build_object('prepared_structure_count',1,'participant_count',0,'seed_count',0,'bracket_row_count',0,'result_row_count',0,'configuration_source_status','externally_resolved_pending','configured_playoff_team_count',null,'configured_round_count',null,'qualification_pending_count',1,'compatible_replay_count',1,'conflict_count',0,'mutation_count',0,'postcondition_count',13,'aggregate_structure_hash',aggregatehash,'validation_codes',jsonb_build_array('target_scheduled','standings_complete','matchups_empty','configuration_pending','participants_empty','seeds_empty','brackets_empty','results_empty','qualification_pending','unpublished','source_hashes','cutover_lock')) ;end if;
 perform set_config('app.rollover_typed_execution','phase3b11c-v1',true);
 insert into public.prepared_target_playoff_structures(rollover_execution_id,league_id,target_season_id,source_snapshot_hash,prepared_standings_set_id,prepared_standings_hash,prepared_matchup_set_id,prepared_matchup_hash,configuration_source_status,participant_count,seed_count,bracket_row_count,result_row_count,qualification_status,structure_status,schema_version,aggregate_structure_hash,deterministic_fingerprint)
 values(x.id,x.league_id,target.id,snap.aggregate_snapshot_fingerprint,standings.id,standings.aggregate_standings_hash,matchups.id,matchups.aggregate_matchup_hash,'externally_resolved_pending',0,0,0,0,'pending','prepared','phase3b11c-playoff-v1',aggregatehash,fingerprint) returning * into existing;
 return jsonb_build_object('prepared_structure_count',1,'participant_count',0,'seed_count',0,'bracket_row_count',0,'result_row_count',0,'configuration_source_status','externally_resolved_pending','configured_playoff_team_count',null,'configured_round_count',null,'qualification_pending_count',1,'compatible_replay_count',0,'conflict_count',0,'mutation_count',1,'postcondition_count',13,'aggregate_structure_hash',aggregatehash,'validation_codes',jsonb_build_array('target_scheduled','standings_complete','matchups_empty','configuration_pending','participants_empty','seeds_empty','brackets_empty','results_empty','qualification_pending','unpublished','source_hashes','cutover_lock'));
end$$;

create or replace function public.execute_rollover_typed_handler_phase3b11c_private(p_operation jsonb,p_rollover_execution_id uuid,p_execution_plan_id uuid,p_approval_id uuid,p_actor uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$declare code text:=p_operation->>'operation_type';result jsonb;begin if code<>'INITIALIZE_TARGET_PLAYOFF_STRUCTURE' then return public.execute_rollover_typed_handler_phase3b11b_private(p_operation,p_rollover_execution_id,p_execution_plan_id,p_approval_id,p_actor);end if;if(p_operation->>'operation_index')::int<>28 then perform public.raise_phase3b6c1_failure('unsupported_handler_version','{}');end if;result:=public.write_prepared_target_playoffs_phase3b11c_private(p_rollover_execution_id,p_execution_plan_id,p_approval_id,p_actor);return jsonb_build_object('operation_code',code,'handler_version',1,'result',result||jsonb_build_object('operation_mutation_count',(result->>'mutation_count')::int));end$$;
do $$declare d text;begin select pg_get_functiondef('public.execute_rollover_plan_phase3b11b_private(jsonb,uuid)'::regprocedure) into d;d:=replace(d,'execute_rollover_plan_phase3b11b_private','execute_rollover_plan_phase3b11c_private');d:=replace(d,'execute_rollover_typed_handler_phase3b11b_private','execute_rollover_typed_handler_phase3b11c_private');d:=replace(d,'''INITIALIZE_TARGET_MATCHUPS'')','''INITIALIZE_TARGET_MATCHUPS'',''INITIALIZE_TARGET_PLAYOFF_STRUCTURE'')');d:=replace(d,'Phase 3B.11B','Phase 3B.11C');d:=replace(d,'phase3b11b-v1','phase3b11c-v1');execute d;end$$;
create or replace function public.execute_rollover_plan_authenticated(p_request jsonb) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$declare actor uuid:=public.require_authenticated_user();x public.rollover_executions%rowtype;begin if p_request?'actor_user_id' or p_request?'executed_by' or p_request?'playoffs' or p_request?'participants' or p_request?'teams' or p_request?'seeds' or p_request?'brackets' or p_request?'winners' or p_request?'losers' or p_request?'configuration' then raise exception 'actor or playoff material spoofing forbidden';end if;select * into x from public.rollover_executions where id=(p_request->>'rollover_execution_id')::uuid;if x.id is null then raise exception 'execution not found';end if;perform public.require_commissioner_authority(x.league_id);return public.execute_rollover_plan_phase3b11c_private(p_request,actor);end$$;
revoke all on function public.write_prepared_target_playoffs_phase3b11c_private(uuid,uuid,uuid,uuid),public.execute_rollover_typed_handler_phase3b11c_private(jsonb,uuid,uuid,uuid,uuid),public.execute_rollover_plan_phase3b11c_private(jsonb,uuid),public.guard_phase3b11c_prepared_playoffs(),public.guard_phase3b11c_legacy_playoff_writes() from public,anon,authenticated,service_role;
revoke all on function public.execute_rollover_plan_authenticated(jsonb) from public,anon,authenticated,service_role;grant execute on function public.execute_rollover_plan_authenticated(jsonb) to authenticated;
commit;
