create or replace function public.read_canonical_team_state_authenticated(p_request jsonb)
returns jsonb language plpgsql stable security definer set search_path=pg_catalog,public as $$
declare v_actor uuid:=public.require_authenticated_user();v_league uuid;v_season int;v_requested uuid;v_member public.league_memberships%rowtype;v_scope uuid;
begin
 if p_request is null or jsonb_typeof(p_request)<>'object' or p_request?|array['actor_user_id','user_id','role'] then raise exception 'team_state_request_invalid';end if;
 begin v_league:=(p_request->>'league_id')::uuid;v_season:=(p_request->>'season')::int;v_requested:=nullif(p_request->>'league_team_id','')::uuid;exception when others then raise exception 'team_state_request_invalid';end;
 if v_league is null or v_season not between 1900 and 9999 then raise exception 'team_state_request_invalid';end if;
 select * into strict v_member from public.league_memberships where league_id=v_league and user_id=v_actor;
 if v_member.role='commissioner' then v_scope:=v_requested;else
  if v_member.league_team_id is null then raise exception 'team_state_team_assignment_required';end if;
  if v_requested is not null and v_requested<>v_member.league_team_id then raise exception 'team_state_cross_team_forbidden';end if;v_scope:=v_member.league_team_id;
 end if;
 if v_scope is not null and not exists(select 1 from public.league_teams where id=v_scope and league_id=v_league) then raise exception 'team_state_team_not_in_league';end if;
 return jsonb_build_object('schema','canonical-team-state-v1','league_id',v_league,'season',v_season,'scope_team_id',v_scope,
 'teams',coalesce((select jsonb_agg(to_jsonb(x) order by owner_name) from(select id::text league_team_id,owner_name,coalesce(nullif(team_name,''),owner_name) team_name from public.league_teams where league_id=v_league and(v_scope is null or id=v_scope))x),'[]'::jsonb),
 'roster',coalesce((select jsonb_agg(to_jsonb(x) order by owner_name,pos,player_name) from(select ca.id::text contract_agreement_id,ca.league_id::text league_id,ca.league_team_id::text league_team_id,ca.player_id,ca.sleeper_player_id,coalesce(pu.player_name,ca.sleeper_player_id)player_name,coalesce(pu.pos,'')pos,lt.owner_name,coalesce(nullif(lt.team_name,''),lt.owner_name)team_name,cs.salary,cs.cap_hit,ca.contract_type,ca.status,v_season season,(select count(*)::int from public.contract_seasons y where y.contract_id=ca.id and y.season>=v_season and y.obligation_status in('active','scheduled'))contract_years_left from public.contract_agreements ca join public.contract_seasons cs on cs.contract_id=ca.id and cs.season=v_season and cs.obligation_status in('active','scheduled') join public.league_teams lt on lt.id=ca.league_team_id and lt.league_id=ca.league_id left join public.player_universe pu on pu.sleeper_id=ca.sleeper_player_id where ca.league_id=v_league and ca.status in('active','scheduled') and ca.superseded_by_contract_id is null and(v_scope is null or ca.league_team_id=v_scope))x),'[]'::jsonb),
 'dead_cap',coalesce((select jsonb_agg(to_jsonb(x) order by owner_name,player_name) from(select d.id::text id,d.league_id::text league_id,d.league_team_id::text league_team_id,d.player_id,coalesce(pu.player_name,d.player_id,'Player')player_name,lt.owner_name,coalesce(nullif(lt.team_name,''),lt.owner_name)team_name,d.season,d.amount,'dropped_player_charge'::text adjustment_type from public.dead_cap_obligations d join public.league_teams lt on lt.id=d.league_team_id and lt.league_id=d.league_id left join public.player_universe pu on pu.sleeper_id=d.player_id where d.league_id=v_league and d.season=v_season and d.status='active' and(v_scope is null or d.league_team_id=v_scope))x),'[]'::jsonb),
 'activity',coalesce((select jsonb_agg(to_jsonb(x) order by created_at desc) from(select e.id::text id,e.contract_id::text contract_id,e.league_id::text league_id,e.league_team_id::text league_team_id,e.player_id,coalesce(pu.player_name,e.player_id)player_name,lt.owner_name,coalesce(nullif(lt.team_name,''),lt.owner_name)team_name,case e.event_type when'signed'then'add'else'drop'end action,e.event_type,e.effective_season,e.effective_at,e.created_at,e.idempotency_key from public.contract_events e join public.league_teams lt on lt.id=e.league_team_id and lt.league_id=e.league_id left join public.player_universe pu on pu.sleeper_id=e.player_id where e.league_id=v_league and e.event_type in('signed','released')and(v_scope is null or e.league_team_id=v_scope)order by e.created_at desc limit 500)x),'[]'::jsonb),
 'cap_adjustments',coalesce((select jsonb_agg(to_jsonb(x) order by created_at) from(select a.*,lt.id::text league_team_id,coalesce(nullif(lt.team_name,''),lt.owner_name)team_name from public.cap_adjustments a join public.league_teams lt on lt.league_id=a.league_id and lower(btrim(a.owner_name))in(lower(btrim(lt.owner_name)),lower(btrim(coalesce(lt.team_name,''))))where a.league_id=v_league and a.season=v_season and(v_scope is null or lt.id=v_scope))x),'[]'::jsonb));
exception when no_data_found then raise exception 'team_state_league_membership_required';when too_many_rows then raise exception 'team_state_membership_ambiguous';end$$;
revoke all on function public.read_canonical_team_state_authenticated(jsonb) from public,anon,authenticated,service_role;
grant execute on function public.read_canonical_team_state_authenticated(jsonb) to authenticated;
