begin;
insert into public.rollover_execution_handler_registry(operation_code,operation_order,handler_version,input_schema_version,result_schema_version,execution_owner,mutation_class,metadata) values('ENABLE_TARGET_FREE_AGENT_VISIBILITY',34,1,'phase3b13c-market-visibility-input-v1','phase3b13c-market-visibility-result-v1','publication','free_agent_domain',jsonb_build_object('phase','3B.13C','eligibility_recalculation',false,'holds_released',false,'cutover_lock_release',false,'cache_refresh',false,'external_sync',false));

create table public.rollover_target_market_visibility_publications(
 id uuid primary key default gen_random_uuid(),rollover_execution_id uuid not null unique references public.rollover_executions(id),league_id uuid not null references public.leagues(id),target_season_id uuid not null references public.league_seasons(id),season_publication_id uuid not null unique references public.rollover_target_season_authority_publications(id),cap_publication_id uuid not null unique references public.rollover_target_cap_authority_publications(id),prepared_free_agent_set_id uuid not null unique references public.prepared_free_agent_eligibility_sets(id),prepared_free_agent_set_hash text not null check(prepared_free_agent_set_hash~'^[0-9a-f]{64}$'),prepared_expiring_set_id uuid not null unique references public.prepared_expiring_contract_sets(id),prepared_expiring_set_hash text not null check(prepared_expiring_set_hash~'^[0-9a-f]{64}$'),published_free_agent_count int not null check(published_free_agent_count>=0),published_expiring_contract_count int not null check(published_expiring_contract_count>=0),excluded_hold_count int not null check(excluded_hold_count>=0),excluded_rostered_count int not null check(excluded_rostered_count>=0),excluded_active_contract_count int not null check(excluded_active_contract_count>=0),excluded_released_expiring_count int not null check(excluded_released_expiring_count>=0),excluded_held_expiring_count int not null check(excluded_held_expiring_count>=0),excluded_terminal_expiring_count int not null check(excluded_terminal_expiring_count>=0),aggregate_visibility_hash text not null check(aggregate_visibility_hash~'^[0-9a-f]{64}$'),status text not null check(status='published'),idempotency_key text not null unique,request_fingerprint text not null check(request_fingerprint~'^[0-9a-f]{64}$'),deterministic_fingerprint text not null check(deterministic_fingerprint~'^[0-9a-f]{64}$'),published_by uuid not null references auth.users(id),published_at timestamptz not null default clock_timestamp(),schema_version text not null check(schema_version='phase3b13c-market-visibility-v1')
);
create table public.rollover_target_market_visibility_rows(
 id uuid primary key default gen_random_uuid(),publication_id uuid not null references public.rollover_target_market_visibility_publications(id),league_id uuid not null references public.leagues(id),target_season_id uuid not null references public.league_seasons(id),player_id text not null references public.player_universe(sleeper_id),market_type text not null check(market_type in('free_agent','expiring_contract')),source_prepared_row_id uuid not null,source_prepared_row_hash text not null check(source_prepared_row_hash~'^[0-9a-f]{64}$'),visibility_status text not null check(visibility_status='visible'),effective_at timestamptz not null,deterministic_fingerprint text not null check(deterministic_fingerprint~'^[0-9a-f]{64}$'),unique(publication_id,market_type,source_prepared_row_id)
);
create index rollover_target_market_visibility_lookup_idx on public.rollover_target_market_visibility_rows(league_id,target_season_id,market_type,player_id);
alter table public.rollover_target_market_visibility_publications enable row level security;alter table public.rollover_target_market_visibility_rows enable row level security;
revoke all on public.rollover_target_market_visibility_publications,public.rollover_target_market_visibility_rows from public,anon,authenticated;grant select,insert on public.rollover_target_market_visibility_publications,public.rollover_target_market_visibility_rows to service_role;grant select on public.rollover_target_market_visibility_publications,public.rollover_target_market_visibility_rows to authenticated;
create policy market_visibility_publication_member_read on public.rollover_target_market_visibility_publications for select to authenticated using(exists(select 1 from public.league_memberships m where m.league_id=rollover_target_market_visibility_publications.league_id and m.user_id=auth.uid()));create policy market_visibility_row_member_read on public.rollover_target_market_visibility_rows for select to authenticated using(exists(select 1 from public.league_memberships m where m.league_id=rollover_target_market_visibility_rows.league_id and m.user_id=auth.uid()));
create or replace function public.guard_phase3b13c_market_visibility() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$begin if tg_op in('UPDATE','DELETE') then raise exception 'market_visibility_evidence_immutable';end if;return new;end$$;
create trigger market_visibility_publication_immutable before update or delete on public.rollover_target_market_visibility_publications for each row execute function public.guard_phase3b13c_market_visibility();create trigger market_visibility_rows_immutable before update or delete on public.rollover_target_market_visibility_rows for each row execute function public.guard_phase3b13c_market_visibility();

create or replace function public.enable_target_market_visibility_phase3b13c_private(p_request jsonb,p_actor uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare x public.rollover_executions%rowtype;f public.rollover_executed_unpublished_finalizations%rowtype;vr public.rollover_post_execution_validation_reports%rowtype;sp public.rollover_target_season_authority_publications%rowtype;cp public.rollover_target_cap_authority_publications%rowtype;l public.rollover_execution_locks%rowtype;t public.league_seasons%rowtype;fa public.prepared_free_agent_eligibility_sets%rowtype;ex public.prepared_expiring_contract_sets%rowtype;prior public.rollover_target_market_visibility_publications%rowtype;pub public.rollover_target_market_visibility_publications%rowtype;k text:=nullif(btrim(p_request->>'idempotency_key'),'');reqfp text;fahash text;exhash text;aggregatehash text;fingerprint text;nowat timestamptz:=clock_timestamp();fac int;exc int;held int;rostered int;activec int;releasedx int;heldx int;terminalx int;writtenfa int:=0;writtenex int:=0;r record;rowfp text;
begin
 if p_actor is null or k is null then raise exception 'market_visibility_execution_missing';end if;if nullif(p_request->>'rollover_execution_id','') is null or nullif(p_request->>'season_publication_id','') is null or nullif(p_request->>'cap_publication_id','') is null or nullif(p_request->>'expected_season_publication_fingerprint','') is null or nullif(p_request->>'expected_cap_publication_fingerprint','') is null or nullif(p_request->>'expected_free_agent_set_hash','') is null or nullif(p_request->>'expected_expiring_set_hash','') is null then raise exception 'market_visibility complete assertions required';end if;
 perform pg_advisory_xact_lock(hashtextextended('phase3b13c:'||(p_request->>'rollover_execution_id'),0));select * into x from public.rollover_executions where id=(p_request->>'rollover_execution_id')::uuid for update;if x.id is null then raise exception 'market_visibility_execution_missing';end if;if x.status<>'executed_unpublished' then raise exception 'market_visibility_execution_state_invalid';end if;perform public.require_commissioner_authority(x.league_id);
 reqfp:=public.rollover_material_fingerprint(jsonb_build_object('operation','ENABLE_TARGET_FREE_AGENT_VISIBILITY','execution',x.id,'league',x.league_id,'request',p_request-'idempotency_key','actor',p_actor));select * into prior from public.rollover_target_market_visibility_publications where rollover_execution_id=x.id for share;if found then if prior.idempotency_key<>k or prior.request_fingerprint<>reqfp or prior.prepared_free_agent_set_hash<>p_request->>'expected_free_agent_set_hash' or prior.prepared_expiring_set_hash<>p_request->>'expected_expiring_set_hash' then raise exception 'market_visibility_already_applied_conflict';end if;return jsonb_build_object('execution_id',x.id,'publication_id',prior.id,'target_season_id',prior.target_season_id,'published_free_agent_count',prior.published_free_agent_count,'published_expiring_contract_count',prior.published_expiring_contract_count,'aggregate_visibility_hash',prior.aggregate_visibility_hash,'compatible_replay_count',1,'operation_mutation_count',0,'postcondition_count',12,'validation_codes',jsonb_build_array('replay','season','cap','eligibility','holds','lock'));end if;
 select * into sp from public.rollover_target_season_authority_publications where id=(p_request->>'season_publication_id')::uuid and rollover_execution_id=x.id for share;if sp.id is null or sp.publication_fingerprint<>p_request->>'expected_season_publication_fingerprint' then raise exception 'market_visibility_season_publication_missing';end if;select * into cp from public.rollover_target_cap_authority_publications where id=(p_request->>'cap_publication_id')::uuid and rollover_execution_id=x.id and season_publication_id=sp.id for share;if cp.id is null or cp.publication_fingerprint<>p_request->>'expected_cap_publication_fingerprint' then raise exception 'market_visibility_cap_authority_inactive';end if;
 select * into f from public.rollover_executed_unpublished_finalizations where id=sp.finalization_id for share;select * into vr from public.rollover_post_execution_validation_reports where id=f.validation_report_id for share;if f.id is null or vr.id is null or not f.publication_eligible or not vr.publication_eligible then raise exception 'market_visibility_not_publication_eligible';end if;if f.publication_blocker_count<>0 or vr.publication_blocker_count<>0 or vr.execution_failure_count<>0 then raise exception 'market_visibility_blockers_present';end if;
 select * into l from public.rollover_execution_locks where id=sp.cutover_lock_id and status='active' and lock_type='cutover' and lock_scope='rollover_global' for update;if l.id is null then raise exception 'market_visibility_cutover_lock_missing';end if;select * into t from public.league_seasons where id=sp.target_season_id and is_active and status='active' for share;if t.id is null then raise exception 'market_visibility_execution_state_invalid';end if;
 select * into fa from public.prepared_free_agent_eligibility_sets where rollover_execution_id=x.id and league_id=x.league_id and target_season_id=t.id and status='prepared' and published_at is null for update;if fa.id is null then raise exception 'market_visibility_free_agent_set_missing';end if;perform 1 from public.prepared_free_agent_eligibilities where eligibility_set_id=fa.id order by player_id,id for share;
 fahash:=public.rollover_material_fingerprint(jsonb_build_object('schema','phase3b10c-free-agent-set-v1','execution',x.id,'rows',coalesce((select jsonb_agg(jsonb_build_object('player_id',player_id,'row_hash',deterministic_row_fingerprint) order by player_id) from public.prepared_free_agent_eligibilities where eligibility_set_id=fa.id),'[]')));if fahash<>fa.aggregate_set_hash or fahash<>p_request->>'expected_free_agent_set_hash' or fa.expected_player_count<>(select count(*) from public.prepared_free_agent_eligibilities where eligibility_set_id=fa.id) then raise exception 'market_visibility_free_agent_hash_mismatch';end if;
 select * into ex from public.prepared_expiring_contract_sets where rollover_execution_id=x.id and league_id=x.league_id and target_season_id=t.id and status='prepared' and published_at is null for update;if ex.id is null then raise exception 'market_visibility_expiring_set_missing';end if;perform 1 from public.prepared_expiring_contract_eligibilities where expiring_set_id=ex.id order by expiry_season,canonical_league_team_id,player_id,contract_agreement_id,id for share;
 exhash:=public.rollover_material_fingerprint(jsonb_build_object('schema','phase3b10d-expiring-set-v1','execution',x.id,'horizon_start',ex.horizon_start_season,'horizon_end',ex.horizon_end_season,'rows',coalesce((select jsonb_agg(jsonb_build_object('expiry',expiry_season,'team',canonical_league_team_id,'player',player_id,'agreement',contract_agreement_id,'hash',deterministic_row_fingerprint) order by expiry_season,canonical_league_team_id,player_id,contract_agreement_id) from public.prepared_expiring_contract_eligibilities where expiring_set_id=ex.id),'[]')));if exhash<>ex.aggregate_set_hash or exhash<>p_request->>'expected_expiring_set_hash' or ex.expected_row_count<>(select count(*) from public.prepared_expiring_contract_eligibilities where expiring_set_id=ex.id) then raise exception 'market_visibility_expiring_hash_mismatch';end if;
 if fa.aggregate_set_hash<>(select prepared_free_agent_hash from public.season_cache_invalidation_manifests where rollover_execution_id=x.id) or ex.aggregate_set_hash<>(select prepared_expiring_hash from public.season_cache_invalidation_manifests where rollover_execution_id=x.id) or public.phase3b13a_prepared_artifact_hash(x.id)<>f.prepared_artifact_aggregate_hash then raise exception 'market_visibility_hash_mismatch';end if;
 perform 1 from public.rollover_commissioner_holds where rollover_execution_id=x.id order by player_id,id for share;select count(*) into held from public.prepared_free_agent_eligibilities where eligibility_set_id=fa.id and eligibility_status='held_ineligible';select count(*) into rostered from public.prepared_free_agent_eligibilities where eligibility_set_id=fa.id and eligibility_status='rostered_ineligible';select count(*) into activec from public.prepared_free_agent_eligibilities where eligibility_set_id=fa.id and eligibility_status='active_contract_ineligible';select count(*) into releasedx from public.prepared_expiring_contract_eligibilities where expiring_set_id=ex.id and eligibility_status='released_excluded';select count(*) into heldx from public.prepared_expiring_contract_eligibilities where expiring_set_id=ex.id and eligibility_status='commissioner_hold_excluded';select count(*) into terminalx from public.prepared_expiring_contract_eligibilities where expiring_set_id=ex.id and eligibility_status='terminal_or_inactive_excluded';select count(*) into fac from public.prepared_free_agent_eligibilities where eligibility_set_id=fa.id and eligibility_status='prepared_free_agent' and not cap_publication_blocked;select count(*) into exc from public.prepared_expiring_contract_eligibilities where expiring_set_id=ex.id and eligibility_status='prepared_expiring_contract';
 if exists(select 1 from public.prepared_free_agent_eligibilities q where q.eligibility_set_id=fa.id and q.eligibility_status='prepared_free_agent' and(q.commissioner_hold_id is not null or q.target_roster_assignment_id is not null or q.active_target_contract_id is not null or q.cap_publication_blocked or exists(select 1 from public.rollover_commissioner_holds h where h.rollover_execution_id=x.id and h.player_id=q.player_id and h.hold_status='active') or exists(select 1 from public.season_roster_assignments a where a.league_season_id=t.id and a.sleeper_player_id=q.player_id) or exists(select 1 from public.contract_seasons c where c.league_season_id=t.id and c.player_id=q.player_id and c.obligation_status='active'))) then raise exception 'market_visibility_hold_conflict';end if;
 aggregatehash:=public.rollover_material_fingerprint(jsonb_build_object('schema','phase3b13c-market-visibility-v1','execution',x.id,'free_agent_set',fa.aggregate_set_hash,'expiring_set',ex.aggregate_set_hash,'free_agents',(select jsonb_agg(deterministic_row_fingerprint order by player_id) from public.prepared_free_agent_eligibilities where eligibility_set_id=fa.id and eligibility_status='prepared_free_agent' and not cap_publication_blocked),'expiring',(select jsonb_agg(deterministic_row_fingerprint order by expiry_season,canonical_league_team_id,player_id) from public.prepared_expiring_contract_eligibilities where expiring_set_id=ex.id and eligibility_status='prepared_expiring_contract')));fingerprint:=public.rollover_material_fingerprint(jsonb_build_object('aggregate',aggregatehash,'execution',x.id,'season_publication',sp.publication_fingerprint,'cap_publication',cp.publication_fingerprint,'lock',l.id));
 insert into public.rollover_target_market_visibility_publications(rollover_execution_id,league_id,target_season_id,season_publication_id,cap_publication_id,prepared_free_agent_set_id,prepared_free_agent_set_hash,prepared_expiring_set_id,prepared_expiring_set_hash,published_free_agent_count,published_expiring_contract_count,excluded_hold_count,excluded_rostered_count,excluded_active_contract_count,excluded_released_expiring_count,excluded_held_expiring_count,excluded_terminal_expiring_count,aggregate_visibility_hash,status,idempotency_key,request_fingerprint,deterministic_fingerprint,published_by,published_at,schema_version) values(x.id,x.league_id,t.id,sp.id,cp.id,fa.id,fa.aggregate_set_hash,ex.id,ex.aggregate_set_hash,fac,exc,held,rostered,activec,releasedx,heldx,terminalx,aggregatehash,'published',k,reqfp,fingerprint,p_actor,nowat,'phase3b13c-market-visibility-v1') returning * into pub;
 for r in select * from public.prepared_free_agent_eligibilities where eligibility_set_id=fa.id and eligibility_status='prepared_free_agent' and not cap_publication_blocked order by player_id loop rowfp:=public.rollover_material_fingerprint(jsonb_build_object('publication',fingerprint,'market','free_agent','source',r.id,'hash',r.deterministic_row_fingerprint));insert into public.rollover_target_market_visibility_rows(publication_id,league_id,target_season_id,player_id,market_type,source_prepared_row_id,source_prepared_row_hash,visibility_status,effective_at,deterministic_fingerprint) values(pub.id,x.league_id,t.id,r.player_id,'free_agent',r.id,r.deterministic_row_fingerprint,'visible',nowat,rowfp);writtenfa:=writtenfa+1;end loop;
 for r in select * from public.prepared_expiring_contract_eligibilities where expiring_set_id=ex.id and eligibility_status='prepared_expiring_contract' order by expiry_season,canonical_league_team_id,player_id,contract_agreement_id loop rowfp:=public.rollover_material_fingerprint(jsonb_build_object('publication',fingerprint,'market','expiring_contract','source',r.id,'hash',r.deterministic_row_fingerprint));insert into public.rollover_target_market_visibility_rows(publication_id,league_id,target_season_id,player_id,market_type,source_prepared_row_id,source_prepared_row_hash,visibility_status,effective_at,deterministic_fingerprint) values(pub.id,x.league_id,t.id,r.player_id,'expiring_contract',r.id,r.deterministic_row_fingerprint,'visible',nowat,rowfp);writtenex:=writtenex+1;end loop;
 if writtenfa<>fac or writtenex<>exc then raise exception 'market_visibility_population_incomplete';end if;return jsonb_build_object('execution_id',x.id,'publication_id',pub.id,'target_season_id',t.id,'prepared_free_agent_count',fa.expected_player_count,'published_free_agent_count',fac,'held_player_exclusion_count',held,'rostered_player_exclusion_count',rostered,'active_contract_exclusion_count',activec,'prepared_expiring_contract_count',ex.expected_row_count,'published_expiring_contract_count',exc,'released_expiring_exclusion_count',releasedx,'held_expiring_exclusion_count',heldx,'terminal_expiring_exclusion_count',terminalx,'aggregate_visibility_hash',aggregatehash,'compatible_replay_count',0,'operation_mutation_count',1+fac+exc,'postcondition_count',12,'validation_codes',jsonb_build_array('season_published','cap_published','eligible','zero_blockers','cutover_active','free_agent_hash','expiring_hash','holds_hidden','rostered_hidden','contracts_hidden','caches_unchanged','external_sync_pending'));
end$$;
create or replace function public.enable_target_free_agent_visibility_authenticated(p_request jsonb) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$declare actor uuid:=public.require_authenticated_user();begin if p_request?'actor_user_id' or p_request?'published_by' or p_request?'players' or p_request?'statuses' or p_request?'free_agent_set_id' or p_request?'expiring_set_id' or p_request?'visibility_rows' then raise exception 'actor or market visibility material spoofing forbidden';end if;return public.enable_target_market_visibility_phase3b13c_private(p_request,actor);end$$;
revoke all on function public.guard_phase3b13c_market_visibility(),public.enable_target_market_visibility_phase3b13c_private(jsonb,uuid),public.enable_target_free_agent_visibility_authenticated(jsonb) from public,anon,authenticated,service_role;grant execute on function public.enable_target_free_agent_visibility_authenticated(jsonb) to authenticated;
commit;
