begin;
create table if not exists public.rollover_dry_run_simulations(
 id uuid primary key default gen_random_uuid(),rollover_execution_id uuid not null references public.rollover_executions(id),league_id uuid not null references public.leagues(id),source_season integer not null,target_season integer not null,
 simulation_version integer not null check(simulation_version>0),simulator_version text not null,simulation_status text not null check(simulation_status in ('generated','blocked','valid','stale','superseded','cancelled','approved_for_plan')),
 input_fingerprint text not null check(input_fingerprint~'^[0-9a-f]{64}$'),result_fingerprint text not null check(result_fingerprint~'^[0-9a-f]{64}$'),policy_fingerprint text not null check(policy_fingerprint~'^[0-9a-f]{64}$'),owner_population_fingerprint text not null check(owner_population_fingerprint~'^[0-9a-f]{64}$'),commissioner_population_fingerprint text not null check(commissioner_population_fingerprint~'^[0-9a-f]{64}$'),authority_preparation_fingerprint text not null check(authority_preparation_fingerprint~'^[0-9a-f]{64}$'),
 result_payload jsonb not null,blockers jsonb not null default '[]' check(jsonb_typeof(blockers)='array'),warnings jsonb not null default '[]' check(jsonb_typeof(warnings)='array'),valid boolean not null,executable boolean not null,plan_eligible boolean not null,
 generated_by uuid not null references auth.users(id),generated_at timestamptz not null default clock_timestamp(),superseded_at timestamptz,superseded_by uuid references public.rollover_dry_run_simulations(id) deferrable initially deferred,cancelled_at timestamptz,metadata jsonb not null default '{}',created_at timestamptz not null default clock_timestamp(),
 check(target_season=source_season+1),check(not executable or valid),check(not plan_eligible or executable),
 check((simulation_status='superseded')=(superseded_at is not null and superseded_by is not null)),check((simulation_status='cancelled')=(cancelled_at is not null)),
 unique(rollover_execution_id,simulation_version),unique(rollover_execution_id,result_fingerprint));
create unique index if not exists rollover_dry_run_one_current on public.rollover_dry_run_simulations(rollover_execution_id) where simulation_status not in ('superseded','cancelled');
create index if not exists rollover_dry_run_league_boundary on public.rollover_dry_run_simulations(league_id,source_season,target_season);
create or replace function public.enforce_rollover_dry_run_immutability() returns trigger language plpgsql set search_path=pg_catalog,public as $$ begin
 if old.simulation_status in ('superseded','cancelled','approved_for_plan') then raise exception 'terminal simulation immutable';end if;
 if new.id<>old.id or new.rollover_execution_id<>old.rollover_execution_id or new.league_id<>old.league_id or new.source_season<>old.source_season or new.target_season<>old.target_season or new.simulation_version<>old.simulation_version or new.simulator_version<>old.simulator_version or new.input_fingerprint<>old.input_fingerprint or new.result_fingerprint<>old.result_fingerprint or new.result_payload<>old.result_payload or new.blockers<>old.blockers or new.warnings<>old.warnings or new.valid<>old.valid or new.executable<>old.executable or new.plan_eligible<>old.plan_eligible or new.generated_by<>old.generated_by or new.generated_at<>old.generated_at then raise exception 'simulation material immutable';end if;
 if new.simulation_status not in ('superseded','cancelled') then raise exception 'only supersession or cancellation allowed';end if;return new;end $$;
drop trigger if exists rollover_dry_run_immutability on public.rollover_dry_run_simulations;
create trigger rollover_dry_run_immutability before update on public.rollover_dry_run_simulations for each row execute function public.enforce_rollover_dry_run_immutability();
alter table public.rollover_dry_run_simulations enable row level security;
drop policy if exists rollover_dry_run_member_read on public.rollover_dry_run_simulations;
create policy rollover_dry_run_member_read on public.rollover_dry_run_simulations for select to authenticated using(exists(select 1 from public.league_memberships m where m.league_id=rollover_dry_run_simulations.league_id and m.user_id=auth.uid()));
revoke all on public.rollover_dry_run_simulations from public,anon,authenticated;grant select on public.rollover_dry_run_simulations to authenticated;grant select,insert,update on public.rollover_dry_run_simulations to service_role;

create or replace function public.generate_rollover_dry_run_authenticated(p_request jsonb) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare actor uuid;x public.rollover_executions%rowtype;k text;material jsonb;fp text;retry jsonb;result jsonb;sim public.rollover_dry_run_simulations%rowtype;auths jsonb;auth_count integer;
begin actor:=public.require_authenticated_user();if p_request?'actor_user_id' or p_request?'requested_by' then raise exception 'actor spoofing forbidden';end if;k:=nullif(btrim(p_request->>'idempotency_key'),'');if k is null then raise exception 'idempotency_key required';end if;
 select * into x from public.rollover_executions where id=(p_request->>'execution_id')::uuid for update;if x.id is null then raise exception 'execution not found';end if;perform public.require_commissioner_authority(x.league_id);if x.status<>'authority_ready' then raise exception 'execution not ready for dry run';end if;
 perform 1 from public.rollover_authority_preparations a where a.rollover_execution_id=x.id for update;
 select count(*),jsonb_agg(to_jsonb(a) order by a.authority_type) into auth_count,auths from public.rollover_authority_preparations a where a.rollover_execution_id=x.id and a.authority_status='prepared';if auth_count<>3 then raise exception 'three current prepared authorities required';end if;
 if x.policy_fingerprint is distinct from p_request->>'policy_fingerprint' or x.decision_population_fingerprint is distinct from p_request->>'owner_population_fingerprint' then raise exception 'stale policy or owner population';end if;
 if exists(select 1 from jsonb_array_elements(auths) a where a->>'commissioner_population_fingerprint' is distinct from p_request->>'commissioner_population_fingerprint' or a->>'preparation_fingerprint' is distinct from p_request->>'authority_preparation_fingerprint') then raise exception 'stale commissioner or authority preparation';end if;
 if p_request->>'input_fingerprint' !~ '^[0-9a-f]{64}$' or p_request->>'result_fingerprint' !~ '^[0-9a-f]{64}$' or jsonb_typeof(p_request->'result_payload')<>'object' then raise exception 'malformed simulation result';end if;
 material:=jsonb_build_object('operation','dry_run_generate','execution',x.id,'boundary',jsonb_build_array(x.source_season,x.target_season),'policy',p_request->>'policy_fingerprint','owner',p_request->>'owner_population_fingerprint','commissioner',p_request->>'commissioner_population_fingerprint','authorities',auths,'simulator_version',p_request->>'simulator_version','input_fingerprint',p_request->>'input_fingerprint','result_fingerprint',p_request->>'result_fingerprint','result_payload',p_request->'result_payload','material_metadata',coalesce(p_request->'material_metadata','{}'),'actor',actor);fp:=public.rollover_material_fingerprint(material);retry:=public.rollover_operation_retry(x.league_id,'dry_run_generate',k,fp);if retry is not null then return retry;end if;
 if exists(select 1 from public.rollover_dry_run_simulations s where s.rollover_execution_id=x.id and s.simulation_status not in ('superseded','cancelled')) then raise exception 'current simulation already exists';end if;
 insert into public.rollover_dry_run_simulations(rollover_execution_id,league_id,source_season,target_season,simulation_version,simulator_version,simulation_status,input_fingerprint,result_fingerprint,policy_fingerprint,owner_population_fingerprint,commissioner_population_fingerprint,authority_preparation_fingerprint,result_payload,blockers,warnings,valid,executable,plan_eligible,generated_by,metadata)
 values(x.id,x.league_id,x.source_season,x.target_season,coalesce((p_request->>'simulation_version')::integer,1),p_request->>'simulator_version',case when jsonb_array_length(coalesce(p_request->'blockers','[]'))>0 then 'blocked' else 'valid' end,p_request->>'input_fingerprint',p_request->>'result_fingerprint',p_request->>'policy_fingerprint',p_request->>'owner_population_fingerprint',p_request->>'commissioner_population_fingerprint',p_request->>'authority_preparation_fingerprint',p_request->'result_payload',coalesce(p_request->'blockers','[]'),coalesce(p_request->'warnings','[]'),coalesce((p_request->>'valid')::boolean,false),coalesce((p_request->>'executable')::boolean,false),coalesce((p_request->>'plan_eligible')::boolean,false),actor,coalesce(p_request->'material_metadata','{}')) returning * into sim;
 result:=jsonb_build_object('operation','dry_run_generate','simulation',to_jsonb(sim));return public.record_rollover_operation(x.league_id,x.id,'dry_run_generate',k,fp,actor,'authenticated_commissioner',sim.id,result,'{}');end $$;

create or replace function public.supersede_rollover_dry_run_authenticated(p_request jsonb) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare actor uuid;s public.rollover_dry_run_simulations%rowtype;r public.rollover_dry_run_simulations%rowtype;x public.rollover_executions%rowtype;k text;material jsonb;fp text;retry jsonb;result jsonb;newid uuid:=gen_random_uuid();
begin actor:=public.require_authenticated_user();if p_request?'actor_user_id' then raise exception 'actor spoofing forbidden';end if;k:=nullif(btrim(p_request->>'idempotency_key'),'');if k is null or nullif(btrim(p_request->>'reason'),'') is null then raise exception 'reason and idempotency_key required';end if;select * into s from public.rollover_dry_run_simulations where id=(p_request->>'simulation_id')::uuid for update;if s.id is null then raise exception 'simulation not found';end if;select * into x from public.rollover_executions where id=s.rollover_execution_id for update;perform public.require_commissioner_authority(x.league_id);if exists(select 1 from public.rollover_execution_locks l where l.rollover_execution_id=x.id and l.status='active') then raise exception 'active lock blocks supersession';end if;
 material:=jsonb_build_object('operation','dry_run_supersede','simulation',s.id,'version',p_request->>'expected_version','input',p_request->>'expected_input_fingerprint','result',p_request->>'expected_result_fingerprint','replacement',p_request->'replacement','reason',p_request->>'reason','actor',actor);fp:=public.rollover_material_fingerprint(material);retry:=public.rollover_operation_retry(x.league_id,'dry_run_supersede',k,fp);if retry is not null then return retry;end if;if s.simulation_version<>(p_request->>'expected_version')::integer or s.input_fingerprint is distinct from p_request->>'expected_input_fingerprint' or s.result_fingerprint is distinct from p_request->>'expected_result_fingerprint' or s.simulation_status in ('superseded','cancelled','approved_for_plan') then raise exception 'stale simulation';end if;
 if jsonb_typeof(p_request->'replacement'->'result_payload')<>'object' then raise exception 'replacement simulation required';end if;
 update public.rollover_dry_run_simulations set simulation_status='superseded',superseded_at=clock_timestamp(),superseded_by=newid where id=s.id;
 insert into public.rollover_dry_run_simulations(id,rollover_execution_id,league_id,source_season,target_season,simulation_version,simulator_version,simulation_status,input_fingerprint,result_fingerprint,policy_fingerprint,owner_population_fingerprint,commissioner_population_fingerprint,authority_preparation_fingerprint,result_payload,blockers,warnings,valid,executable,plan_eligible,generated_by,metadata)
 values(newid,s.rollover_execution_id,s.league_id,s.source_season,s.target_season,s.simulation_version+1,p_request->'replacement'->>'simulator_version',case when jsonb_array_length(coalesce(p_request->'replacement'->'blockers','[]'))>0 then 'blocked' else 'valid' end,p_request->'replacement'->>'input_fingerprint',p_request->'replacement'->>'result_fingerprint',s.policy_fingerprint,s.owner_population_fingerprint,s.commissioner_population_fingerprint,p_request->'replacement'->>'authority_preparation_fingerprint',p_request->'replacement'->'result_payload',coalesce(p_request->'replacement'->'blockers','[]'),coalesce(p_request->'replacement'->'warnings','[]'),coalesce((p_request->'replacement'->>'valid')::boolean,false),coalesce((p_request->'replacement'->>'executable')::boolean,false),coalesce((p_request->'replacement'->>'plan_eligible')::boolean,false),actor,coalesce(p_request->'replacement'->'metadata','{}')) returning * into r;
 result:=jsonb_build_object('operation','dry_run_supersede','simulation',to_jsonb(r),'superseded_simulation_id',s.id);return public.record_rollover_operation(x.league_id,x.id,'dry_run_supersede',k,fp,actor,'authenticated_commissioner',r.id,result,'{}');end $$;

create or replace function public.cancel_rollover_dry_run_authenticated(p_request jsonb) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare actor uuid;s public.rollover_dry_run_simulations%rowtype;x public.rollover_executions%rowtype;k text;material jsonb;fp text;retry jsonb;result jsonb;
begin actor:=public.require_authenticated_user();if p_request?'actor_user_id' then raise exception 'actor spoofing forbidden';end if;k:=nullif(btrim(p_request->>'idempotency_key'),'');if k is null or nullif(btrim(p_request->>'reason'),'') is null then raise exception 'reason and idempotency_key required';end if;select * into s from public.rollover_dry_run_simulations where id=(p_request->>'simulation_id')::uuid for update;if s.id is null then raise exception 'simulation not found';end if;select * into x from public.rollover_executions where id=s.rollover_execution_id for update;perform public.require_commissioner_authority(x.league_id);if exists(select 1 from public.rollover_execution_locks l where l.rollover_execution_id=x.id and l.status='active') then raise exception 'active lock blocks cancellation';end if;
 material:=jsonb_build_object('operation','dry_run_cancel','simulation',s.id,'version',p_request->>'expected_version','input',p_request->>'expected_input_fingerprint','result',p_request->>'expected_result_fingerprint','reason',p_request->>'reason','actor',actor);fp:=public.rollover_material_fingerprint(material);retry:=public.rollover_operation_retry(x.league_id,'dry_run_cancel',k,fp);if retry is not null then return retry;end if;if s.simulation_version<>(p_request->>'expected_version')::integer or s.input_fingerprint is distinct from p_request->>'expected_input_fingerprint' or s.result_fingerprint is distinct from p_request->>'expected_result_fingerprint' or s.simulation_status in ('superseded','cancelled','approved_for_plan') then raise exception 'stale simulation';end if;update public.rollover_dry_run_simulations set simulation_status='cancelled',cancelled_at=clock_timestamp() where id=s.id returning * into s;result:=jsonb_build_object('operation','dry_run_cancel','simulation',to_jsonb(s));return public.record_rollover_operation(x.league_id,x.id,'dry_run_cancel',k,fp,actor,'authenticated_commissioner',s.id,result,'{}');end $$;

revoke all on function public.generate_rollover_dry_run_authenticated(jsonb),public.supersede_rollover_dry_run_authenticated(jsonb),public.cancel_rollover_dry_run_authenticated(jsonb) from public,anon,authenticated,service_role;grant execute on function public.generate_rollover_dry_run_authenticated(jsonb),public.supersede_rollover_dry_run_authenticated(jsonb),public.cancel_rollover_dry_run_authenticated(jsonb) to authenticated;grant execute on function public.generate_rollover_dry_run_authenticated(jsonb),public.supersede_rollover_dry_run_authenticated(jsonb),public.cancel_rollover_dry_run_authenticated(jsonb) to service_role;
commit;
