begin;

alter table public.rollover_execution_handler_registry drop constraint rollover_execution_handler_registry_mutation_class_check;
alter table public.rollover_execution_handler_registry add constraint rollover_execution_handler_registry_mutation_class_check
check(mutation_class in('read_only','contract_domain','roster_domain','taxi_domain','taxi_eligibility_domain','ir_domain','draft_inventory_domain','rookie_authority_domain','rookie_eligibility_domain','dead_cap_domain','team_cap_domain','free_agent_domain','expiring_contract_domain'));
insert into public.rollover_execution_handler_registry(operation_code,operation_order,handler_version,input_schema_version,result_schema_version,execution_owner,mutation_class,metadata)
values('RECONCILE_EXPIRING_CONTRACT_ELIGIBILITY',25,1,'phase3b10d-expiring-input-v1','phase3b10d-expiring-result-v1','execution','expiring_contract_domain',jsonb_build_object('phase','3B.10D','horizon_length',4,'publication',false,'external_calls',false));

do $$declare d text;sig regprocedure;begin foreach sig in array array[
 'public.guard_contract_write_during_rollover()'::regprocedure,
 'public.guard_season_roster_assignment_insert_phase3b8a()'::regprocedure,
 'public.guard_phase3b9a_draft_inventory()'::regprocedure,
 'public.guard_phase3b9b_rookie_authority()'::regprocedure,
 'public.guard_phase3b9c_rookie_eligibility()'::regprocedure]
 loop select pg_get_functiondef(sig) into d;d:=replace(d,'''phase3b10c-v1'')','''phase3b10c-v1'',''phase3b10d-v1'')');execute d;end loop;end$$;

create table public.prepared_expiring_contract_sets(
 id uuid primary key default gen_random_uuid(),rollover_execution_id uuid not null unique references public.rollover_executions(id),
 league_id uuid not null references public.leagues(id),target_season_id uuid not null references public.league_seasons(id),
 source_snapshot_hash text not null check(source_snapshot_hash~'^[0-9a-f]{64}$'),contract_evidence_hash text not null check(contract_evidence_hash~'^[0-9a-f]{64}$'),
 release_evidence_hash text not null check(release_evidence_hash~'^[0-9a-f]{64}$'),commissioner_hold_evidence_hash text not null check(commissioner_hold_evidence_hash~'^[0-9a-f]{64}$'),
 target_roster_set_hash text not null check(target_roster_set_hash~'^[0-9a-f]{64}$'),free_agent_set_hash text not null check(free_agent_set_hash~'^[0-9a-f]{64}$'),
 visible_horizon_length integer not null check(visible_horizon_length=4),horizon_start_season integer not null,horizon_end_season integer not null,
 expected_row_count integer not null check(expected_row_count>=0),aggregate_set_hash text not null check(aggregate_set_hash~'^[0-9a-f]{64}$'),
 status text not null check(status='prepared'),published_at timestamptz,schema_version text not null check(schema_version='phase3b10d-expiring-v1'),
 created_at timestamptz not null default clock_timestamp(),unique(league_id,target_season_id),
 check(horizon_end_season=horizon_start_season+3),check(published_at is null));

create table public.prepared_expiring_contract_eligibilities(
 id uuid primary key default gen_random_uuid(),expiring_set_id uuid not null references public.prepared_expiring_contract_sets(id),
 league_id uuid not null references public.leagues(id),target_season_id uuid not null references public.league_seasons(id),
 contract_agreement_id uuid not null references public.contract_agreements(id),target_contract_season_id uuid not null references public.contract_seasons(id),
 player_id text not null references public.player_universe(sleeper_id),canonical_league_team_id uuid not null references public.league_teams(id),
 eligibility_status text not null check(eligibility_status in('prepared_expiring_contract','active_beyond_horizon','released_excluded','commissioner_hold_excluded','terminal_or_inactive_excluded','conflicting_evidence')),
 eligibility_reason_code text not null,target_contract_status text not null,contract_season_ordinal integer not null,
 years_remaining integer not null,expiry_season integer not null,years_until_expiry integer not null,
 in_visible_horizon boolean not null,release_id uuid references public.rollover_contract_releases(id),commissioner_hold_id uuid references public.rollover_commissioner_holds(id),
 source_snapshot_hash text not null check(source_snapshot_hash~'^[0-9a-f]{64}$'),contract_evidence_hash text not null check(contract_evidence_hash~'^[0-9a-f]{64}$'),
 release_evidence_hash text not null check(release_evidence_hash~'^[0-9a-f]{64}$'),hold_evidence_hash text not null check(hold_evidence_hash~'^[0-9a-f]{64}$'),
 roster_evidence_hash text not null check(roster_evidence_hash~'^[0-9a-f]{64}$'),free_agent_evidence_hash text not null check(free_agent_evidence_hash~'^[0-9a-f]{64}$'),
 deterministic_row_fingerprint text not null check(deterministic_row_fingerprint~'^[0-9a-f]{64}$'),created_at timestamptz not null default clock_timestamp(),
 unique(expiring_set_id,contract_agreement_id),check(contract_season_ordinal>=1),check(years_remaining>=0));

alter table public.prepared_expiring_contract_eligibilities add constraint prepared_expiring_horizon_status_check check(
 (eligibility_status='prepared_expiring_contract' and in_visible_horizon)
 or(eligibility_status='active_beyond_horizon' and not in_visible_horizon)
 or eligibility_status in('released_excluded','commissioner_hold_excluded','terminal_or_inactive_excluded','conflicting_evidence'));
create index prepared_expiring_contract_order_idx on public.prepared_expiring_contract_eligibilities(league_id,target_season_id,expiry_season,canonical_league_team_id,player_id,contract_agreement_id);

alter table public.prepared_expiring_contract_sets enable row level security;alter table public.prepared_expiring_contract_eligibilities enable row level security;
revoke all on public.prepared_expiring_contract_sets,public.prepared_expiring_contract_eligibilities from public,anon,authenticated;
grant select,insert on public.prepared_expiring_contract_sets,public.prepared_expiring_contract_eligibilities to service_role;
create policy prepared_expiring_set_commissioner_read on public.prepared_expiring_contract_sets for select to authenticated using(exists(select 1 from public.league_memberships m where m.league_id=prepared_expiring_contract_sets.league_id and m.user_id=auth.uid() and m.role='commissioner'));
create policy prepared_expiring_row_commissioner_read on public.prepared_expiring_contract_eligibilities for select to authenticated using(exists(select 1 from public.league_memberships m where m.league_id=prepared_expiring_contract_eligibilities.league_id and m.user_id=auth.uid() and m.role='commissioner'));

create or replace function public.guard_phase3b10d_prepared_expiring() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
declare lid uuid:=coalesce(new.league_id,old.league_id);begin
 if tg_op in('UPDATE','DELETE') then raise exception 'prepared_expiring_contract_evidence_immutable';end if;
 if public.has_active_rollover_cutover_lock(lid) and coalesce(current_setting('app.rollover_typed_execution',true),'')<>'phase3b10d-v1' then raise exception 'rollover_cutover_expiring_contract_writes_blocked';end if;return new;end$$;
create trigger prepared_expiring_sets_guard before insert or update or delete on public.prepared_expiring_contract_sets for each row execute function public.guard_phase3b10d_prepared_expiring();
create trigger prepared_expiring_rows_guard before insert or update or delete on public.prepared_expiring_contract_eligibilities for each row execute function public.guard_phase3b10d_prepared_expiring();

create or replace function public.write_prepared_expiring_phase3b10d_private(p_rollover_execution_id uuid,p_execution_plan_id uuid,p_approval_id uuid,p_actor uuid)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare x public.rollover_executions%rowtype;target public.league_seasons%rowtype;snap public.rollover_execution_input_snapshots%rowtype;aset public.rollover_target_roster_assignment_sets%rowtype;
 faset public.prepared_free_agent_eligibility_sets%rowtype;existing public.prepared_expiring_contract_sets%rowtype;r record;state text;reason text;rowhash text;material jsonb:='[]';
 contracthash text;releasehash text;holdhash text;sethash text;expected int:=0;written int:=0;prepared int:=0;beyond int:=0;released int:=0;held int:=0;terminal int:=0;conflicts int:=0;earliest int;
begin
 if p_actor is null then perform public.raise_phase3b6c1_failure('expiring_authenticated_actor_required','{}');end if;
 select * into x from public.rollover_executions where id=p_rollover_execution_id;
 select * into target from public.league_seasons where league_id=x.league_id and season=x.target_season for share;
 if target.id is null then perform public.raise_phase3b6c1_failure('expiring_target_season_missing','{}');end if;
 if target.league_id<>x.league_id then perform public.raise_phase3b6c1_failure('expiring_target_season_cross_league','{}');end if;
 if x.target_season+3-x.target_season+1<>4 then perform public.raise_phase3b6c1_failure('expiring_horizon_invalid','{}');end if;
 if not exists(select 1 from public.rollover_execution_locks l where l.rollover_execution_id=x.id and l.execution_plan_id=p_execution_plan_id and l.approval_id=p_approval_id and l.status='active' and l.lock_type='cutover' and l.lock_scope='rollover_global' for update) then perform public.raise_phase3b6c1_failure('expiring_cutover_lock_missing','{}');end if;
 select * into snap from public.rollover_execution_input_snapshots where rollover_execution_id=x.id and execution_plan_id=p_execution_plan_id and approval_id=p_approval_id for share;
 select * into aset from public.rollover_target_roster_assignment_sets where rollover_execution_id=x.id for share;
 select * into faset from public.prepared_free_agent_eligibility_sets where rollover_execution_id=x.id for share;
 if snap.id is null or aset.id is null or aset.source_snapshot_id<>snap.id or aset.source_snapshot_hash<>snap.aggregate_snapshot_fingerprint or aset.status<>'complete_unpublished' then perform public.raise_phase3b6c1_failure('expiring_source_hash_mismatch','{}');end if;
 if aset.expected_row_count<>(select count(*) from public.season_roster_assignments where assignment_set_id=aset.id) then perform public.raise_phase3b6c1_failure('expiring_contract_population_incomplete','{}');end if;
 if faset.id is null or faset.league_id<>x.league_id or faset.target_season_id<>target.id or faset.source_snapshot_hash<>snap.aggregate_snapshot_fingerprint or faset.status<>'prepared' then perform public.raise_phase3b6c1_failure('expiring_source_hash_mismatch','{}');end if;
 perform 1 from public.contract_agreements where league_id=x.league_id order by id for share;perform 1 from public.contract_seasons where league_season_id=target.id order by contract_id,id for share;
 perform 1 from public.season_roster_assignments where assignment_set_id=aset.id order by contract_agreement_id,id for share;perform 1 from public.rollover_contract_releases where rollover_execution_id=x.id order by contract_agreement_id,id for share;
 perform 1 from public.rollover_commissioner_holds where rollover_execution_id=x.id order by source_contract_agreement_id,id for share;perform 1 from public.prepared_free_agent_eligibilities where eligibility_set_id=faset.id order by player_id,id for share;
 perform 1 from public.prepared_expiring_contract_sets where rollover_execution_id=x.id for update;
 if exists(select 1 from public.contract_seasons cs where cs.league_season_id=target.id group by cs.contract_id having count(*)<>1) then perform public.raise_phase3b6c1_failure('expiring_active_obligation_duplicate','{}');end if;
 if exists(select 1 from public.contract_seasons cs join public.contract_agreements a on a.id=cs.contract_id left join public.league_teams t on t.id=a.league_team_id where cs.league_season_id=target.id and(cs.league_id<>x.league_id or a.league_id<>x.league_id or t.league_id<>x.league_id or cs.player_id<>a.player_id or cs.league_team_id<>a.league_team_id)) then perform public.raise_phase3b6c1_failure('expiring_cross_league_evidence','{}');end if;
 if exists(select 1 from public.contract_agreements a join public.contract_seasons cs on cs.contract_id=a.id and cs.league_season_id=target.id where a.status='active' and cs.obligation_status='active' and(a.end_season<a.start_season or a.end_season<x.target_season)) then perform public.raise_phase3b6c1_failure('expiring_term_invalid','{}');end if;
 if exists(select 1 from public.contract_agreements a join public.contract_seasons cs on cs.contract_id=a.id and cs.league_season_id=target.id left join public.season_roster_assignments ra on ra.assignment_set_id=aset.id and ra.contract_agreement_id=a.id where a.status='active' and cs.obligation_status='active' and ra.id is null) then perform public.raise_phase3b6c1_failure('expiring_target_assignment_missing','{}');end if;
 if exists(select 1 from public.contract_agreements a join public.contract_seasons cs on cs.contract_id=a.id and cs.league_season_id=target.id join public.season_roster_assignments ra on ra.assignment_set_id=aset.id and ra.contract_agreement_id=a.id where a.status='active' and cs.obligation_status='active' and(ra.league_team_id<>a.league_team_id or ra.sleeper_player_id<>a.player_id or ra.target_contract_season_id<>cs.id)) then perform public.raise_phase3b6c1_failure('expiring_target_assignment_conflict','{}');end if;
 if exists(select 1 from public.contract_agreements a join public.contract_seasons cs on cs.contract_id=a.id and cs.league_season_id=target.id join public.rollover_contract_releases rel on rel.rollover_execution_id=x.id and rel.contract_agreement_id=a.id where a.status='active' and cs.obligation_status='active') then perform public.raise_phase3b6c1_failure('expiring_release_conflict','{}');end if;
 if exists(select 1 from public.contract_agreements a join public.contract_seasons cs on cs.contract_id=a.id and cs.league_season_id=target.id join public.rollover_commissioner_holds h on h.rollover_execution_id=x.id and h.source_contract_agreement_id=a.id and h.hold_status='active' where a.status='active' and cs.obligation_status='active') then perform public.raise_phase3b6c1_failure('expiring_hold_conflict','{}');end if;
 if exists(select 1 from public.contract_agreements a join public.contract_seasons cs on cs.contract_id=a.id and cs.league_season_id=target.id join public.prepared_free_agent_eligibilities f on f.eligibility_set_id=faset.id and f.player_id=a.player_id where a.status='active' and cs.obligation_status='active' and f.eligibility_status in('prepared_free_agent','released_publication_blocked')) then perform public.raise_phase3b6c1_failure('expiring_free_agent_conflict','{}');end if;
 contracthash:=public.rollover_material_fingerprint(coalesce((select jsonb_agg(jsonb_build_object('agreement',to_jsonb(a)-'created_at'-'updated_at','season',to_jsonb(cs)-'created_at'-'updated_at') order by a.end_season,a.league_team_id,a.player_id,a.id) from public.contract_agreements a join public.contract_seasons cs on cs.contract_id=a.id and cs.league_season_id=target.id where a.league_id=x.league_id),'[]'::jsonb));
 releasehash:=public.rollover_material_fingerprint(coalesce((select jsonb_agg(release_fingerprint order by contract_agreement_id,id) from public.rollover_contract_releases where rollover_execution_id=x.id),'[]'::jsonb));
 holdhash:=public.rollover_material_fingerprint(coalesce((select jsonb_agg(creation_fingerprint order by source_contract_agreement_id,id) from public.rollover_commissioner_holds where rollover_execution_id=x.id and hold_status='active'),'[]'::jsonb));
 for r in select a.id agreement_id,cs.id season_id,a.player_id,a.league_team_id,a.status agreement_status,cs.obligation_status,a.start_season,a.end_season,rel.id release_id,h.id hold_id,fa.eligibility_status fa_status
  from public.contract_agreements a join public.contract_seasons cs on cs.contract_id=a.id and cs.league_season_id=target.id
  left join public.rollover_contract_releases rel on rel.rollover_execution_id=x.id and rel.contract_agreement_id=a.id
  left join public.rollover_commissioner_holds h on h.rollover_execution_id=x.id and h.source_contract_agreement_id=a.id and h.hold_status='active'
  left join public.prepared_free_agent_eligibilities fa on fa.eligibility_set_id=faset.id and fa.player_id=a.player_id
  where a.league_id=x.league_id order by a.end_season,a.league_team_id,a.player_id,a.id loop
  expected:=expected+1;if earliest is null or r.end_season<earliest then earliest:=r.end_season;end if;
  if r.hold_id is not null then state:='commissioner_hold_excluded';reason:='active_commissioner_hold';held:=held+1;
  elsif r.release_id is not null then state:='released_excluded';reason:='certified_release';released:=released+1;
  elsif r.agreement_status<>'active' or r.obligation_status<>'active' then state:='terminal_or_inactive_excluded';reason:='terminal_or_inactive_target_obligation';terminal:=terminal+1;
  elsif r.end_season between x.target_season and x.target_season+3 then state:='prepared_expiring_contract';reason:='active_expiry_within_four_season_horizon';prepared:=prepared+1;
  elsif r.end_season>x.target_season+3 then state:='active_beyond_horizon';reason:='active_expiry_beyond_four_season_horizon';beyond:=beyond+1;
  else state:='conflicting_evidence';reason:='expiry_unresolved';conflicts:=conflicts+1;end if;
  rowhash:=public.rollover_material_fingerprint(jsonb_build_object('schema','phase3b10d-expiring-row-v1','execution',x.id,'agreement',r.agreement_id,'season',r.season_id,'player',r.player_id,'team',r.league_team_id,'status',state,'reason',reason,'target_status',r.obligation_status,'ordinal',x.target_season-r.start_season+1,'expiry',r.end_season,'years_until',r.end_season-x.target_season,'release',r.release_id,'hold',r.hold_id,'snapshot',snap.aggregate_snapshot_fingerprint,'contract_hash',contracthash,'release_hash',releasehash,'hold_hash',holdhash,'roster_hash',aset.aggregate_assignment_set_hash,'fa_hash',faset.aggregate_set_hash));
  material:=material||jsonb_build_array(jsonb_build_object('expiry',r.end_season,'team',r.league_team_id,'player',r.player_id,'agreement',r.agreement_id,'hash',rowhash));end loop;
 sethash:=public.rollover_material_fingerprint(jsonb_build_object('schema','phase3b10d-expiring-set-v1','execution',x.id,'horizon_start',x.target_season,'horizon_end',x.target_season+3,'rows',material));
 select * into existing from public.prepared_expiring_contract_sets where league_id=x.league_id and target_season_id=target.id for update;
 if found then if existing.rollover_execution_id<>x.id or existing.aggregate_set_hash<>sethash or existing.expected_row_count<>expected then perform public.raise_phase3b6c1_failure('expiring_set_conflict','{}');end if;if(select count(*) from public.prepared_expiring_contract_eligibilities where expiring_set_id=existing.id)<>expected then perform public.raise_phase3b6c1_failure('expiring_set_hash_mismatch','{}');end if;return jsonb_build_object('evaluated_agreement_count',expected,'prepared_expiring_count',prepared,'active_beyond_horizon_count',beyond,'released_exclusion_count',released,'commissioner_hold_exclusion_count',held,'terminal_inactive_exclusion_count',terminal,'conflicting_evidence_count',conflicts,'eligibility_rows_written',0,'earliest_expiry_year',earliest,'latest_visible_expiry_year',x.target_season+3,'compatible_replay_count',1,'mutation_count',0,'postcondition_count',13,'aggregate_set_hash',sethash,'validation_codes',jsonb_build_array('target_season','contract_population','canonical_owner','target_roster','release_hold','free_agent','four_season_horizon','cutover_lock','unpublished'));end if;
 perform set_config('app.rollover_typed_execution','phase3b10d-v1',true);
 insert into public.prepared_expiring_contract_sets(rollover_execution_id,league_id,target_season_id,source_snapshot_hash,contract_evidence_hash,release_evidence_hash,commissioner_hold_evidence_hash,target_roster_set_hash,free_agent_set_hash,visible_horizon_length,horizon_start_season,horizon_end_season,expected_row_count,aggregate_set_hash,status,schema_version)
 values(x.id,x.league_id,target.id,snap.aggregate_snapshot_fingerprint,contracthash,releasehash,holdhash,aset.aggregate_assignment_set_hash,faset.aggregate_set_hash,4,x.target_season,x.target_season+3,expected,sethash,'prepared','phase3b10d-expiring-v1') returning * into existing;
 for r in select a.id agreement_id,cs.id season_id,a.player_id,a.league_team_id,a.status agreement_status,cs.obligation_status,a.start_season,a.end_season,rel.id release_id,h.id hold_id
  from public.contract_agreements a join public.contract_seasons cs on cs.contract_id=a.id and cs.league_season_id=target.id left join public.rollover_contract_releases rel on rel.rollover_execution_id=x.id and rel.contract_agreement_id=a.id left join public.rollover_commissioner_holds h on h.rollover_execution_id=x.id and h.source_contract_agreement_id=a.id and h.hold_status='active' where a.league_id=x.league_id order by a.end_season,a.league_team_id,a.player_id,a.id loop
  if r.hold_id is not null then state:='commissioner_hold_excluded';reason:='active_commissioner_hold';elsif r.release_id is not null then state:='released_excluded';reason:='certified_release';elsif r.agreement_status<>'active' or r.obligation_status<>'active' then state:='terminal_or_inactive_excluded';reason:='terminal_or_inactive_target_obligation';elsif r.end_season between x.target_season and x.target_season+3 then state:='prepared_expiring_contract';reason:='active_expiry_within_four_season_horizon';elsif r.end_season>x.target_season+3 then state:='active_beyond_horizon';reason:='active_expiry_beyond_four_season_horizon';else state:='conflicting_evidence';reason:='expiry_unresolved';end if;
  rowhash:=public.rollover_material_fingerprint(jsonb_build_object('schema','phase3b10d-expiring-row-v1','execution',x.id,'agreement',r.agreement_id,'season',r.season_id,'player',r.player_id,'team',r.league_team_id,'status',state,'reason',reason,'target_status',r.obligation_status,'ordinal',x.target_season-r.start_season+1,'expiry',r.end_season,'years_until',r.end_season-x.target_season,'release',r.release_id,'hold',r.hold_id,'snapshot',snap.aggregate_snapshot_fingerprint,'contract_hash',contracthash,'release_hash',releasehash,'hold_hash',holdhash,'roster_hash',aset.aggregate_assignment_set_hash,'fa_hash',faset.aggregate_set_hash));
  insert into public.prepared_expiring_contract_eligibilities(expiring_set_id,league_id,target_season_id,contract_agreement_id,target_contract_season_id,player_id,canonical_league_team_id,eligibility_status,eligibility_reason_code,target_contract_status,contract_season_ordinal,years_remaining,expiry_season,years_until_expiry,in_visible_horizon,release_id,commissioner_hold_id,source_snapshot_hash,contract_evidence_hash,release_evidence_hash,hold_evidence_hash,roster_evidence_hash,free_agent_evidence_hash,deterministic_row_fingerprint)
  values(existing.id,x.league_id,target.id,r.agreement_id,r.season_id,r.player_id,r.league_team_id,state,reason,r.obligation_status,x.target_season-r.start_season+1,greatest(r.end_season-x.target_season+1,0),r.end_season,r.end_season-x.target_season,state='prepared_expiring_contract',r.release_id,r.hold_id,snap.aggregate_snapshot_fingerprint,contracthash,releasehash,holdhash,aset.aggregate_assignment_set_hash,faset.aggregate_set_hash,rowhash);written:=written+1;end loop;
 if written<>expected then perform public.raise_phase3b6c1_failure('expiring_population_incomplete','{}');end if;
 return jsonb_build_object('evaluated_agreement_count',expected,'prepared_expiring_count',prepared,'active_beyond_horizon_count',beyond,'released_exclusion_count',released,'commissioner_hold_exclusion_count',held,'terminal_inactive_exclusion_count',terminal,'conflicting_evidence_count',conflicts,'eligibility_rows_written',written,'earliest_expiry_year',earliest,'latest_visible_expiry_year',x.target_season+3,'compatible_replay_count',0,'mutation_count',written+1,'postcondition_count',13,'aggregate_set_hash',sethash,'validation_codes',jsonb_build_array('target_season','contract_population','canonical_owner','target_roster','release_hold','free_agent','four_season_horizon','cutover_lock','unpublished'));
end$$;

create or replace function public.execute_rollover_typed_handler_phase3b10d_private(p_operation jsonb,p_rollover_execution_id uuid,p_execution_plan_id uuid,p_approval_id uuid,p_actor uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$declare code text:=p_operation->>'operation_type';result jsonb;begin if code<>'RECONCILE_EXPIRING_CONTRACT_ELIGIBILITY' then return public.execute_rollover_typed_handler_phase3b10c_private(p_operation,p_rollover_execution_id,p_execution_plan_id,p_approval_id,p_actor);end if;if(p_operation->>'operation_index')::int<>25 then perform public.raise_phase3b6c1_failure('unsupported_handler_version','{}');end if;result:=public.write_prepared_expiring_phase3b10d_private(p_rollover_execution_id,p_execution_plan_id,p_approval_id,p_actor);return jsonb_build_object('operation_code',code,'handler_version',1,'result',result||jsonb_build_object('operation_mutation_count',(result->>'mutation_count')::int));end$$;
do $$declare d text;begin select pg_get_functiondef('public.execute_rollover_plan_phase3b10c_private(jsonb,uuid)'::regprocedure) into d;d:=replace(d,'execute_rollover_plan_phase3b10c_private','execute_rollover_plan_phase3b10d_private');d:=replace(d,'execute_rollover_typed_handler_phase3b10c_private','execute_rollover_typed_handler_phase3b10d_private');d:=replace(d,'''RECONCILE_FREE_AGENT_ELIGIBILITY'')','''RECONCILE_FREE_AGENT_ELIGIBILITY'',''RECONCILE_EXPIRING_CONTRACT_ELIGIBILITY'')');d:=replace(d,'Phase 3B.10C','Phase 3B.10D');d:=replace(d,'phase3b10c-v1','phase3b10d-v1');execute d;end$$;
create or replace function public.execute_rollover_plan_authenticated(p_request jsonb) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$declare actor uuid:=public.require_authenticated_user();x public.rollover_executions%rowtype;begin if p_request?'actor_user_id' or p_request?'executed_by' or p_request?'contract_ids' or p_request?'expiry_year' or p_request?'horizon' or p_request?'league_team_id' then raise exception 'actor or expiring-contract material spoofing forbidden';end if;select * into x from public.rollover_executions where id=(p_request->>'rollover_execution_id')::uuid;if x.id is null then raise exception 'execution not found';end if;perform public.require_commissioner_authority(x.league_id);return public.execute_rollover_plan_phase3b10d_private(p_request,actor);end$$;
revoke all on function public.write_prepared_expiring_phase3b10d_private(uuid,uuid,uuid,uuid),public.execute_rollover_typed_handler_phase3b10d_private(jsonb,uuid,uuid,uuid,uuid),public.execute_rollover_plan_phase3b10d_private(jsonb,uuid),public.guard_phase3b10d_prepared_expiring() from public,anon,authenticated,service_role;
revoke all on function public.execute_rollover_plan_authenticated(jsonb) from public,anon,authenticated,service_role;grant execute on function public.execute_rollover_plan_authenticated(jsonb) to authenticated;
commit;
